// ====== DỮ LIỆU NGÀNH THỦY SẢN — task "quet-nganh-thuy-san" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.thuysan = {
  id: "thuysan",
  name: "Thủy sản",
  icon: "🐟",
  order: 3,
  scope: "VHC, ANV, FMC, MPC, IDI, CMX",
  subtitle: "Sentiment ngành thủy sản VN theo chuỗi giá trị — xuất khẩu & thị trường, thuế & phòng vệ thương mại, nguyên liệu/nuôi trồng, chi phí đầu vào, tỷ giá, rào cản (IUU), tài chính, dòng tiền. Phạm vi: VHC, ANV, FMC, MPC, IDI, CMX (+ ASM, ABT). Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-09-15T02:10:44+07:00",
  factors: {
  export:"Xuất khẩu & thị trường", tariff:"Thuế & phòng vệ TM", material:"Nguyên liệu & nuôi trồng",
  feed:"Chi phí đầu vào", fx:"Tỷ giá", policy:"Pháp lý & rào cản (IUU)", finance:"Tài chính DN", market:"Thị trường & dòng tiền"
},
  sentiment: {
    score: -1, date: "2026-09-14",
    reason: "Tự động tổng hợp từ 10 tín hiệu mới nhất trong 3 ngày gần nhất. Tiêu cực: Xuất khẩu cá tra sang Hoa Kỳ năm 2026: Áp lực gia tăng từ thuế, bảo hộ và sức mua yếu - vasep.com.vn (vasep.com.vn, 14/09/2026); Chính sách thuế Hoa Kỳ đang làm xoay chuyển thương mại thủy sản thế giới - vasep.com.vn (vasep.com.vn, 14/09/2026). Có 8 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:2, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC"], title:"Vĩnh Hoàn tháng 5: doanh thu thuần 1.737 tỷ (+44%), Mỹ +46%, sản phẩm phụ (C&G) +102%", desc:"Ý nghĩa đầu tư: Thị trường Mỹ (633 tỷ, +46%) và EU (+81%), TQ (+50%) đồng loạt phục hồi; mảng sản phẩm phụ collagen/gelatin bật +102% lên 336 tỷ — củng cố biên lợi nhuận và vị thế dẫn đầu cá tra của VHC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"export", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Ngành bước vào cao điểm đơn hàng tháng 7-8; cá tra 5T XK +12,6% (905 triệu USD), TQ/HK tăng mạnh", desc:"Ý nghĩa đầu tư: Cầu Mỹ-TQ phục hồi, tồn kho thấp và nguồn cung cá thịt trắng tự nhiên thắt chặt giúp DN giữ/đẩy giá bán; cao điểm cuối năm hỗ trợ doanh số — tích cực cho cả cá tra (VHC/ANV/IDI) lẫn tôm (FMC/MPC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"tariff", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","MPC","CMX"], title:"Sao Ta kẹt thuế Mỹ: mỗi container phải đóng cọc 25%, tạm chỉ bán hàng không chịu thuế", desc:"Ý nghĩa đầu tư: Tiền cọc 25%/container gây kẹt vốn tại thị trường Mỹ; FMC dồn sang Nhật (30%)/EU (25%) và tập trung sản phẩm biên cao — rủi ro thuế tôm tiếp tục đè biên nhóm FMC/MPC/CMX.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"finance", impact:1, date:"2026-06-29", srcDate:"29/06/2026", isNew:true, aff:["MPC"], title:"Minh Phú khánh thành nhà máy chế biến Minh Phú Khánh An (Cà Mau), tự động hoá cao", desc:"Ý nghĩa đầu tư: 5T/2026 MPC XK >19.726 tấn tôm, doanh số >211,7 triệu USD, LN ~489,3 tỷ; nhà máy mới ứng dụng robot/tự động hoá giúp tối ưu chi phí, đẩy hàng GTGT — nâng năng lực cạnh tranh MPC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/minh-phu-mpc-khanh-thanh-nha-may-che-bien-thuy-san-minh-phu-khanh-an-tai-ca-mau-post393104.html"},
    {factor:"finance", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["ANV","FMC"], title:"Dự báo LNST 2026: ANV ~1.100 tỷ (+10%), FMC ~400 tỷ (+15%) — Chứng khoán NH Việt Nam", desc:"Ý nghĩa đầu tư: Giá cá tra & cá rô phi neo cao cùng cầu các thị trường trọng điểm tích cực hỗ trợ ANV; FMC kỳ vọng phục hồi lợi nhuận nhờ đa dạng thị trường dù vướng thuế Mỹ.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"material", impact:0, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Giá cá tra nguyên liệu neo >30.000đ/kg; chi phí nhiên liệu cao do căng thẳng Mỹ-Iran", desc:"Ý nghĩa đầu tư: Nguyên liệu cao phản ánh đơn hàng dồi dào nhưng cũng bào mòn biên nếu không chuyển được sang giá bán; chi phí nhiên liệu (Mỹ-Iran) đẩy chi phí khai thác/nuôi/vận chuyển — theo dõi biên gộp Q2.", srcName:"Tin nhanh chứng khoán (ĐTCK)/VASEP", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"market", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","ANV","MPC","IDI"], title:"Tuần qua cổ phiếu thủy sản điều chỉnh nhẹ: FMC -0,98%, ANV -0,91%, MPC -0,63%, IDI -3,61%", desc:"Ý nghĩa đầu tư: Nhóm phân hoá và chốt lời ngắn hạn trước mùa cao điểm dù triển vọng tích cực; dòng tiền chọn lọc mã có hiệu suất vận hành tốt (ưu tiên VHC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "feed", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026 (truy xuất)", "isNew": false, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Khô đậu tương CBOT: 357.0 USD/tấn ngắn (+2.9% phiên 14/09)", "desc": "Ý nghĩa đầu tư: Khô đậu đi ngang, chi phí thức ăn ít thay đổi.", "srcName": "Yahoo Finance (ZM=F)", "url": "https://finance.yahoo.com/quote/ZM=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026 (truy xuất)", "isNew": false, "aff": ["VHC", "ANV", "FMC", "MPC", "IDI", "CMX"], "title": "Tỷ giá USD/VND: 25984.0 đồng (+0.2% phiên 14/09)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026 (truy xuất)", "isNew": true, "aff": ["ANV", "IDI", "FMC", "VHC", "MPC", "CMX"], "title": "Nhóm thủy sản phiên 14/09: 1 mã tăng / 3 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — ANV -2.2%; IDI -1.3%; FMC -1.0%; VHC +0.2%; MPC +0.0%; CMX +0.0%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "243b1d406c671555", "factor": "export", "impact": -1, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Xuất khẩu cá tra sang Hoa Kỳ năm 2026: Áp lực gia tăng từ thuế, bảo hộ và sức mua yếu - vasep.com.vn", "desc": "Rule-based: Xuất khẩu cá tra sang Hoa Kỳ năm 2026: Áp lực gia tăng từ thuế, bảo hộ và sức mua yếu vasep.com.vn Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "vasep.com.vn", "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOMFlwOUxTRUdqbXV1OHZpalNVSFBxc3VwSUVLLTBqSDhTUkdaaVlmV1FqWlBKZlJIZnpvTWxtenlIdzFWYjExbDRXUGZvOWJoT1JRT25rS1RMYlBTM3ZZMFh4d25YXzNTbWVHbnRjVWU2VEV4MlhRbVdMM0RZUWdIckRCMjJsUHRGbHdmYy1yS19temZna3Fma1B2Q0ptY3NZc0ZhVk5tMW1GbER5N2FMMjJLR3JWNXhBRzI40gG7AUFVX3lxTE4wWXA5TFNFR2ptdXU4dmlqU1VIUHFzdXBJRUstMGpIOFNSR1ppWWZXUWpaUEpmUkhmem9NbG16eUh3MVZiMTFsNFdQZm85YmhPUlFPbmtLVExiUFMzdlkwWHh3blhfM1NtZUdudGNVZTZURXgyWFFtV0wzRFlRZ0hyREIyMmxQdEZsd2ZjLXJLX216ZmdrcWZrUHZDSm1jc1lzRmFWTm0xbUZsRHk3YUwyMktHclY1eEFHMjg?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "fcf739d940f59ebf", "factor": "tariff", "impact": -1, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Chính sách thuế Hoa Kỳ đang làm xoay chuyển thương mại thủy sản thế giới - vasep.com.vn", "desc": "Rule-based: Chính sách thuế Hoa Kỳ đang làm xoay chuyển thương mại thủy sản thế giới vasep.com.vn Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "vasep.com.vn", "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxPWHc4T0dZU3lQLTFES3NTYnVTenJKQUxJcXFQcjJFUFRSMVFHeGdhdVJHUVprX0RNN29YY3B1OUtnRElsU2hubWtBbEtseWw0OS1YM0J0Vy1ZX0phbVZrYThMZmRKUUVUUTFUc3FNZzc3MU90eEY2U1czNFZjT0drSnotV3h5dUh6b0FVdXBveXRua2VMVlhid1VhcEYwT2YxWVFlMVg4N1pmNll30gGsAUFVX3lxTE9YdzhPR1lTeVAtMURLc1NidVN6ckpBTElxcVByMkVQVFIxUUd4Z2F1UkdRWmtfRE03b1hjcHU5S2dESWxTaG5ta0FsS2x5bDQ5LVgzQnRXLVlfSmFtVmthOExmZEpRRVRRMVRzcU1nNzcxT3R4RjZTVzM0VmNPR2tKei1XeHl1SHpvQVV1cG95dG5rZUxWWGJ3VWFwRjBPZjFZUWUxWDg3WmY2WXc?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "aabdb47be40eb493", "factor": "market", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Điểm tin thủy sản thế giới ngày 14/9/2026 - vasep.com.vn", "desc": "Rule-based: Điểm tin thủy sản thế giới ngày 14/9/2026 vasep.com.vn Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "vasep.com.vn", "url": "https://news.google.com/rss/articles/CBMigwFBVV95cUxQLXNxTWxndEVuWF9ScUpHQm9IVl9nVmVLYVRUVUdJdHdYSGtZaS1oUnFfU0htX2dDbk5GdWJhdEdtNWVOWU9qU3BDdUdZd25FbVdtOGlpQU1IX3RHUWZOTEdrZmJnQ19RRTV2OW43bGk3ZlRQLUJuY0FhZlZUV2R4ZEdKSdIBgwFBVV95cUxQLXNxTWxndEVuWF9ScUpHQm9IVl9nVmVLYVRUVUdJdHdYSGtZaS1oUnFfU0htX2dDbk5GdWJhdEdtNWVOWU9qU3BDdUdZd25FbVdtOGlpQU1IX3RHUWZOTEdrZmJnQ19RRTV2OW43bGk3ZlRQLUJuY0FhZlZUV2R4ZEdKSQ?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "d28654f4a9cfaa89", "factor": "market", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "The Top 10 Best Aquaculture Management Platforms In Africa 2026: - Nubia Magazine!", "desc": "Rule-based: The Top 10 Best Aquaculture Management Platforms In Africa 2026: Nubia Magazine! Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Nubia Magazine!", "url": "https://news.google.com/rss/articles/CBMigwFBVV95cUxQMlNqMHctNWtkZERRZGhDanNpVXROR244dHhSYzJtSVpwVDhjT1BEWVU4YkNfMjZkWDFIVDdxUlhLT1E1RHpscFZ0Q1oyT2F2TGZYcDJjMVJxTDhwTGhIdmVZcnJRczhPUGJ2ZWxFNjlaclBvOFlqUE9qTC1lbGpCY3Rtaw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "aa8b2864b960ff2e", "factor": "market", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Croquette cá tra ướp muối của Vĩnh Hoàn giành giải cao nhất tại Seafood Excellence Asia 2026 - vasep.com.vn", "desc": "Rule-based: Croquette cá tra ướp muối của Vĩnh Hoàn giành giải cao nhất tại Seafood Excellence Asia 2026 vasep.com.vn Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "vasep.com.vn", "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxQZElWbmttZDdBZUY0M3NfYllUMUR4cm9MMFBYQXZpeklmTnI1SW1UZ3ViYmJ5N2lBVk9KZUNnLWhDaTdmX0xmVWdPaGU0T0QwSjB1RUwzTlRjYTF5SGg1bnVGeVBObnNEc3lzXzE5TWtvRl93b2ZwVzd4eDVLU0c1Wk1CcFRoaVZpbHExSnA3ODh6VGxGSHR3cHhuUlgycGRvdkdDQXNRblNYa2xrQjlOV0tOMDRZNEhGX2pXR1VSWGo0NGd1YjhB0gHHAUFVX3lxTFBkSVZua21kN0FlRjQzc19iWVQxRHhyb0wwUFhBdml6SWZOcjVJbVRndWJiYnk3aUFWT0plQ2ctaENpN2ZfTGZVZ09oZTRPRDBKMHVFTDNOVGNhMXlIaDVudUZ5UE5uc0RzeXNfMTlNa29GX3dvZnBXN3h4NUtTRzVaTUJwVGhpVmlscTFKcDc4OHpUbEZIdHdweG5SWDJwZG92R0NBc1FuU1hrbGtCOU5XS04wNFk0SEZfaldHVVJYajQ0Z3ViOEE?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "9e9b35ff5d8a2335", "factor": "export", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "China wholesale shrimp prices: Ecuadorian products ease, Argentine reds steady - Undercurrent News", "desc": "Rule-based: China wholesale shrimp prices: Ecuadorian products ease, Argentine reds steady Undercurrent News Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Undercurrent News", "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxORmNXX2s2MUcyejlma2hybXRBbTdYU2Zpd1RKNlhUdGhmY213bDcwTThqY2plNWt3aUx4TEQ5emVZUzBJZDZjRjB2cXd5TXpHRG5UWnpZa1hrRWdVWlYyUldIR0o0Zmc0NVJpZU0zdG5SblpfSWZlTU85ZkVpSFlMd1NUbkJ4NG05dmhEZTlCalFjcmFyQ0pEZTkxVTZtN3lNWHZnQnI0YXB3OVpyMllIUXh2RkdtUUNodE9Yc0x3?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "b505eda573d9c547", "factor": "market", "impact": 0, "date": "2026-09-14", "srcDate": "14/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Catch & Culture Review: Research gaps and future directions for penaeid shrimp larvae nutrition and rearing - Global Seafood Alliance", "desc": "Rule-based: Catch & Culture Review: Research gaps and future directions for penaeid shrimp larvae nutrition and rearing Global Seafood Alliance Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Global Seafood Alliance", "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxNb1JGdGZ0V1A5czE2RmZ3RHB5ZXBCSjZ2bkFlaGo4M0lVZDlJbjdDSW9NaG9RRGp4WUVuVFZOVzNlcTlMRVZyMGV5RTVpTnI4LUg4VVpVeVFUTGpXa0hJMUdLOXlmbzkyZ2ZvaF9wS3QxUU1iRWoyMWNiemVKYWNZc1dmWUpiR2V6TmNMNXAtNUZvT2p2aDRERmNJTTFoUkU3RDlfWXgzUFpNdmpHRUVxSkhLOF83UjVXUzE0d2lOY0lOcDNGSkN1WkRVYmllVzNSNlVsZll2MjhscW5r?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "f49fb22114450ab3", "factor": "market", "impact": 0, "date": "2026-09-11", "srcDate": "11/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Shrimp Processing Plant Setup in India - IMARC Group", "desc": "Rule-based: Shrimp Processing Plant Setup in India IMARC Group Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "IMARC Group", "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTE9vNXJBMXk1UU1MOHJFZkliYnRUTEFscUFaSzh3T3RUM0U5Mmo1VkRTUnZFVDl2c3d0eTB5UXlEZTJ5UmYxUFllTEQ2ZXlVUUk4eVNBckx3TFNROUJJeURua0Y0b1pRN0ZTRnRycWtyYS1SSlFfaVVEei13?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
  ["Thức ăn thủy sản","Giá đậu nành/bột cá; tự chủ thức ăn","(đầu vào) ASM, các DN tự chủ","Giá nguyên liệu thức ăn giảm; tự chủ cao"],
  ["Con giống & nuôi trồng","Vùng nuôi tự chủ; giá cá tra/tôm nguyên liệu; dịch bệnh","VHC, ANV, FMC, MPC","Giá nguyên liệu hợp lý; vùng nuôi tự chủ; ít dịch bệnh"],
  ["Chế biến","Công suất; tỷ trọng hàng GTGT; sản phẩm phụ (collagen)","VHC, FMC, MPC, IDI, CMX","Công suất chạy cao; tăng hàng GTGT & C&G"],
  ["Xuất khẩu","Đơn hàng; thị trường Mỹ/TQ/EU/Nhật; giá bán","VHC, ANV, FMC, MPC","Đơn hàng tốt; giá XK tăng; đa dạng thị trường"],
  ["Thị trường tiêu thụ","Thuế CBPG/đối ứng; rào cản IUU/MMPA; cạnh tranh Ecuador/Ấn Độ","VHC, FMC, MPC","Thuế thấp/miễn trừ; rào cản nới; cạnh tranh giảm"]
],
  tickers: [
  ["VHC","Cá tra; thị trường Mỹ/TQ; mảng C&G (collagen); giá cá tra","Giá cá tra & giá XK tăng; thuế Mỹ thấp; C&G tăng","Thuế CBPG Mỹ cao; giá cá tra giảm; cầu Mỹ yếu"],
  ["ANV","Cá tra; mở rộng Trung Quốc; tự chủ vùng nuôi & thức ăn","Thị phần TQ tăng; biên cải thiện; tự chủ chuỗi","Phụ thuộc TQ; giá cá tra giảm; chi phí tăng"],
  ["IDI","Cá tra; thị trường TQ/ASEAN; tồn kho cá","Giá cá tra phục hồi; tồn kho lãi","Giá cá tra yếu; tồn kho lỗ; biên mỏng"],
  ["FMC","Tôm; thị trường Nhật/Mỹ; vùng nuôi; hàng GTGT","Đơn tôm tốt; Nhật ổn định; vùng nuôi mở rộng","Thuế CBPG tôm Mỹ; cạnh tranh Ecuador/Ấn Độ; giá tôm giảm"],
  ["MPC","Tôm (lớn nhất); chuỗi khép kín; thị trường Mỹ","Giá tôm tăng; thị phần Mỹ giữ; chuỗi hiệu quả","Thuế tôm Mỹ 25,76%; giá tôm thấp; dịch bệnh"],
  ["CMX","Tôm; thị trường EU; tôm sinh thái","Cầu EU tốt; giá tôm tăng; chứng nhận sinh thái","Rào cản EU; giá tôm giảm; chi phí cao"]
],
  sources: [
    ["VASEP","https://vasep.com.vn/","Số liệu & dự báo xuất khẩu tôm, cá tra, cá ngừ; thuế Mỹ"],
    ["Tổng cục Hải quan","https://www.customs.gov.vn/","Kim ngạch xuất nhập khẩu theo tháng"],
    ["Thị trường cá tra","https://www.thitruongcatra.com/","Giá cá tra nguyên liệu, thị trường"],
    ["Vĩnh Hoàn (VHC)","https://www.vinhhoan.com/","IR: KQKD, sản lượng, mảng C&G"],
    ["Sao Ta (FMC)","https://fimexvn.com/","IR: doanh số tôm theo tháng, thị trường"],
    ["Nam Việt (ANV)","https://navicorp.com.vn/","IR: cá tra, thị trường Trung Quốc"],
    ["Minh Phú (MPC)","https://minhphu.com/","IR: tôm, thuế CBPG Mỹ"]
  ]
};
