// ====== DỮ LIỆU NGÀNH DỆT MAY — task "quet-nganh-det-may" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.detmay = {
  id: "detmay",
  name: "Dệt may",
  icon: "🧵",
  order: 4,
  scope: "TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG",
  subtitle: "Sentiment ngành dệt may VN theo chuỗi giá trị — đơn hàng & xuất khẩu, thuế & thương mại, nguyên liệu (bông/sợi), tỷ giá, lao động, ESG & xanh hóa, tài chính DN, dòng tiền. Phạm vi: TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-08-06T06:07:01+07:00",
  factors: {
    export: "Đơn hàng & xuất khẩu", tariff: "Thuế & thương mại", input: "Nguyên liệu (bông/sợi)",
    fx: "Tỷ giá", labor: "Lao động & chi phí", esg: "ESG & xanh hóa",
    finance: "Tài chính DN", market: "Thị trường & dòng tiền"
  },
  sentiment: {
    score: -1, date: "2026-08-06",
    reason: "Tự động tổng hợp từ 11 tín hiệu mới nhất trong 3 ngày gần nhất. Tiêu cực: US labour tariffs give Bangladesh strategic edge over China, Vietnam - dhakatribune.com (dhakatribune.com, 06/08/2026); US again imposes 10% tariff on Bangladesh - The Daily Star (The Daily Star, 05/08/2026). Có 8 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["HTG","VGT"], title:"Dệt may Hòa Thọ (HTG): XK nửa đầu năm 2026 ~148,5 triệu USD (+14%), doanh thu hợp nhất 2.893 tỷ (+9%), lãi riêng 224,3 tỷ (đạt 56% KH năm)", desc:"Ý nghĩa đầu tư: HTG (mảng may FOB, thuộc VGT) duy trì đà tăng trưởng 2 con số bất chấp thị trường biến động — green flag cho KQKD 6T; cổ tức tiền mặt cao là điểm cộng. Theo dõi đơn hàng nửa cuối năm và rủi ro thị trường Mỹ.", srcName:"Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"export", impact:-1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"VITAS: XK dệt may 5T2026 ~17,81 tỷ USD (+0,6%) — may mặc 13,72 tỷ GIẢM 1,5%; xơ sợi 1,90 tỷ (+9,6%), vải +6,9%", desc:"Ý nghĩa đầu tư: Phân hóa rõ — mảng MAY mặc (TNG, MSH, GIL, HTG) suy yếu cầu, áp lực cho mục tiêu cả năm 48–49 tỷ USD; mảng SỢI/xơ (STK, ADS, VGT) ngược dòng tăng tốt. Ưu tiên mã có tỷ trọng sợi/đơn giá tốt.", srcName:"VITAS / Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"input", impact:-1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:true, aff:["TCM","STK","ADS","VGT"], title:"Giá bông thế giới (ICE) ~78 US cent/lb, tăng ~18% từ đầu năm trên kỳ vọng nguồn cung toàn cầu thắt chặt", desc:"Ý nghĩa đầu tư: Bông neo cao đẩy chi phí đầu vào mảng may/dệt (TCM) và chi phí bông cho kéo sợi; có thể hỗ trợ giá bán sợi nhưng bóp spread bông–sợi nếu cầu yếu (STK, ADS, VGT). Theo dõi chênh bông–sợi.", srcName:"Trading Economics – Cotton", url:"https://tradingeconomics.com/commodity/cotton"},
    {factor:"fx", impact:1, date:"2026-06-17", srcDate:"17/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"Tỷ giá USD/VND căng: tỷ giá trung tâm 25.165 (16/6), NHTM đồng loạt bán USD kịch trần ~26.433", desc:"Ý nghĩa đầu tư: USD mạnh hỗ trợ doanh thu/biên quy đổi cho nhóm xuất khẩu dệt may (đa số doanh thu USD, chi phí VND) — tích cực cho TNG, MSH, HTG, STK. Lưu ý DN vay USD chịu áp lực chi phí tài chính.", srcName:"Thanh Niên", url:"https://thanhnien.vn/gia-usd-hom-nay-1662026-do-tu-do-bat-tang-18526061608200601.htm"},
    {factor:"finance", impact:1, date:"2026-06-13", srcDate:"13/06/2026", isNew:true, aff:["VGT"], title:"Tập đoàn Dệt May Việt Nam (VGT/Vinatex) ước lãi ~763 tỷ đồng 6T2026 (+14%); đơn sợi đầy đến hết T7, may đến T8–9, song đơn hàng đang chậm lại chờ thuế Mỹ", desc:"Ý nghĩa đầu tư: KQKD hợp nhất 6T tích cực cho VGT, nhưng ban lãnh đạo cảnh báo đơn hàng chững lại — lợi nhuận tốt là quá khứ, biến số là đơn quý IV. Theo dõi lấp đầy chuyền và tín hiệu thuế quan.", srcName:"CafeF", url:"https://cafef.vn/tap-doan-det-may-viet-nam-uoc-lai-763-ty-dong-tang-14-trong-6-thang-dau-nam-don-hang-dang-cham-lai-cho-cau-chuyen-thue-quan-cua-my-188260613013603581.chn"},
    {factor:"tariff", impact:-1, date:"2026-06-12", srcDate:"12/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","VGT"], title:"ALERT — Đơn hàng quý IV khan hiếm: khách nhập khẩu 'nghe ngóng' chờ thuế đối ứng song phương Mỹ (sau 24/7), cộng chi phí vận tải biển +30–40% do xung đột Trung Đông", desc:"Ý nghĩa đầu tư: Rủi ro thiếu đơn cuối năm là tâm điểm — nhạy nhất với MSH (tỷ trọng khách Mỹ lớn); cửa sổ thuế tạm 10% hết hạn 24/7 là mốc quyết định dịch chuyển đơn TQ→VN. Quan sát mức thuế thực tế của VN so Indonesia/Campuchia/Bangladesh.", srcName:"Dân trí / Vietstock", url:"https://dantri.com.vn/kinh-doanh/det-may-viet-nam-doi-mat-ap-luc-kep-tu-thue-quan-va-xung-dot-trung-dong-20260612173236317.htm"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "input", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026 (truy xuất)", "isNew": false, "aff": ["TCM", "STK", "ADS", "VGT", "TNG", "MSH"], "title": "Bông ICE: 82.86 cent/lb (+2.1% phiên 05/08)", "desc": "Ý nghĩa đầu tư: Giá bông đi ngang, tác động chi phí ngắn hạn thấp.", "srcName": "Yahoo Finance (CT=F)", "url": "https://finance.yahoo.com/quote/CT=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026 (truy xuất)", "isNew": false, "aff": ["TNG", "MSH", "TCM", "STK", "GIL", "ADS", "VGT", "HTG"], "title": "Tỷ giá USD/VND: 26258.0 đồng (-0.1% phiên 05/08)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026 (truy xuất)", "isNew": true, "aff": ["GIL", "TCM", "HTG", "STK", "MSH", "ADS"], "title": "Nhóm dệt may phiên 05/08: 4 mã tăng / 2 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — GIL +6.9%; TCM +1.8%; HTG -1.4%; STK +0.8%; MSH -0.5%; ADS +0.2%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "865f2da7b67d9360", "factor": "tariff", "impact": -1, "date": "2026-08-06", "srcDate": "06/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "US labour tariffs give Bangladesh strategic edge over China, Vietnam - dhakatribune.com", "desc": "Rule-based: US labour tariffs give Bangladesh strategic edge over China, Vietnam dhakatribune.com Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "dhakatribune.com", "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQYm9GdkpXYzlDMGNWdHNyRW1YbkhlZlVQQWM5Y3ZKRjQ5N0FMRndRQTd0SzZSblJYMk5iYVdVdlFWc0VXTktmdFZZRjBwWFozTzExbGRFNlUyYlVCbmxPdUZ1QkxDNEpnbG5MZE9yUENZNzZBSjY2RFgtYXM1TnQwekZfaHhrdUlzUzRtY05Fd0Q2MGZlWDU2WHRRc01fQdIBngFBVV95cUxQYm9GdkpXYzlDMGNWdHNyRW1YbkhlZlVQQWM5Y3ZKRjQ5N0FMRndRQTd0SzZSblJYMk5iYVdVdlFWc0VXTktmdFZZRjBwWFozTzExbGRFNlUyYlVCbmxPdUZ1QkxDNEpnbG5MZE9yUENZNzZBSjY2RFgtYXM1TnQwekZfaHhrdUlzUzRtY05Fd0Q2MGZlWDU2WHRRc01fQQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "b760aaec68341dd0", "factor": "tariff", "impact": -1, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "US again imposes 10% tariff on Bangladesh - The Daily Star", "desc": "Rule-based: US again imposes 10% tariff on Bangladesh The Daily Star Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "The Daily Star", "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxPTldYQnVJSUpSNVB3WVZodE56RlU5eXl2OG8tOUl1UmRSZ2txX2FKanIzbVIxbWh0R1cwSHgyMW1OMlNZSzVqbVowazRYd0k0LW0zSVpzRDRlQ2ZYYjNRV2p0Tm9fNU9UZW1ULU9VUmJfVTY1Q1JXV2k1ZDFIcXZMVmFtTzZCT3U3N0ZoWGZ0RGxJdGxTaGNXdUlLbVh2RzVEbE9BWHhodTg?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "1576a63f53fb523a", "factor": "tariff", "impact": -1, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "25 bang của Mỹ kiện chính quyền Tổng thống Trump về các mức thuế quan mới - vinatex.com.vn", "desc": "Rule-based: 25 bang của Mỹ kiện chính quyền Tổng thống Trump về các mức thuế quan mới vinatex.com.vn Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "vinatex.com.vn", "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxOTmV6TDE1VDJ0OEJkc1N3a2I5MUl1cVZGRzVtTlBTQkJXWFlBcjdLWFdhZVdxYlI1dEdpNGliMkVEdzB0MldlVjRobW1OcHU5d2NEQU96S29BTzZyaTEwOTFmNnpaS2hrQjhoaEtHRU9IaWtZMVRPTVVkU2ItMXE3aDAyTVRVazJ4UGwtTHZ1eWxmS21HMk9SM0hpY2dRZw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "11e603c996a200bf", "factor": "market", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| TexPro analysis: The hidden $19.1 bn textile-quota contest - Fibre2Fashion", "desc": "Rule-based: | TexPro analysis: The hidden $19.1 bn textile-quota contest Fibre2Fashion Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxOaG5Vb0xfbS1pNURhY2JBWGgtM1cybGFneDBlNE05cWRCbkJPbGVHZlZIbDMyMDBhRjNqUzF3eHZMbjBFVWVhVXo3Y1JzVlZ4Y0V5X0xrd29ueHZpdEdlbXZycHRxSWZfYzZxbWZiNEphZ3VFS3ozVGVnb2RPMHlOLTNaaDNTNEg5SURHT1A1T2l4WGVELWFTUGpfTXVtSlpOTmdnQWVsZVpiek9tTDdGODFweE83bGo0cDItMXdkc0ZLQWptUnJjTHJPeDdFZm8?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "f82641db51618f2e", "factor": "market", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| TexPro analysis: The hidden $19.1 bn textile-quota contest - Fibre2Fashion", "desc": "Rule-based: | TexPro analysis: The hidden $19.1 bn textile-quota contest Fibre2Fashion Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxOOGR0VkZ3ZHJVWmpnOFl2NkVCMEJVYWRTTmtqTVhmSjRWU0pkc3ZuQlFxUUlkQnMzX0Y3aFNyS1g5amVwRG8xdWVNYUlMUEV6VzlKQ0w2ckN3Yll3bENPd0phX21LWkpqR2o1Y2o2cGk0aWxtZVQ4T1phc2tFQjhtRmV6aHRENUpoTFlMaHROaDdUNVBtU0hOQVRaRThLVEpub0h2X1hXTDN5TXU2dmV5cUhHdnhNUWFZZkNLaFNIYWxQVWxzaVE?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "a76be955369a1ed4", "factor": "export", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Vì sao doanh nghiệp xuất khẩu khó tìm khách hàng mới? Nguyên nhân và giải pháp 2026 - Innovative Hub", "desc": "Rule-based: Vì sao doanh nghiệp xuất khẩu khó tìm khách hàng mới? Nguyên nhân và giải pháp 2026 Innovative Hub Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Innovative Hub", "url": "https://news.google.com/rss/articles/CBMiV0FVX3lxTE5qR2tQeWhWdW9iTlc4ZGlrekJzTFJ1RXc5enlEcU5BeFYtYjZpM1phR3YxNTVGTmlzRFhzd0ZvVHkyemxvTWJUV3hxMXRJaElfZ2o3cDBDaw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "1d71dc1d79708ef3", "factor": "input", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "ICE cotton retreats on profit booking, weaker crude oil - Fibre2Fashion", "desc": "Rule-based: ICE cotton retreats on profit booking, weaker crude oil Fibre2Fashion Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxPeEQtUi1ybS1FTVMwTWlwRTNIMFBpWTVzWFhXdkJ2dzZQakhMNmEwUGFoNUtxekx4c3pHU3F1X0FwbEI1emVaYlpNTThITG5NRkxlSk5lclFQVzVYUW1SSlY1aGZXQ0J0WjM5bDFiejRwaTJ5RzdGbnYwb25LVS11bndZZFRud2tKZVhxYUltNXJTblRDbDNIZExZQ0RETWxiT3pxMDQ3VlFwNzJ1R1pwM3UtazU3aU1TaURsYkJjRkJ1Mnc?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "c5daabcdef385a5e", "factor": "market", "impact": 0, "date": "2026-08-05", "srcDate": "05/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Doanh nghiệp nâng cao tuân thủ trong toàn bộ chuỗi cung ứng dệt may - Tin nhanh chứng khoán", "desc": "Rule-based: Doanh nghiệp nâng cao tuân thủ trong toàn bộ chuỗi cung ứng dệt may Tin nhanh chứng khoán Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Tin nhanh chứng khoán", "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxNbkpmQTFqMzZZSHZhMnl6VDZSdmJmNS1XbE1uUld0R1FNTE85UUtKWUhvSkVwZG5qYnVKSlN0Y1JOT25SSkk4Y0FRTmxrTUlEeExUT1pIQVhMbFd3TmNmYVJQTWRtM05KZ1k2Y25mVlM5S3NFLTY2RTNtWVFza0pWcEtyOTFMV0d0ZlQ0SUVXQXJHVUVvTzVEcDEtR0hFN3BWZEVrWERYMmFYUVVVN2pBMktKTDbSAbQBQVVfeXFMTW5KZkExajM2WUh2YTJ5elQ2UnZiZjUtV2xNblJXdEdRTUxPOVFLSllIb0pFcGRuamJ1SkpTdGNSTk9uUkpJOGNBUU5sa01JRHhMVE9aSEFYTGxXd05jZmFSUE1kbTNOSmdZNmNuZlZTOUtzRS02NkUzbVlRc2tKVnBLcjkxTFdHdGZUNElFV0FyR1VFb081RHAxLUdIRTdwVmRFa1hEWDJhWFFVVTdqQTJLSkw2?oc=5", "src": "news", "sourceScope": "local"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
    ["Nguyên liệu (bông/xơ)", "Giá bông thế giới; nhập khẩu xơ; xơ tái chế", "(đầu vào) STK, ADS", "Giá bông/xơ hợp lý; nguồn cung ổn định"],
    ["Sợi (spinning)", "Giá sợi; chênh bông–sợi; cầu Trung Quốc", "STK, ADS, VGT", "Spread sợi tốt; cầu TQ phục hồi; giá xơ thấp"],
    ["Dệt – nhuộm vải", "Tự chủ vải; quy tắc xuất xứ (CPTPP/EVFTA)", "TCM (chuỗi khép kín); điểm nghẽn của ngành", "Đầu tư dệt nhuộm; đáp ứng xuất xứ 'từ sợi/vải trở đi'"],
    ["May (CMT/FOB/ODM)", "Đơn hàng; đơn giá; tỷ trọng FOB/ODM", "TNG, MSH, TCM, GIL, HTG, VGT", "Đơn hàng đầy; dịch lên FOB/ODM; năng suất cao"],
    ["Thương hiệu & phân phối", "OBM; thị trường nội địa; giá trị gia tăng", "Số ít DN có thương hiệu", "Phát triển OBM; biên cao; ít phụ thuộc gia công"],
    ["Thị trường xuất khẩu", "Mỹ/EU/Nhật/Hàn; thuế; dịch chuyển đơn", "TNG, MSH, TCM, HTG", "Thuế thấp/ổn định; đơn dịch từ TQ/Bangladesh về VN"]
  ],
  tickers: [
    ["TNG", "Đơn hàng (Decathlon, Columbia…); công suất chuyền; đơn giá", "Đơn hàng đầy; mở rộng chuyền; thị trường EU tốt", "Cầu Mỹ/EU yếu; đơn giá giảm; tồn kho cao"],
    ["MSH", "FOB/ODM; khách Mỹ (tỷ trọng lớn); nhà máy mới (SH10)", "Đơn FOB tăng; khách Mỹ ổn; nhà máy mới chạy đủ", "Thuế đối ứng Mỹ; mất khách lớn; giá bông tăng"],
    ["TCM", "Chuỗi khép kín sợi–dệt–may; khách Hàn (E-Land); ODM", "Tự chủ chuỗi; đơn ODM biên cao; Hàn/Nhật ổn", "Đơn hàng yếu; lỗ mảng sợi; cạnh tranh khu vực"],
    ["STK", "Sợi tái chế (recycled); giá xơ; cầu TQ; dự án Unitex", "Giá sợi tốt; premium recycled; Unitex vận hành", "Cầu sợi yếu; cạnh tranh sợi TQ; giá dầu (xơ) cao"],
    ["GIL", "May + KCN (Gilimex Phú Bài); hậu vụ kiện Amazon", "KCN cho thuê tốt; đơn hàng may hồi phục", "Mất đơn khách lớn; KCN chậm lấp đầy"],
    ["ADS", "Sợi + khăn (Damsan); giá sợi; BĐS KCN", "Giá sợi tốt; mảng khăn ổn; KCN đóng góp", "Cầu sợi yếu; chi phí đầu vào; đòn bẩy"],
    ["VGT", "Tổng công ty (sợi + may); chu kỳ ngành; hợp nhất", "Ngành hồi phục; mảng sợi có lãi trở lại", "Sợi lỗ; cầu yếu; bộ máy lớn kém linh hoạt"],
    ["HTG", "May FOB (Hòa Thọ); khách ổn định; cổ tức cao", "Đơn hàng đầy; biên ổn định; cổ tức tiền mặt", "Cầu yếu; chi phí lao động tăng; tỷ giá"]
  ],
  sources: [
    ["Hiệp hội Dệt May VN (VITAS)", "https://vietnamtextile.org.vn/", "Kim ngạch, đơn hàng, triển vọng ngành"],
    ["Tổng cục Hải quan", "https://www.customs.gov.vn/", "Kim ngạch xuất khẩu dệt may theo tháng"],
    ["Vinatex", "https://vinatex.com.vn/", "Tin ngành, sản xuất, giá sợi"],
    ["Giá bông – Trading Economics", "https://tradingeconomics.com/commodity/cotton", "Giá bông thế giới (đầu vào sợi)"],
    ["OTEXA (Mỹ)", "https://otexa.trade.gov/", "Số liệu nhập khẩu dệt may vào Mỹ theo nước"],
    ["Bộ Công Thương", "https://moit.gov.vn/", "Chính sách thương mại, FTA, phòng vệ thương mại"],
    ["TNG IR", "https://tng.vn/", "Doanh thu theo tháng, đơn hàng, công suất"],
    ["Dệt may Thành Công (TCM)", "https://www.thanhcongtextile.com/", "IR: KQKD tháng, cơ cấu đơn hàng"]
  ]
};
