// ====== DỮ LIỆU NGÀNH HÀNG HÓA (đường, sữa, sắn, ngô) — task "quet-nganh-hang-hoa" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.hanghoa = {
  id: "hanghoa",
  name: "Hàng hóa",
  icon: "🌾",
  order: 5,
  scope: "SBT, SLS, LSS, QNS, VNM, IDP, MCM, DBC, BAF, HAG",
  subtitle: "Sentiment nhóm hàng hóa nông nghiệp VN (đường, sữa, sắn, ngô/TĂCN) theo giá hàng hóa & chuỗi giá trị — giá đường, giá sữa bột, ngô & thức ăn chăn nuôi, sắn, chi phí đầu vào, tỷ giá, chính sách & phòng vệ TM, tài chính DN. Phạm vi: SBT, SLS, LSS, QNS, VNM, IDP, MCM, DBC, BAF, HAG. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-09-07T20:25:48+07:00",
  factors: {
    sugar: "Đường", milk: "Sữa", corn: "Ngô & TĂCN", cassava: "Sắn",
    input: "Chi phí đầu vào & logistics", fx: "Tỷ giá & nhập khẩu",
    policy: "Chính sách & phòng vệ TM", finance: "Tài chính DN", market: "Thị trường & dòng tiền"
  },
  sentiment: {
    score: 1, date: "2026-09-07",
    reason: "Tự động tổng hợp từ 8 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: FAO Food Price Index rises in August amid broad-based increases, led by sugar - PotatoPro (PotatoPro, 07/09/2026); Sugar Prices Surge on Heat, El Niño & India Imports - Briefs Finance (Briefs Finance, 06/09/2026). Có 4 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    { factor: "corn", impact: -1, date: "2026-06-29", srcDate: "29/06/2026 (truy xuất)", isNew: true, aff: ["DBC","BAF","HAG"], title: "Giá heo hơi tiếp tục giảm: miền Bắc 67–68k, miền Trung 62–67k, miền Nam 61–63k đ/kg", desc: "Ý nghĩa đầu tư: Heo hơi hạ nhiệt và giảm tuần thứ hai liên tiếp ép biên đầu ra của DBC/BAF/HAG; vùng giá 60–68k vẫn có lãi nhưng xu hướng giảm là tín hiệu thận trọng cho lợi nhuận quý 2–3.", srcName: "Thanh Niên", url: "https://thanhnien.vn/gia-heo-hoi-hom-nay-2962026-lai-tiep-tuc-giam-185260629081524846.htm" },
    { factor: "corn", impact: -1, date: "2026-06-25", srcDate: "25/06/2026", isNew: true, aff: ["DBC","BAF","HAG"], title: "ALERT: Bùng phát dịch tả heo châu Phi (ASF) ở Đồng Nai, tiêu hủy đàn ~1.942 con; báo động đỏ miền Bắc", desc: "Ý nghĩa đầu tư: Ổ dịch ASF mới + khuyến cáo tạm dừng tái đàn là rủi ro hai mặt cho DBC/BAF: tăng rủi ro thiệt hại đàn ngắn hạn, nhưng nếu lan rộng sẽ giảm cung và đỡ giá heo cuối năm. Theo dõi sát mức độ lan và tiến độ tái đàn.", srcName: "Một Thế Giới", url: "https://motthegioi.vn/gia-heo-hoi-mien-bac-asf/" },
    { factor: "corn", impact: 0, date: "2026-06-24", srcDate: "24/06/2026 (truy xuất)", isNew: true, aff: ["DBC","BAF","HAG"], title: "Giá ngô nhập ~248,8 USD/tấn (−3,6%); khô đậu tương ~475,9 USD/tấn (+5,2%)", desc: "Ý nghĩa đầu tư: Ngô rẻ hơn hỗ trợ giá thành thức ăn chăn nuôi nhưng khô đậu tăng bù trừ; nguồn cung khô đậu về nhiều tháng 6–7 có thể hạ nhiệt giá → trung tính với biên TĂCN của DBC/BAF.", srcName: "Nhà Bè Agri", url: "https://nhabeagri.com/gia-nong-san/gia-ngo-moi-nhat/" },
    { factor: "fx", impact: -1, date: "2026-06-17", srcDate: "17/06/2026", isNew: true, aff: ["VNM","IDP","MCM","DBC","BAF"], title: "USD/VND căng: tỷ giá trung tâm 25.165, NHTM bán USD kịch trần 26.433 đồng", desc: "Ý nghĩa đầu tư: USD mạnh, giá bán kịch trần làm tăng chi phí nhập bột sữa, ngô và khô đậu (tính bằng USD) → bất lợi biên cho nhóm nhập nguyên liệu VNM/IDP/MCM/DBC/BAF, bù trừ một phần lợi ích giá hàng hóa thế giới giảm.", srcName: "Thanh Niên", url: "https://thanhnien.vn/gia-usd-hom-nay-1662026-do-tu-do-bat-tang-18526061608200601.htm" },
    { factor: "sugar", impact: -1, date: "2026-06-12", srcDate: "12/06/2026", isNew: true, aff: ["SBT","SLS","LSS","QNS"], title: "Đường lậu, không rõ nguồn gốc vẫn tràn lan; VSSA dự báo dư cung kéo dài", desc: "Ý nghĩa đầu tư: Đường nhập lậu Campuchia/Lào (~16.300 đ/kg) cạnh tranh trực tiếp, dư cung tiếp diễn → rủi ro tồn kho và giá bán thấp cho doanh nghiệp đường, tiêu cực ngắn hạn cho SBT/LSS/SLS/QNS.", srcName: "Vietstock", url: "https://vietstock.vn/2026/06/duong-lau-khong-ro-nguon-goc-van-tran-lan-118-1453545.htm" },
    { factor: "cassava", impact: 0, date: "2026-06-12", srcDate: "12/06/2026", isNew: true, aff: ["HAG"], title: "Giá tinh bột sắn xuất khẩu neo cao (~515–540 USD/tấn) nhưng Trung Quốc giảm mua", desc: "Ý nghĩa đầu tư: Giá tinh bột sắn neo cao gần gấp đôi cùng kỳ hỗ trợ doanh nghiệp sắn, song cầu Trung Quốc giảm do bớt dùng cho ethanol là rủi ro đầu ra; tác động gián tiếp, nhẹ tới HAG và DN tinh bột.", srcName: "Vietnam.vn", url: "https://www.vietnam.vn/en/trung-quoc-cham-mua-hang-gia-mot-loai-tinh-bot-cua-viet-nam-giam-sau/" },
    { factor: "sugar", impact: -1, date: "2026-06-05", srcDate: "05/06/2026", isNew: true, aff: ["SBT","SLS","LSS","QNS"], title: "Giá đường nội địa chạm đáy 3 năm dù giá đường thế giới gần đỉnh 5 tháng", desc: "Ý nghĩa đầu tư: Đường kính trắng nội địa chỉ 15.800–16.600 đ/kg do dư cung + đường lậu, ép biên mảng đường của SBT/SLS/LSS/QNS bất chấp giá #11 thế giới cao; chưa thấy catalyst tăng giá nội địa rõ ràng.", srcName: "Dân trí", url: "https://dantri.com.vn/kinh-doanh/duong-lau-bua-vay-nganh-mia-duong-lao-dao-vi-gia-cham-day-20260605091744497.htm" },
    { factor: "milk", impact: 1, date: "2026-06-02", srcDate: "02/06/2026 (truy xuất)", isNew: true, aff: ["VNM","IDP","MCM"], title: "Đấu giá GDT: WMP −3,1% về 3.589 USD/tấn, SMP −3,6%, chỉ số chung −2,8%", desc: "Ý nghĩa đầu tư: Giá bột sữa nhập (WMP/SMP) giảm do dư cung toàn cầu = hạ giá vốn đầu vào, hỗ trợ biên gộp cho VNM/IDP/MCM; tuy nhiên cần bù trừ với tỷ giá USD/VND cao và sức mua trong nước còn yếu (Q1 giảm ~3,7%).", srcName: "GlobalDairyTrade / eDairyNews", url: "https://en.edairynews.com/supply-glut-slashes-global-dairy-auction-prices/" }
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "sugar", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": false, "aff": ["SBT", "SLS", "LSS", "QNS"], "title": "Đường thô ICE #11: 18.4 cent/lb (+1.8% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Giá đường thế giới đi ngang, ít tác động tới nhóm mía đường trong ngắn hạn.", "srcName": "Yahoo Finance (SB=F)", "url": "https://finance.yahoo.com/quote/SB=F", "src": "py"},
    {"factor": "corn", "impact": -1, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": true, "aff": ["DBC", "BAF", "HAG"], "title": "Ngô CBOT: 537.2 cent/bushel (+4.3% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Giá ngô tăng đẩy chi phí thức ăn chăn nuôi, bất lợi biên cho DBC/BAF/HAG.", "srcName": "Yahoo Finance (ZC=F)", "url": "https://finance.yahoo.com/quote/ZC=F", "src": "py"},
    {"factor": "corn", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": false, "aff": ["DBC", "BAF"], "title": "Khô đậu tương CBOT: 355.0 USD/tấn ngắn (+2.8% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Khô đậu tương đi ngang.", "srcName": "Yahoo Finance (ZM=F)", "url": "https://finance.yahoo.com/quote/ZM=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": false, "aff": ["VNM", "IDP", "MCM", "DBC", "BAF"], "title": "Tỷ giá USD/VND: 26054.0 đồng (-0.1% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Tỷ giá USD/VND ổn định, ít tác động chi phí nhập khẩu.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": true, "aff": ["IDP", "SLS", "DBC", "VNM", "HAG", "MCM"], "title": "Nhóm hàng hóa phiên 04/09: 6 mã tăng / 3 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — IDP +15.0%; SLS -1.9%; DBC -1.5%; VNM +1.1%; HAG -1.1%; MCM +0.9%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "a4e32768f9e0f355", "factor": "sugar", "impact": 1, "date": "2026-09-07", "srcDate": "07/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "FAO Food Price Index rises in August amid broad-based increases, led by sugar - PotatoPro", "desc": "Rule-based: FAO Food Price Index rises in August amid broad-based increases, led by sugar PotatoPro Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "PotatoPro", "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNR2VtVlVPdmFMTjNMUE12aXJYb2NHRDZWV0o5QzMyUWdBN2JOTmt3Q2pycmxwbGJmY1d0MDBTYi1ZZnZ3VEV4ZFR0QnNiYmN2OGF0MHN5bGJzS2U5Y0hnY3VyajJNaUoweGxTN04tcERLUWlGajB3alFmbGw0aUtJR19DdHQ4Q2NXY1kzdU9lLWZLdkRWRmFacm9GNl9sbmIweU94OUNqOTFxZw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "ce5bb7da50746f2c", "factor": "sugar", "impact": 0, "date": "2026-09-07", "srcDate": "07/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Sugar Has Outrun the S&P 500 This Year — and the Story Behind It Is Bitter - egamers.io", "desc": "Rule-based: Sugar Has Outrun the S&P 500 This Year — and the Story Behind It Is Bitter egamers.io Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "egamers.io", "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNQnJJXzF6TkkxZlhsV2wtV0MyLVF1NURrbHJFdUM3bndOTVVCQy1NQ0lxNkgyTHVNQ3phYmRvSUlUVU1tRmpEeWdFWnFiZVo3Qk5SdmJSQmFyUGtHWjRRazJKZUdSbUcteFBjbmU5MGNwTXRwVVR4MWFLb2h3UkxISncxQjZSYndhaXN1azM3eFlTRV9nLXc?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "b1b6cfd22e84c55d", "factor": "sugar", "impact": 1, "date": "2026-09-06", "srcDate": "06/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Sugar Prices Surge on Heat, El Niño & India Imports - Briefs Finance", "desc": "Rule-based: Sugar Prices Surge on Heat, El Niño & India Imports Briefs Finance Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Briefs Finance", "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxPaVQtY2h1N29Vd2xqbmNMUUdCdGdsMVRyWlFtRndxYk0tYzlyVVhkUmhlMXJqT0hNSk5Yb0gyR2xIWkVDb1lfS2p1N1RHU2R0eUdKQWozeWNnOGViS1VMMHAyWmJXVmt0aTVnUVNaaFpyMEM3UWRoN2l0djFvWDdNVUNORmUtYUNtNk1MMkc5LUEzdw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "f89aaf2f74bcaf85", "factor": "sugar", "impact": 1, "date": "2026-09-06", "srcDate": "06/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Global food prices rise 1.9% in August with sugar, wheat and maize all higher - Gulf News", "desc": "Rule-based: Global food prices rise 1.9% in August with sugar, wheat and maize all higher Gulf News Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Gulf News", "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxPYUgxY2g5NlpiQ0V4Tl92RzBoY0ZkdnZvVUc2VjJmY1VnTE1SRENvVzBMTXF3ZGRvMHl3MV9XVnVLRW1lS3poVDVwSS1kci1BZEZZU3VKVzlULUIwZXFzSkllcFBTNVBXdjIwcEpSZGFScGNuZTdnalZIWVg1Y3Q3cmh6NnRVNzZNN204U09CZW1kS2llT09jMFpac3paY1g0anJiSUhJZ01pa1pwbFJ5YllIWXpYUzhjTVFFSTFBRHDSAdMBQVVfeXFMUG4yVWViSjN0VXpNZlFTc2xTMlFqSzBfZzdwR0IxV0lDRWhlaGY1cmZCOHNtX3ZpQ0RpSGxLYnhYYmNRYVlFZFFZV0ViSFNJZ0Z2SHlxb0I5SEgzX3VKd0I3THl5d3Q3dDl1ZWJxS1dQSHo3WS0xd3Y4cF8zdzlwdDlKcjBPZWY3bDRXbDM0c2toNmlGd2kySEJpdTBkSWFLbGZmUk9FSThJeHViSnNlV1dRMldMNUNHRWpDT3NBekN0S3dFd1JVLURLbFRvSUFWcFlWRQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "16125f033f49c9a8", "factor": "sugar", "impact": 0, "date": "2026-09-06", "srcDate": "06/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Sugar is outperforming the stock market this year. Here's what's driving it, and where it can go from here - CNBC", "desc": "Rule-based: Sugar is outperforming the stock market this year. Here's what's driving it, and where it can go from here CNBC Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "CNBC", "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxQcTZpMGdtdWNoRTdJR3ZEWGJibDlWMXE0bHAxbUp0UVBHQWNCU0sxZGJBTk10OFRncnhiYkpyOGpTVWZnWXJtN1RtT0pEcndWN2NqWkEyLUdHZ0tIaWRtWHhVWFUwQkRHNGpjUkhLQWlKaGRtQ0tKU252SkZNV0tOUzhCeWpjMGFjNHBPWjBOVW5sNktmbmZLMV90ekRjRXY0cVZhNEo0V18zcHPSAasBQVVfeXFMUHE2aTBnbXVjaEU3SUd2RFhiYmw5VjFxNGxwMW1KdFFQR0FjQlNLMWRiQU5NdDhUZ3J4YmJKcjhqU1VmZ1lybTdUbU9KRHJ3VjdjalpBMi1HR2dLSGlkbVh4VVhVMEJERzRqY1JIS0FpSmhkbUNLSlNudkpGTVdLTlM4QnlqYzBhYzRwT1owTlVubDZLZm5mSzFfdHpEY0V2NHFWYTRKNFdfM3Bz?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "495bf3d1dce62dcb", "factor": "sugar", "impact": 0, "date": "2026-09-06", "srcDate": "06/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Philippines seen remaining Brazil’s largest pork export market through 2027 - Manila Bulletin", "desc": "Rule-based: Philippines seen remaining Brazil’s largest pork export market through 2027 Manila Bulletin Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Manila Bulletin", "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxOMWRKXzNCWl9PcG9QRGl4MHhGNDdEQjhISnRRR08xQV94Y2hrRThXcWliRGZmOWtVQTlqTXN4Z2l4WWNIbHRPNU80azkxal9ZbldQSWNuMW9WM1g1aFpObnVIejZwY296ZXd0Q1pQMm45cDk0R0FSQi1JWkhNWWZqTDFGTzdnWGZMUTVjQVR1TE5rUGlJdnJ3YXRfeXdGcXhQTGt2SGh3?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "2c13eeb2e227ce5d", "factor": "sugar", "impact": 0, "date": "2026-09-06", "srcDate": "06/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Grain, sugar and milk ARE GETTING MORE EXPENSIVE on the world market - Modern.az", "desc": "Rule-based: Grain, sugar and milk ARE GETTING MORE EXPENSIVE on the world market Modern.az Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Modern.az", "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxQVTBjVWR1a0RrcWRBZUhMSWN3alhzeWozZlBYZUp3RHR0RTBlU0lXWldvb3pXeHAteVJpbUszLVAxQXg5M0ZpMjItTnZKMHBCOG1VSG5Rb0F6S3lSZ05IamROVndHbFhFYUx0aEdfQ2RjSlpibGFiQXJ2eE14V2lfTWpYdGlUVFZBNlM5eXdPeHFNSldGWUVRVU5yTjhJN2VCNFdnTTZLc0QtN2xjZ3c?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "24c7fdd6aec400f0", "factor": "sugar", "impact": 1, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "High Sugar Prices in India Echo Global Surge as FAO Sugar Index Jumps 11.9% in August - RuralVoice", "desc": "Rule-based: High Sugar Prices in India Echo Global Surge as FAO Sugar Index Jumps 11.9% in August RuralVoice Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "RuralVoice", "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxPQjVyNTQ1X3M0YW9oTnhuS1RNLW5fQUdnUDlCT0ljVWh4c3dfRUx3cHhjMlcwN25seTE2cV82VVVPZ0dPbFE5X3l2QmlVMTZrTEp2QlFLekVkUUZsTF9iQTQya1ZUZzV3ZU14c1E3Ums2dWFYQjJ6NXAxd3lacDk0ZmRMc29VLXVITzdDSWllSG5kOTVlejNaNFlCZDNMTUFFSjFfdjhHQWpFWGZyN04wTWFmYi1DcmRVRVo5TzhvRUhJd3lpY0g2S2VkMGpwbEJtMVpV0gHYAUFVX3lxTE1IZkFqRGhyYl9yZ2M1VFVBUzdsZ0pXd1lnQ1lYWHplUkdIUzhDUFdraDZKVVh1ZDlndXRVR3FUclJ6U0lsY25mcmhCNTF4U2xmQ0puQXlxTlVmX1NJYmR0U2ZkczZyLWJ3ZXpERWtCNDdFVVVleHhOc1NLYWtKeUhXSjhzRFVvbFZ2RGlGZEtoSlNibXo3SGlraHcyNThiYlpkMWRWWEZ2LTJuS2ZmRVk3ZU8wMDh3VEJnN1liR2V6WTM0S191V0gyU0F4ZmdtdWJqcFd5VXNLSQ?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
    ["Đường", "Vùng mía; giá đường thế giới (#11) & nội; nhập lậu; CBPG đường Thái", "SBT, SLS, LSS, QNS", "Giá đường cao; phòng vệ TM hiệu quả; vùng nguyên liệu ổn"],
    ["Sữa", "Giá bột sữa nhập (WMP/SMP); sức mua; đàn bò; thị phần", "VNM, IDP, MCM, QNS (sữa đậu nành)", "Giá bột nhập rẻ; sức mua hồi phục; giữ/tăng thị phần"],
    ["Ngô & thức ăn chăn nuôi", "Giá ngô/khô đậu nhập; giá heo; dịch bệnh; tái đàn", "DBC, BAF, HAG", "Giá heo cao + nguyên liệu rẻ = biên tốt; tái đàn thuận lợi"],
    ["Sắn", "Giá sắn lát/tinh bột; cầu Trung Quốc; ethanol", "HAG (nông nghiệp) + DN tinh bột", "Cầu TQ tốt; giá tinh bột cao; xuất khẩu thuận lợi"],
    ["Chi phí & logistics", "Cước vận tải; năng lượng; phân bón; tỷ giá nhập nguyên liệu", "Toàn nhóm", "Cước & năng lượng giảm; tỷ giá ổn định"]
  ],
  tickers: [
    ["SBT", "Đường (lớn nhất); vùng mía; xuất khẩu; giá đường", "Giá đường cao; vùng nguyên liệu mở rộng; xuất khẩu tốt", "Giá đường giảm; đường nhập lậu; tồn kho; đòn bẩy cao"],
    ["SLS", "Đường; vùng mía Sơn La; biên cao; cổ tức tiền mặt", "Giá đường cao; năng suất mía tốt; cổ tức lớn", "Giá đường giảm; thời tiết bất lợi; diện tích mía"],
    ["LSS", "Đường + sau đường (điện, cồn); đa dạng hóa", "Giá đường tốt; mảng sau đường đóng góp", "Giá đường yếu; cạnh tranh; chi phí"],
    ["QNS", "Sữa đậu nành Vinasoy + đường; giá đậu nành; thị phần", "Vinasoy giữ thị phần; đường có lãi; giá đậu nành rẻ", "Cạnh tranh sữa đậu; giá đường giảm; sức mua"],
    ["VNM", "Sữa (đầu ngành); giá bột nhập; thị phần; xuất khẩu", "Giá WMP/SMP rẻ; giữ/tăng thị phần; xuất khẩu Trung Đông", "Sức mua yếu; mất thị phần; giá bột nhập tăng"],
    ["IDP", "Sữa (nhãn Kun); tăng trưởng; biên; marketing", "Tăng trưởng nhãn Kun; biên cao; phân phối mở rộng", "Cạnh tranh gay gắt; chi phí marketing; sức mua"],
    ["MCM", "Sữa (Mộc Châu); đàn bò; vùng nguyên liệu; hợp lực VNM", "Sản lượng sữa tươi tăng; hợp lực Vinamilk; thương hiệu", "Giá nguyên liệu; cạnh tranh; sức mua yếu"],
    ["DBC", "3F (feed–farm–food); giá heo; giá ngô/khô đậu; tái đàn", "Giá heo cao + nguyên liệu rẻ; tái đàn; vắc-xin ASF", "Giá heo thấp; dịch ASF; giá ngô cao; đòn bẩy"],
    ["BAF", "Chăn nuôi heo; giá heo; mở rộng đàn; chuỗi khép kín", "Giá heo cao; mở trại mới; chuỗi khép kín hiệu quả", "Giá heo thấp; dịch bệnh; đòn bẩy; pha loãng"],
    ["HAG", "Chuối + heo (+ sầu riêng); giá heo/chuối; cơ cấu nợ", "Giá heo/chuối tốt; giảm nợ; dòng tiền cải thiện", "Giá nông sản yếu; đòn bẩy cao; pha loãng"]
  ],
  sources: [
    ["Giá đường – Trading Economics", "https://tradingeconomics.com/commodity/sugar", "Giá đường thế giới (#11), tham chiếu giá nội địa"],
    ["Giá ngô – Trading Economics", "https://tradingeconomics.com/commodity/corn", "Giá ngô thế giới (đầu vào thức ăn chăn nuôi)"],
    ["Global Dairy Trade", "https://www.globaldairytrade.info/", "Giá đấu giá sữa bột WMP/SMP toàn cầu"],
    ["Tổng cục Hải quan", "https://www.customs.gov.vn/", "Xuất khẩu sắn/tinh bột sắn, nhập khẩu ngô/đậu/sữa"],
    ["AgroMonitor", "https://agromonitor.vn/", "Dữ liệu & giá nông sản (đường, TĂCN, sắn) trong nước"],
    ["Bộ Nông nghiệp & Môi trường", "https://www.mard.gov.vn/", "Chính sách nông nghiệp, dịch bệnh chăn nuôi"],
    ["Chăn nuôi Việt Nam", "https://channuoivietnam.com/", "Giá heo hơi 3 miền, giá nguyên liệu TĂCN"],
    ["Vinamilk IR", "https://www.vinamilk.com.vn/", "IR: KQKD, thị phần, sản lượng sữa"]
  ]
};
