// ====== DỮ LIỆU NGÀNH THỦY SẢN — task "quet-nganh-thuy-san" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.thuysan = {
  id: "thuysan",
  name: "Thủy sản",
  icon: "🐟",
  order: 3,
  scope: "VHC, ANV, FMC, MPC, IDI, CMX",
  subtitle: "Sentiment ngành thủy sản VN theo chuỗi giá trị — xuất khẩu & thị trường, thuế & phòng vệ thương mại, nguyên liệu/nuôi trồng, chi phí đầu vào, tỷ giá, rào cản (IUU), tài chính, dòng tiền. Phạm vi: VHC, ANV, FMC, MPC, IDI, CMX (+ ASM, ABT). Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-08-17T08:40:58+07:00",
  factors: {
  export:"Xuất khẩu & thị trường", tariff:"Thuế & phòng vệ TM", material:"Nguyên liệu & nuôi trồng",
  feed:"Chi phí đầu vào", fx:"Tỷ giá", policy:"Pháp lý & rào cản (IUU)", finance:"Tài chính DN", market:"Thị trường & dòng tiền"
},
  sentiment: {
    score: 0, date: "2026-08-17",
    reason: "Tự động tổng hợp từ 7 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Thương mại thủy sản toàn cầu đạt 186 tỷ USD, tăng trưởng dự báo chậm lại - VASEP (VASEP, 15/08/2026). Tiêu cực: Mỹ đã hoàn trả khoảng 100 tỷ USD thuế quan sau phán quyết của Tòa án Tối cao - VASEP (VASEP, 15/08/2026). Có 5 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:2, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC"], title:"Vĩnh Hoàn tháng 5: doanh thu thuần 1.737 tỷ (+44%), Mỹ +46%, sản phẩm phụ (C&G) +102%", desc:"Ý nghĩa đầu tư: Thị trường Mỹ (633 tỷ, +46%) và EU (+81%), TQ (+50%) đồng loạt phục hồi; mảng sản phẩm phụ collagen/gelatin bật +102% lên 336 tỷ — củng cố biên lợi nhuận và vị thế dẫn đầu cá tra của VHC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"export", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Ngành bước vào cao điểm đơn hàng tháng 7-8; cá tra 5T XK +12,6% (905 triệu USD), TQ/HK tăng mạnh", desc:"Ý nghĩa đầu tư: Cầu Mỹ-TQ phục hồi, tồn kho thấp và nguồn cung cá thịt trắng tự nhiên thắt chặt giúp DN giữ/đẩy giá bán; cao điểm cuối năm hỗ trợ doanh số — tích cực cho cả cá tra (VHC/ANV/IDI) lẫn tôm (FMC/MPC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"tariff", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","MPC","CMX"], title:"Sao Ta kẹt thuế Mỹ: mỗi container phải đóng cọc 25%, tạm chỉ bán hàng không chịu thuế", desc:"Ý nghĩa đầu tư: Tiền cọc 25%/container gây kẹt vốn tại thị trường Mỹ; FMC dồn sang Nhật (30%)/EU (25%) và tập trung sản phẩm biên cao — rủi ro thuế tôm tiếp tục đè biên nhóm FMC/MPC/CMX.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"finance", impact:1, date:"2026-06-29", srcDate:"29/06/2026", isNew:true, aff:["MPC"], title:"Minh Phú khánh thành nhà máy chế biến Minh Phú Khánh An (Cà Mau), tự động hoá cao", desc:"Ý nghĩa đầu tư: 5T/2026 MPC XK >19.726 tấn tôm, doanh số >211,7 triệu USD, LN ~489,3 tỷ; nhà máy mới ứng dụng robot/tự động hoá giúp tối ưu chi phí, đẩy hàng GTGT — nâng năng lực cạnh tranh MPC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/minh-phu-mpc-khanh-thanh-nha-may-che-bien-thuy-san-minh-phu-khanh-an-tai-ca-mau-post393104.html"},
    {factor:"finance", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["ANV","FMC"], title:"Dự báo LNST 2026: ANV ~1.100 tỷ (+10%), FMC ~400 tỷ (+15%) — Chứng khoán NH Việt Nam", desc:"Ý nghĩa đầu tư: Giá cá tra & cá rô phi neo cao cùng cầu các thị trường trọng điểm tích cực hỗ trợ ANV; FMC kỳ vọng phục hồi lợi nhuận nhờ đa dạng thị trường dù vướng thuế Mỹ.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"material", impact:0, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Giá cá tra nguyên liệu neo >30.000đ/kg; chi phí nhiên liệu cao do căng thẳng Mỹ-Iran", desc:"Ý nghĩa đầu tư: Nguyên liệu cao phản ánh đơn hàng dồi dào nhưng cũng bào mòn biên nếu không chuyển được sang giá bán; chi phí nhiên liệu (Mỹ-Iran) đẩy chi phí khai thác/nuôi/vận chuyển — theo dõi biên gộp Q2.", srcName:"Tin nhanh chứng khoán (ĐTCK)/VASEP", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"market", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","ANV","MPC","IDI"], title:"Tuần qua cổ phiếu thủy sản điều chỉnh nhẹ: FMC -0,98%, ANV -0,91%, MPC -0,63%, IDI -3,61%", desc:"Ý nghĩa đầu tư: Nhóm phân hoá và chốt lời ngắn hạn trước mùa cao điểm dù triển vọng tích cực; dòng tiền chọn lọc mã có hiệu suất vận hành tốt (ưu tiên VHC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "feed", "impact": 0, "date": "2026-08-14", "srcDate": "14/08/2026 (truy xuất)", "isNew": false, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Khô đậu tương CBOT: 316.4 USD/tấn ngắn (+2.1% phiên 14/08)", "desc": "Ý nghĩa đầu tư: Khô đậu đi ngang, chi phí thức ăn ít thay đổi.", "srcName": "Yahoo Finance (ZM=F)", "url": "https://finance.yahoo.com/quote/ZM=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-08-14", "srcDate": "14/08/2026 (truy xuất)", "isNew": false, "aff": ["VHC", "ANV", "FMC", "MPC", "IDI", "CMX"], "title": "Tỷ giá USD/VND: 26068.0 đồng (+0.1% phiên 14/08)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": -1, "date": "2026-08-14", "srcDate": "14/08/2026 (truy xuất)", "isNew": true, "aff": ["ANV", "IDI", "MPC", "VHC", "CMX", "FMC"], "title": "Nhóm thủy sản phiên 14/08: 1 mã tăng / 4 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — ANV -2.6%; IDI -0.8%; MPC -0.7%; VHC +0.6%; CMX -0.4%; FMC +0.0%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "d671473c18da2c3f", "factor": "export", "impact": 0, "date": "2026-08-17", "srcDate": "17/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Vietnam seafood exports soar, but major challenges persist - Báo VietNamNet", "desc": "Rule-based: Vietnam seafood exports soar, but major challenges persist Báo VietNamNet Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Báo VietNamNet", "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNUW93aG1OeXJ0MFFpdmJRSkFULWxqT2xYU2xPWGNjUWY5bjBuRy1Xc3FPNzk1czlPRmxDQkR0bWtidTQza1hXSEtSYnFfcDBHTVl5S2oyZEgwazgzMDkzNnJiMnJXN2dZd1U1ZGNtVUNWTnB6VWRCeXUwYTdIa2QtRk43cGVqNWVoYUR0RHozaVJtTU9QWXBENWUtRQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "d4304fb8ccbbbf46", "factor": "export", "impact": 1, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Thương mại thủy sản toàn cầu đạt 186 tỷ USD, tăng trưởng dự báo chậm lại - VASEP", "desc": "Rule-based: Thương mại thủy sản toàn cầu đạt 186 tỷ USD, tăng trưởng dự báo chậm lại VASEP Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPM3BaazVrSTdKYnhsSmxWaEs1MlNLRjM3OWpsYWZOWXBMS3JKcWtQRm9BbkN3RlBTaWtOWDNzLVZHQ1RKajYxcnJhd0J6MDV5Rmg5LTB3TlgtbGlrRmVZVWEtUDJaUi12SkZTN29KNk1wZlBMVzBZTVNwRDZGLVFQQl9rLTlSYjhvSlBrZ2FoeHBsNVVuVzZvcWJmSm4xdC1FdkVPX1I1Y3RaVmvSAasBQVVfeXFMTzNwWms1a0k3SmJ4bEpsVmhLNTJTS0YzNzlqbGFmTllwTEtySnFrUEZvQW5Dd0ZQU2lrTlgzcy1WR0NUSmo2MXJyYXdCejA1eUZoOS0wd05YLWxpa0ZlWVVhLVAyWlItdkpGUzdvSjZNcGZQTFcwWU1TcEQ2Ri1RUEJfay05UmI4b0pQa2dhaHhwbDVVblc2b3FiZkpuMXQtRXZFT19SNWN0WlZr?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "fba727b75401d129", "factor": "export", "impact": -1, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Mỹ đã hoàn trả khoảng 100 tỷ USD thuế quan sau phán quyết của Tòa án Tối cao - VASEP", "desc": "Rule-based: Mỹ đã hoàn trả khoảng 100 tỷ USD thuế quan sau phán quyết của Tòa án Tối cao VASEP Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPRllUeUNkMkNwWHV2RF9CdWtlLS1WMlpuSzliQ0tTWWs2dDNfRy01Rk50RXE1TjZ4SHU2eUg4cm9xaTVhdTlWMDd1V1VFTUJrMjE5cm9lS3ZFdGNPdnAwZWFYRzI4Z3k5X3ZaZndnbS1tUXB1NGNCUWtVU2V3NlRLbHpFX0l5U3hSd2F3Q3dfVVMzWDNLY2ZFMnJHaElrQkhaMW9HNkJvVDNONTdDcm9vMGJB0gGyAUFVX3lxTE9GWVR5Q2QyQ3BYdXZEX0J1a2UtLVYyWm5LOWJDS1NZazZ0M19HLTVGTnRFcTVONnhIdTZ5SDhyb3FpNWF1OVYwN3VXVUVNQmsyMTlyb2VLdkV0Y092cDBlYVhHMjhneTlfdlpmd2dtLW1RcHU0Y0JRa1VTZXc2VEtsekVfSXlTeFJ3YXdDd19VUzNYM0tjZkUyckdoSWtCSFoxb0c2Qm9UM041N0Nyb28wYkE?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "6e88d01d75bc0968", "factor": "market", "impact": 0, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Việt Úc: Sẵn sàng cho AquaTech, 2030 trở thành Tập đoàn Công nghệ Thủy sản - VASEP", "desc": "Rule-based: Việt Úc: Sẵn sàng cho AquaTech, 2030 trở thành Tập đoàn Công nghệ Thủy sản VASEP Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxPV1dmNnFYTWRINjIwNmV3RmJQbGoyUUo5MjF6eU9vOXpsNHk0SFo4Q3RzSktmTDNlOHBIZlMzNWJZWFVxMFd3R3VlXzhrbUhxRVJiQWZqbkZhbnZJREZzOHdkTkhwNkN0bk44SExWTVB0cXNBUWQwTFNiUjZrTnBSSm5XeEx5RlhQUDV0blFvTU9YUGNzcUJ3dHhwb3Qta0czQzVrTk9pSE1RcG9h0gGsAUFVX3lxTE9XV2Y2cVhNZEg2MjA2ZXdGYlBsajJRSjkyMXp5T285emw0eTRIWjhDdHNKS2ZMM2U4cEhmUzM1YllYVXEwV3dHdWVfOGttSHFFUmJBZmpuRmFudklERnM4d2ROSHA2Q3RuTjhITFZNUHRxc0FRZDBMU2JSNmtOcFJKbld4THlGWFBQNXRuUW9NT1hQY3NxQnd0eHBvdC1rRzNDNWtOT2lITVFwb2E?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "6387ca9f092a3135", "factor": "market", "impact": 0, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "VASEP kiến nghị gỡ khó trong thủ tục cấp Chứng nhận xuất xứ hàng hóa - Báo Nông nghiệp và Môi trường", "desc": "Rule-based: VASEP kiến nghị gỡ khó trong thủ tục cấp Chứng nhận xuất xứ hàng hóa Báo Nông nghiệp và Môi trường Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Báo Nông nghiệp và Môi trường", "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPc1Bmb0hJUXFHMjIzUzVhb2xRcVJTaE9CcGs3SXU2aG5ZTDVVNE12bmpHNWVZVlpxVEt5bUgxaXdGMEg0LUhFZjlGVDA3XzEyY0dydGxFM2RaNmJzRkhZWHRxRHl3XzQ2RVNfUnczX0FmOHpjSkFtRUFuZW0wdDVpUnBUaWJrY1lsSU5uQlY5aUdqRDVGOUZzWUhpbHZDWEpTaHp0ak5lTkZVYzY5NlJoVlln?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "d63f91030294d067", "factor": "market", "impact": 0, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Trade insights: Low prices don’t deter Ecuador from shipping more shrimp in June - Undercurrent News", "desc": "Rule-based: Trade insights: Low prices don’t deter Ecuador from shipping more shrimp in June Undercurrent News Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Undercurrent News", "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxONFo3U0Vzc2h0OVMtUjZvMEpmTmpxNTZjZHhsNG9ZVlZQNUx1Rm11Unp6Qnh4VlJBLXdVZTktRUtRbDVQejlDakl1NVU1OENSeG05SXJkeTUzdEVQeEo2cGx5d0Z2cHk1QXNZTnhPbmltcXFUT1pxSHNtYjJSUlR6X1dVZGljbXNPTC15MF9pdnUyenJZQUw3QzFUc3BqT2U2a3RoUm15VFJEY3RLRlFTTjE4N3ZmQWlMdnN3Vmx6NnQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "5c4cfdfc336faece", "factor": "export", "impact": 0, "date": "2026-08-15", "srcDate": "15/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Chlorella Meal Ingredients Market To Hit USD 2.2B by 2035 on Aquaculture Protein Demand - News and Statistics - IndexBox", "desc": "Rule-based: Chlorella Meal Ingredients Market To Hit USD 2.2B by 2035 on Aquaculture Protein Demand Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "IndexBox", "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxQX09rU05Xb1VzaHlPT3E0SHZOcDBubG5iT05EUks2ZUhIWWRVME5SVC1NUmxPTFo3aUJIWU9aWjc2bWU3djhjVFkxUDYxY0lFMXpibjVGZmV5dmNRRnFsZ0NwYnhsVHdLS2ZMdHFrbER4SWFtWGRPMV92dnExQ3FNVzFFajJOUmhZMzRZVldsalpES25mNUtmSUxDbW1zTk5WVWRsQ2VZd0dtNFVSR3Y3cEw1aFhabjlBR0dZ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "d1841be6c8bd534a", "factor": "export", "impact": -1, "date": "2026-08-14", "srcDate": "14/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Mỹ: Ngành thủy sản chịu tác động nặng nề từ thuế quan - VASEP", "desc": "Rule-based: Mỹ: Ngành thủy sản chịu tác động nặng nề từ thuế quan VASEP Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxPVTkydmdfdlFFeERfX3pQZi1nSU9jWm5SMmFuTjRyN1NyYnF1ZEQzN09MeVpzaXlmN2FqRlpiVkRXOF85QnJVbHp0WnhSTklfNWw4U1dlT0RHYmJna29jVU5kTXg1a3NNZTZPN1BkRkhwS25OQUs1X1pkcDdSREZ3NTVENlZ0WExNTGloOVZqdVBfZ9IBkgFBVV95cUxPVTkydmdfdlFFeERfX3pQZi1nSU9jWm5SMmFuTjRyN1NyYnF1ZEQzN09MeVpzaXlmN2FqRlpiVkRXOF85QnJVbHp0WnhSTklfNWw4U1dlT0RHYmJna29jVU5kTXg1a3NNZTZPN1BkRkhwS25OQUs1X1pkcDdSREZ3NTVENlZ0WExNTGloOVZqdVBfZw?oc=5", "src": "news", "sourceScope": "local"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
  ["Thức ăn thủy sản","Giá đậu nành/bột cá; tự chủ thức ăn","(đầu vào) ASM, các DN tự chủ","Giá nguyên liệu thức ăn giảm; tự chủ cao"],
  ["Con giống & nuôi trồng","Vùng nuôi tự chủ; giá cá tra/tôm nguyên liệu; dịch bệnh","VHC, ANV, FMC, MPC","Giá nguyên liệu hợp lý; vùng nuôi tự chủ; ít dịch bệnh"],
  ["Chế biến","Công suất; tỷ trọng hàng GTGT; sản phẩm phụ (collagen)","VHC, FMC, MPC, IDI, CMX","Công suất chạy cao; tăng hàng GTGT & C&G"],
  ["Xuất khẩu","Đơn hàng; thị trường Mỹ/TQ/EU/Nhật; giá bán","VHC, ANV, FMC, MPC","Đơn hàng tốt; giá XK tăng; đa dạng thị trường"],
  ["Thị trường tiêu thụ","Thuế CBPG/đối ứng; rào cản IUU/MMPA; cạnh tranh Ecuador/Ấn Độ","VHC, FMC, MPC","Thuế thấp/miễn trừ; rào cản nới; cạnh tranh giảm"]
],
  tickers: [
  ["VHC","Cá tra; thị trường Mỹ/TQ; mảng C&G (collagen); giá cá tra","Giá cá tra & giá XK tăng; thuế Mỹ thấp; C&G tăng","Thuế CBPG Mỹ cao; giá cá tra giảm; cầu Mỹ yếu"],
  ["ANV","Cá tra; mở rộng Trung Quốc; tự chủ vùng nuôi & thức ăn","Thị phần TQ tăng; biên cải thiện; tự chủ chuỗi","Phụ thuộc TQ; giá cá tra giảm; chi phí tăng"],
  ["IDI","Cá tra; thị trường TQ/ASEAN; tồn kho cá","Giá cá tra phục hồi; tồn kho lãi","Giá cá tra yếu; tồn kho lỗ; biên mỏng"],
  ["FMC","Tôm; thị trường Nhật/Mỹ; vùng nuôi; hàng GTGT","Đơn tôm tốt; Nhật ổn định; vùng nuôi mở rộng","Thuế CBPG tôm Mỹ; cạnh tranh Ecuador/Ấn Độ; giá tôm giảm"],
  ["MPC","Tôm (lớn nhất); chuỗi khép kín; thị trường Mỹ","Giá tôm tăng; thị phần Mỹ giữ; chuỗi hiệu quả","Thuế tôm Mỹ 25,76%; giá tôm thấp; dịch bệnh"],
  ["CMX","Tôm; thị trường EU; tôm sinh thái","Cầu EU tốt; giá tôm tăng; chứng nhận sinh thái","Rào cản EU; giá tôm giảm; chi phí cao"]
],
  sources: [
    ["VASEP","https://vasep.com.vn/","Số liệu & dự báo xuất khẩu tôm, cá tra, cá ngừ; thuế Mỹ"],
    ["Tổng cục Hải quan","https://www.customs.gov.vn/","Kim ngạch xuất nhập khẩu theo tháng"],
    ["Thị trường cá tra","https://www.thitruongcatra.com/","Giá cá tra nguyên liệu, thị trường"],
    ["Vĩnh Hoàn (VHC)","https://www.vinhhoan.com/","IR: KQKD, sản lượng, mảng C&G"],
    ["Sao Ta (FMC)","https://fimexvn.com/","IR: doanh số tôm theo tháng, thị trường"],
    ["Nam Việt (ANV)","https://navicorp.com.vn/","IR: cá tra, thị trường Trung Quốc"],
    ["Minh Phú (MPC)","https://minhphu.com/","IR: tôm, thuế CBPG Mỹ"]
  ]
};
