// ====== DỮ LIỆU NGÀNH DẦU KHÍ — task "quet-nganh-dau-khi" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.oil = {
  id: "oil",
  name: "Dầu khí",
  icon: "🛢️",
  order: 1,
  scope: "PVD, PVS, GAS, PVT, BSR, PLX, OIL, POW, DPM, DCM",
  subtitle: "Sentiment ngành dầu khí VN theo chuỗi giá trị — giá dầu, khí/LNG, pháp lý, dự án, biên lọc dầu, vận tải, tài chính, dòng tiền. Phạm vi: PVD, PVS, GAS, PVT, BSR, PLX, OIL, POW, DPM, DCM. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-07-23T07:05:22+07:00",
  factors: {
  oil:"Giá dầu & OPEC+", gas:"Khí & LNG", legal:"Pháp lý & chính sách", project:"Dự án",
  refining:"Biên lọc dầu", shipping:"Vận tải biển", fuel:"Giá xăng dầu", finance:"Tài chính DN", market:"Thị trường & dòng tiền"
},
  sentiment: {
    score: 1, date: "2026-07-23",
    reason: "Tự động tổng hợp từ 12 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Oil Prices Rise 3% as Iran War Stand-off Persists - Energy News, Top Headlines, Commentaries, Features &… (EnergyNow.com, 23/07/2026); Goldman Sachs Warns: If Hormuz Strait Disruption Persists, Brent Crude Could Surge Past $120 in Q4 - fin… (finance.biggo.com, 22/07/2026). Tiêu cực: Brent crude: 84.76 USD/thùng (-6.9% phiên 22/07) (Yahoo Finance (BZ=F), 22/07/2026 (truy xuất)); Hormuz on a Knife-Edge: Shipping Pays the Price as the Iran-U.S. Ceasefire Unravels - gCaptain (gCaptain, 22/07/2026). Có 5 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
  {factor:"oil", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"Phiên 30/6: dầu thô tăng phiên thứ 2 liên tiếp — Brent ~73,4 USD (+~1,9%), WTI ~71 USD (+~2,6%); ngừng bắn Mỹ–Iran mong manh, nhu cầu mùa hè",
   desc:"Ý nghĩa đầu tư: sáng 30/6 dầu tăng phiên thứ 2 liên tiếp — Brent ~73,36 USD (+1,37 USD, +1,9%), WTI ~71,06 USD (+1,83 USD, +2,64%) theo bản tin trong nước; một số nguồn khác ghi Brent ~72,8 USD (+1,1%), WTI ~70,2 USD (+1,4%) tùy thời điểm chốt. Nguyên nhân: các vụ va chạm/trả đũa Mỹ–Iran cuối tuần cho thấy thỏa thuận ngừng bắn 60 ngày còn mong manh, risk premium địa chính trị duy trì; thêm kỳ vọng nhu cầu nhiên liệu mùa hè cao điểm cải thiện. Đà tăng bị kìm bởi xuất khẩu Vùng Vịnh qua eo Hormuz hồi nhanh về ≥75% mức trước xung đột (Gelber & Associates) và thời tiết Mỹ dịu làm khí tự nhiên giảm về ~3,18 USD/MMBtu. Mức tăng <3% (chưa chạm ALERT). Hồi giá hỗ trợ tâm lý thượng nguồn (PVD/PVS) và crack spread (BSR) ngắn hạn; PVD/PVS vẫn bám backlog Lô B ít phụ thuộc spot; feedstock/khí rẻ lợi cho POW/DPM/DCM. Theo dõi kỳ điều hành giá xăng thứ Năm 2/7.",
   srcName:"Thể Thao 247 / VTC News / Dân Việt / Reuters", url:"https://vtcnews.vn/gia-xang-dau-hom-nay-30-6-tiep-tuc-tang-nhe-ar1026349.html"},
  {factor:"finance", impact:1, date:"2026-06-29", srcDate:"29/06/2026", isNew:true, aff:["BSR","PVD","PVS","PVT","GAS","PLX"],
   title:"MBS dự phóng KQKD Q2/2026 nhóm dầu khí: BSR +>380%, PVD +41%, PVS +18,5%, PVT +19% — thượng nguồn là điểm sáng; GAS/PLX giảm",
   desc:"Ý nghĩa đầu tư: báo cáo MBS (29/6) dự phóng KQKD Q2/2026 nhóm dầu khí sáng nhờ giá dầu bình quân quý vẫn cao (~97 USD/thùng) và các dự án trọng điểm tăng tốc. BSR dẫn đầu với LN dự báo +>380% (nền thấp cùng kỳ + crack spread tốt); PVD ~339 tỷ LNST (+41,3%) nhờ giàn PVD IX vận hành từ tháng 4 nâng số giàn JU lên cao nhất từ trước tới nay; PVS ~428 tỷ (+18,5%) nhờ EPCI Lô B–Ô Môn triển khai nhanh hơn dự kiến, củng cố backlog; PVT ~349 tỷ (+19%) nhờ hiệu suất khai thác cao, tàu mới và cước thuận lợi. Ngược lại GAS và PLX bị dự báo lợi nhuận giảm. Củng cố luận điểm ưu tiên thượng nguồn (PVD/PVS/PVT) và BSR hạ nguồn; thận trọng với GAS/PLX. Theo dõi KQKD Q2 chính thức công bố cuối tháng 7.",
   srcName:"MBS / CafeF / Nhịp Sống Kinh Doanh", url:"https://cafef.vn/mbs-du-bao-loi-nhuan-mot-dai-gia-dau-khi-co-the-tang-truong-hon-380-trong-quy-2-188260629230333342.chn"},
  {factor:"oil", impact:1, date:"2026-06-29", srcDate:"29/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"Phiên đầu tuần 29/6: Brent +0,54% lên ~73 USD, WTI +0,77% lên ~69,8 USD — Iran tập kích căn cứ Mỹ ở Bahrain/Kuwait, lung lay ngừng bắn 60 ngày",
   desc:"Ý nghĩa đầu tư: 6h–7h ngày 29/6 Brent ~72,99 USD (+0,39 USD, +0,54%), WTI ~69,76 USD (+0,53 USD, +0,77%) — hồi nhẹ từ đáy ~4 tháng. Nguyên nhân: Chủ nhật 28/6 Iran phóng drone/tên lửa vào căn cứ Mỹ ở Bahrain và Kuwait (đáp trả đợt không kích của Mỹ vào mục tiêu tên lửa/radar Iran cuối tuần) → thị trường lo ngại thỏa thuận ngừng bắn 60 ngày Mỹ–Iran lung lay, risk premium địa chính trị quay lại. Mức tăng chỉ ~0,5% (chưa chạm ALERT 3%) cho thấy thị trường chưa định giá gián đoạn nguồn cung lớn; nền cung vẫn dư (Hormuz thông, Mỹ miễn trừ Iran 60 ngày tới 21/8, OPEC+ tăng cung). Hai chiều: nhích nhẹ hỗ trợ tâm lý thượng nguồn (PVD/PVS) và crack spread (BSR) ngắn hạn, nhưng leo thang Trung Đông tạo biến động hai chiều cao. PVD/PVS vẫn bám backlog Lô B ít phụ thuộc spot; feedstock/khí rẻ lợi cho POW/DPM/DCM. Theo dõi diễn biến căng thẳng và kỳ điều hành giá xăng thứ Năm 2/7.",
   srcName:"Thanh Niên / VietnamBiz / Reuters", url:"https://thanhnien.vn/gia-xang-dau-hom-nay-2962026-tang-nhe-185260629075159757.htm"},
  {factor:"oil", impact:0, date:"2026-06-28", srcDate:"28/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"Cuối tuần 28/6: Brent neo đáy ~72 USD sau tuần -8%; J.P. Morgan & Goldman hạ dự báo Brent H2/2026 (Q3 ~86, Q4 ~80 USD)",
   desc:"Ý nghĩa đầu tư: T7–CN nghỉ giao dịch, giá vẫn ở mức chốt phiên 26/6 — Brent ~71,99 USD, WTI ~69,2 USD (đáy từ 27/2); cả tuần Brent/WTI mất ~8%, mức giảm tuần mạnh nhất một tháng, khi vận chuyển qua eo Hormuz tăng tốc và xuất khẩu Vùng Vịnh hồi về ~75% mức trước xung đột. Diễn biến mới: J.P. Morgan hạ dự báo Brent nửa cuối 2026 (Q3 ~86, Q4 ~80 USD) vì nhu cầu yếu và tồn kho OECD giảm chậm; Goldman cũng hạ mục tiêu Q4 về 80 USD (từ 90), kỳ vọng cung Vùng Vịnh về mức trước chiến cuối tháng 7. Hai chiều: gần hạn bearish cho crack spread (BSR) và tâm lý thượng nguồn, nhưng mục tiêu ~80 USD vẫn cao hơn spot ~72 → hàm ý hồi phục H2; PVD/PVS bám backlog Lô B ít chịu tác động spot, feedstock/khí rẻ hơn lợi cho POW/DPM/DCM. Chờ phiên đầu tuần và kỳ điều hành giá xăng tới.",
   srcName:"VTC News / Reuters / J.P. Morgan", url:"https://vtcnews.vn/gia-xang-dau-hom-nay-28-6-tiep-tuc-lao-doc-ar1026019.html"},
  {factor:"oil", impact:-1, date:"2026-06-27", srcDate:"27/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"ALERT: Brent giảm hơn 4% về ~72 USD/thùng (WTI dưới 70) — cả tuần -8% khi Aramco nối lại bốc xếp Ras Tanura, tồn kho Mỹ tăng, OPEC+ im lặng",
   desc:"Ý nghĩa đầu tư: 6h ngày 27/6 Brent ~71,99 USD (-3,27 USD, -4,34%), WTI ~69,23 USD (giảm gần 4%, dưới mốc 70 — đáy từ 27/2); cả tuần Brent/WTI mất ~8%. Risk premium Hormuz tan nhanh: Saudi Aramco nối lại bốc xếp tại cảng Ras Tanura (vùng Vịnh) ngày 26/6 sau gần 4 tháng gián đoạn — 2 tàu VLCC (~2 triệu thùng/tàu) đã cập cảng nạp dầu; tồn kho xăng Mỹ tăng 2,064 triệu thùng lên 216,3 triệu; OPEC+ im lặng, chưa phát tín hiệu cắt giảm → rủi ro dư cung lấn át nỗi lo thiếu hụt. ALERT (Brent ±>3%): bearish ngắn hạn cho crack spread (BSR) và tâm lý thượng nguồn; PVD/PVS chạy theo backlog Lô B nên ít chịu tác động spot; feedstock/khí rẻ hơn có lợi cho POW/DPM/DCM. Lưu ý biến động hai chiều cao quanh tin Trung Đông.",
   srcName:"VTC News / Thanh Niên / Reuters", url:"https://thanhnien.vn/gia-xang-dau-hom-nay-2762026-lao-doc-mat-8-trong-tuan-185260627075840868.htm"},
  {factor:"oil", impact:-1, date:"2026-06-27", srcDate:"27/06/2026 (truy xuất)", isNew:false, aff:["BSR","PLX","OIL"],
   title:"Saudi Aramco hạ OSP kỷ lục sang châu Á tháng 7 — tín hiệu cạnh tranh thị phần, dư cung lấn át",
   desc:"Ý nghĩa đầu tư: sau khi eo Hormuz thông trở lại, Aramco hạ giá bán chính thức (OSP) sang châu Á ở mức kỷ lục — Arab Light giao tháng 7 dự kiến chỉ +7,5–12,5 USD vs tham chiếu Dubai/Oman, giảm 3–8 USD so với OSP tháng 6; phần bù Dubai spot vs swap về ~8,9 USD (từ ~13,92 USD hồi tháng 4). Động thái xác nhận nguồn cung Vùng Vịnh hồi phục và cuộc chiến thị phần — củng cố xu hướng giá dầu hạ nhiệt, gây áp lực crack spread (BSR); ngược lại đầu vào rẻ hơn hỗ trợ biên POW/DPM/DCM trung hạn.",
   srcName:"Dân Trí / Vinanet / Reuters", url:"https://dantri.com.vn/kinh-doanh/saudi-aramco-giam-gia-dau-ky-luc-sang-chau-a-sau-tin-hormuz-20260627060124062.htm"},
  {factor:"market", impact:-1, date:"2026-06-26", srcDate:"26/06/2026", isNew:false, aff:["BSR","PVS","PVD","PVT","PLX","PVC"],
   title:"Phiên 26/6: cổ phiếu dầu khí giảm theo giá dầu (BSR -3,7%, PVC -4,5%, PVS -2,1%), thận trọng trở lại",
   desc:"Ý nghĩa đầu tư: nhóm năng lượng là ngành giảm mạnh nhất phiên 26/6 (-2,61%) dưới áp lực giá dầu — BSR -3,72%, PVC -4,48%, PVS -2,06%, PVT -1,25%, PLX -1,46%, PVD -1,1%, PVP -1,09%. Thanh khoản dưới trung bình 20 phiên, tâm lý thận trọng quay lại sau nhịp tăng nóng. Đợt chốt lời kỹ thuật theo giá dầu spot; vùng giá điều chỉnh có thể là cơ hội với nhà đầu tư bám luận điểm backlog thượng nguồn (Lô B), nhưng cần chờ giá dầu ổn định.",
   srcName:"Vietstock / Người Quan Sát", url:"https://vietstock.vn/2026/06/vietstock-daily-26062026-than-trong-tro-lai-1636-1458521.htm"},
  {factor:"project", impact:1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:false, aff:["PVS","PVD","GAS"],
   title:"PVS đẩy nhanh Lô B – Ô Môn: EPC#2 đạt ~95%, Lạc Đà Vàng kỳ vọng first oil Q4/2026 — ABS đánh giá cao GAS/PVS/PVD",
   desc:"Ý nghĩa đầu tư: PVS cho biết EPC#2 dự án Lô B–Ô Môn đã đạt ~95% khối lượng; dự án Lạc Đà Vàng kỳ vọng đón dòng dầu đầu tiên (first oil) Q4/2026, cùng các dự án điện gió Baltica 2 / Phong Điều tiến độ 95–97%. ABS đánh giá cao triển vọng GAS, PVS, PVD — nhóm hưởng lợi lớn và dẫn đầu thượng/trung nguồn từ đại dự án ~12 tỷ USD. Củng cố trục tăng trưởng dài hạn dựa trên backlog, là điểm tựa cơ bản khi giá dầu spot biến động.",
   srcName:"VnEconomy / Elibook / ABS", url:"https://vneconomy.vn/cu-hich-tu-du-an-lo-b-o-mon-lo-trinh-huong-loi-cua-co-phieu-dau-khi.htm"},
  {factor:"oil", impact:1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"Brent bật hơn 2% lên ~75,3 USD/thùng sau vụ tàu hàng bị tấn công gần Oman — risk premium Hormuz quay lại",
   desc:"Ý nghĩa đầu tư: chốt phiên 26/6 Brent +1,52 USD (+2,1%) lên ~75,26 USD, WTI +1,58 USD (+2,3%) lên ~71,92 USD — hồi từ đáy 4 tháng. Tàu hàng Ever Lovely (cờ Singapore) trúng vật thể lạ gần Oman khi qua eo Hormuz; hai quan chức Mỹ nói Iran đã nổ súng, IMO tạm dừng chiến dịch hỗ trợ tàu/thuyền viên qua eo, LHQ hoãn kế hoạch sơ tán → thỏa thuận hòa bình Mỹ–Iran lung lay, risk premium địa chính trị quay lại. Kho chứa Vùng Vịnh mới đầy ~50–60%; nếu lưu thông qua Hormuz chưa hồi phục, các nước có thể buộc cắt giảm cung. Mức +2,1% chưa chạm ngưỡng ALERT 3% nhưng đảo chiều tâm lý ngắn hạn theo hướng hỗ trợ thượng nguồn (PVD/PVS) và crack spread (BSR); lưu ý biến động hai chiều cao quanh tin Trung Đông.",
   srcName:"VTC News / VietnamBiz / Reuters", url:"https://vietnambiz.vn/gia-xang-dau-hom-nay-266-tang-hon-2-vi-dien-bien-moi-tai-trung-dong-20266266530139.htm"},
  {factor:"finance", impact:1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:false, aff:["PVS"],
   title:"PVS chốt cổ tức 2026 7% tiền + 20% cổ phiếu; VDSC dự phóng LNST ~2.330 tỷ (+28%), Vietcap kỳ vọng hoàn nhập ~635 tỷ",
   desc:"Ý nghĩa đầu tư: PVS được duyệt cổ tức 2026 tỷ lệ 7% tiền mặt + 20% cổ phiếu; VDSC dự phóng doanh thu cả năm ~39.454 tỷ (+21% YoY) và LNST ~2.330 tỷ (+28% YoY), trong khi Vietcap nhấn mạnh khả năng hoàn nhập dự phòng ~635 tỷ (~26% LNTT 2026). 6T/2026 mới đạt ~30% kế hoạch nên tăng trưởng dồn về nửa cuối năm khi khối lượng EPC Lô B/Lạc Đà Vàng tăng tốc — củng cố luận điểm backlog thượng nguồn, ít phụ thuộc giá dầu spot.",
   srcName:"Elibook / VDSC / Vietcap", url:"https://elibook.vn/2026/06/24/pvs-loi-nhuan-6-thang-dau-nam-dat-627-ty-dong-chi-moi-hoan-thanh-30-du-bao-loi-nhuan-ca-nam-nhung-dang-tang-toc-cho-lo-b-o-mon.html/"},
  {factor:"fuel", impact:0, date:"2026-06-25", srcDate:"25/06/2026", isNew:false, aff:["PLX","OIL","BSR"],
   title:"Kỳ điều hành 25/6: xăng E10 RON95 -837 đ về ~19.916 đ/lít — chính thức dưới 20.000 đ/lít, giảm 5 kỳ liên tiếp",
   desc:"Ý nghĩa đầu tư: từ 15h ngày 25/6, Liên Bộ Công Thương–Tài chính điều chỉnh giảm; E10 RON95 giảm 837 đ về tối đa ~19.916 đ/lít (xác nhận con số chính thức so với ước tính trước), E5 RON92 cũng về dưới 20.000 đ — lần giảm thứ 5 liên tiếp theo đà giá thế giới. Giá bán lẻ giảm theo giá cơ sở ít ảnh hưởng biên gốc PLX/OIL nhưng tăng nhẹ rủi ro lỗ tồn kho khi giá xuống nhanh; theo dõi chiết khấu và vòng quay tồn kho, nhất là khi giá dầu thế giới đảo chiều tăng lại.",
   srcName:"VietnamNet / Thanh Niên / Techz", url:"https://thanhnien.vn/gia-xang-dau-hom-nay-2662026-xang-e10-ve-duoi-muc-20000-dong-lit-185260626071509853.htm"},
  {factor:"oil", impact:-1, date:"2026-06-25", srcDate:"25/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"ALERT: Brent giảm hơn 4% về ~73,7 USD/thùng — đáy ~4 tháng do Hormuz thông, Mỹ miễn trừ Iran 60 ngày, OPEC+ tăng cung",
   desc:"Ý nghĩa đầu tư: sáng 25/6 Brent ~73,7 USD (có lúc 75,6 USD — thấp nhất từ 27/2), WTI ~69,9–72 USD (đáy từ 3/3), giảm hơn 4% trong phiên — đáy gần 4 tháng. Vận chuyển qua eo Hormuz phục hồi, Mỹ cấp giấy phép miễn trừ 60 ngày cho Iran xuất khẩu dầu (hiệu lực đến 21/8), UAE xuất ~85% mức trước xung đột và OPEC+ tăng cung (+188k bpd tháng 7) → áp lực giảm kéo dài, giá đã rơi ~40% từ đỉnh thời chiến. ALERT (Brent ±>3%): bearish ngắn hạn cho crack spread (BSR) và tâm lý thượng nguồn; PVD/PVS chạy theo backlog Lô B nên ít chịu tác động spot; feedstock/khí rẻ hơn lợi cho POW/DPM/DCM.",
   srcName:"VTC News / Trading Economics / Reuters", url:"https://vtcnews.vn/gia-xang-dau-hom-nay-25-6-tiep-da-giam-sau-ar1025467.html"},
  {factor:"fuel", impact:0, date:"2026-06-25", srcDate:"25/06/2026", isNew:false, aff:["PLX","OIL","BSR"],
   title:"Giá xăng dầu trong nước giảm lần thứ 5 liên tiếp kỳ điều hành 25/6 (E10 về ~20.000 đ/lít)",
   desc:"Ý nghĩa đầu tư: kỳ điều hành chiều 25/6 giảm 700–1.500 đ/lít, diesel giảm mạnh hơn xăng E10; xăng sinh học E10 về mốc ~20.000 đ/lít — lần giảm thứ 5 liên tiếp, vùng thấp khu vực, theo đà giá dầu thế giới về đáy 4 tháng. Giá bán lẻ giảm theo giá cơ sở ít ảnh hưởng biên gốc PLX/OIL nhưng tăng rủi ro lỗ tồn kho khi giá xuống nhanh; theo dõi chiết khấu, vòng quay tồn kho và đề xuất kéo dài giảm thuế xăng dầu.",
   srcName:"VTC News / Thanh Niên", url:"https://vtcnews.vn/gia-xang-dau-hom-nay-25-6-tiep-da-giam-sau-ar1025467.html"},
  {factor:"finance", impact:1, date:"2026-06-24", srcDate:"24/06/2026", isNew:false, aff:["PVS"],
   title:"PVS 6T/2026: doanh thu ~15.815 tỷ (+13%), LNST 627 tỷ (+2% YoY), mới đạt ~30% kế hoạch — tăng tốc Lô B nửa cuối năm",
   desc:"Ý nghĩa đầu tư: PVS 6 tháng đầu 2026 doanh thu hợp nhất ~15.815 tỷ (+13% YoY), LNST ~627 tỷ (+2% YoY) — mới hoàn thành ~30% dự báo lợi nhuận cả năm, phản ánh khối lượng EPC Lô B/Lạc Đà Vàng dồn về nửa cuối năm. Tiến độ giải ngân backlog (giá trị HĐ ~1,5 tỷ USD) là biến số then chốt cho tăng trưởng H2; theo dõi nghiệm thu khối lượng và khả năng hoàn nhập dự phòng.",
   srcName:"Elibook", url:"https://elibook.vn/2026/06/24/pvs-loi-nhuan-6-thang-dau-nam-dat-627-ty-dong-chi-moi-hoan-thanh-30-du-bao-loi-nhuan-ca-nam-nhung-dang-tang-toc-cho-lo-b-o-mon.html/"},
  {factor:"market", impact:1, date:"2026-06-24", srcDate:"24/06/2026", isNew:false, aff:["PVD","PVS","BSR","GAS"],
   title:"Phiên 24/6: cổ phiếu dầu khí tăng bất chấp giá dầu giảm (PVD +3,2%, PVS +2,7%)",
   desc:"Ý nghĩa đầu tư: nhóm dầu khí đóng góp +0,83 điểm vào VN-Index phiên 24/6 dù giá dầu thế giới rơi — PVD +3,23%, PVS +2,65%. Dòng tiền tiếp tục ưu tiên câu chuyện backlog thượng nguồn (Lô B) và vùng định giá chiết khấu sâu hơn là biến động giá dầu spot; lưu ý một số khuyến nghị bắt đầu nhắc tới vùng chốt lời ngắn hạn sau nhịp tăng nóng.",
   srcName:"Báo Mới / DNSE", url:"https://www.dnse.com.vn/senses/tin-tuc/giai-ma-suc-nong-cua-nhom-co-phieu-dau-khi-35156697"},
  {factor:"oil", impact:-1, date:"2026-06-24", srcDate:"24/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL","GAS"],
   title:"Brent về ~77,1 USD/thùng — đáy ~3 tháng do Iran xuất khẩu trở lại, Hormuz thông, OPEC+ tăng cung",
   desc:"Ý nghĩa đầu tư: sáng 24/6 Brent ~77,08 USD (-0,82 USD vs phiên trước), WTI ~74 USD — vùng thấp nhất gần 3 tháng. Mỹ–Iran ký khung hòa bình tạm thời, Mỹ cấp giấy phép cho Iran bán dầu/nhiên liệu 60 ngày (Iran đã xuất >30 triệu thùng/tuần), giao thông qua eo Hormuz phục hồi và OPEC+ tiếp tục tăng sản lượng → áp lực giảm giá kéo dài. Giá dầu thấp làm dịu sentiment thượng nguồn ngắn hạn nhưng PVD/PVS chạy theo backlog Lô B; BSR chịu áp lực crack spread thu hẹp; feedstock/khí rẻ hơn lợi cho POW/DPM/DCM.",
   srcName:"Trading Economics / VTC News / Reuters", url:"https://tradingeconomics.com/commodity/brent-crude-oil"},
  {factor:"project", impact:1, date:"2026-06-24", srcDate:"24/06/2026 (truy xuất)", isNew:false, aff:["PVS","PVD","GAS","PVB"],
   title:"PVS đẩy nhanh Lô B – Ô Môn: hạ thủy chân đế, FSO Lạc Đà Vàng vận hành, ký EPC Sư Tử Trắng 2B",
   desc:"Ý nghĩa đầu tư: tại gặp gỡ NĐT T6/2026, PVS cho biết đang hạ thủy chân đế giàn dự án khí Lô B, đưa FSO Lạc Đà Vàng vào vận hành, ký hợp đồng thi công Sư Tử Trắng 2B và triển khai trạm biến áp ngoài khơi Formosa 4; dự án khí–điện Lô B đúng tiến độ, kỳ vọng đón dòng khí đầu tiên (first gas) trong 2026. Backlog tỷ USD củng cố tăng trưởng PVS/PVD (PVS 5T/2026 DT 13.515 tỷ +34%, LNST 563 tỷ +11%), ít phụ thuộc giá dầu spot.",
   srcName:"MarketTimes / 24hMoney", url:"https://markettimes.vn/pvs-tang-toc-voi-loat-du-an-ty-usd-co-phieu-duoc-du-bao-but-pha-32-121939.html"},
  {factor:"oil", impact:-1, date:"2026-06-23", srcDate:"23/06/2026 (truy xuất)", isNew:false, aff:["BSR","PVD","PVS","PLX","OIL"],
   title:"ALERT: Brent giảm hơn 3% về ~78 USD/thùng do tiến triển đàm phán Mỹ–Iran",
   desc:"Ý nghĩa đầu tư: Brent rớt ~3,3% phiên 22/6 về ~77,9 USD, sáng 23/6 hồi nhẹ +0,38% lên ~78,15 USD — vùng thấp nhất từ đầu tháng 3. Mỹ cấp phép Iran xuất khẩu dầu 60 ngày (hiệu lực đến 21/8), Kuwait gỡ force majeure, ADNOC nối lại cung → kỳ vọng nguồn cung Vùng Vịnh phục hồi, giảm rủi ro eo Hormuz. Giá hạ nhiệt làm dịu sentiment thượng nguồn ngắn hạn nhưng PVD/PVS chạy theo backlog; BSR chịu áp lực crack spread thu hẹp; đầu vào khí/feedstock rẻ hơn lợi cho POW/DPM/DCM.",
   srcName:"Trading Economics / Reuters / CNBC", url:"https://tradingeconomics.com/commodity/brent-crude-oil"},
  {factor:"refining", impact:-1, date:"2026-06-23", srcDate:"23/06/2026 (truy xuất)", isNew:false, aff:["BSR"],
   title:"Crack spread dự báo thu hẹp về ~17 USD/thùng khi căng thẳng Trung Đông hạ nhiệt",
   desc:"Ý nghĩa đầu tư: Maybank dự báo crack spread giảm từ ~40 USD/thùng (T3) về ~17 USD/thùng (T6) khi rủi ro địa chính trị giảm — dù vẫn cao so với lịch sử. Biên lọc dầu thu hẹp gây áp lực lên LN BSR nửa cuối 2026 sau quý đầu lập đỉnh (LN ròng Q1 ~8.265 tỷ); theo dõi tồn kho và kỳ bảo dưỡng Dung Quất.",
   srcName:"Maybank / CafeF", url:"https://cafef.vn/maybank-loi-nhuan-bsr-co-the-lap-dinh-lich-su-trong-nam-2026-188260318225627811.chn"},
  {factor:"finance", impact:1, date:"2026-06-23", srcDate:"23/06/2026 (truy xuất)", isNew:false, aff:["PVD"],
   title:"PVD: day rate giàn JU 2026 ~100.000 USD/ngày, cao hơn 2024; không khoan Lô B 2026",
   desc:"Ý nghĩa đầu tư: toàn bộ hợp đồng khoan 2026 đã ký; giàn PVD 1,2,6,8 ký HĐ mới giá cao hơn 2024, day rate trung bình giàn JU ~100.000 USD/ngày. PVD dự kiến không tham gia khoan Lô B 2026. Day rate cao + hiệu suất giàn đầy củng cố LN 2026 (+~40% YoY), ít phụ thuộc biến động giá dầu ngắn hạn.",
   srcName:"DNSE / IVAM", url:"https://www.dnse.com.vn/senses/tin-tuc/pv-drilling-pvd-du-kien-khong-tham-gia-khoan-du-an-lo-b-nam-2026-35119929"},
  {factor:"market", impact:1, date:"2026-06-23", srcDate:"23/06/2026 (truy xuất)", isNew:false, aff:["PVD","BSR","GAS","PVS"],
   title:"Cổ phiếu dầu khí lội ngược dòng, PVD/BSR/GAS hút mạnh dòng tiền",
   desc:"Ý nghĩa đầu tư: nhóm dầu khí hút mạnh dòng tiền bất chấp giá dầu giảm — PVD +3,5%, PVP +3,9%, BSR/PVS +1%; khối ngoại mua ròng PVD ~34 tỷ. Dòng tiền ưu tiên câu chuyện backlog thượng nguồn hơn biến động giá dầu ngắn hạn, xác nhận luận điểm thượng nguồn.",
   srcName:"Báo Văn Hóa / vietnam.vn", url:"https://baovanhoa.vn/kinh-te/co-phieu-dau-khi-loi-nguoc-dong-pvd-bsr-gas-hut-manh-dong-tien-209149.html"},
  {factor:"fuel", impact:0, date:"2026-06-23", srcDate:"23/06/2026 (truy xuất)", isNew:false, aff:["PLX","OIL","BSR"],
   title:"Giá xăng dầu trong nước có thể giảm phiên thứ 5 liên tiếp kỳ điều hành 25/6",
   desc:"Ý nghĩa đầu tư: dầu thế giới giảm sâu (Brent -3%+), giới kinh doanh dự báo kỳ điều hành thứ Năm 25/6 xăng E5/E10/diesel tiếp tục giảm — lần thứ 5 liên tiếp, về vùng thấp nhất khu vực. Giá bán lẻ giảm theo giá cơ sở ít ảnh hưởng biên gốc PLX/OIL nhưng tăng rủi ro lỗ tồn kho khi giá xuống nhanh; theo dõi chiết khấu và vòng quay tồn kho.",
   srcName:"VTC News / Techz", url:"https://vtcnews.vn/gia-xang-dau-hom-nay-23-6-quay-dau-giam-ar1025048.html"},
  {factor:"finance", impact:1, date:"2026-06-09", srcDate:"09/06/2026", isNew:false, aff:["PVS"],
   title:"PVS dự kiến hoàn nhập ~600 tỷ từ dự phòng Sao Vàng – Đại Nguyệt",
   desc:"Ý nghĩa đầu tư: khoản hoàn nhập ~600 tỷ củng cố triển vọng lợi nhuận 2026 của PVS, cộng hưởng backlog Lô B / Lạc Đà Vàng.",
   srcName:"Elibook", url:"https://elibook.vn/2026/06/09/pvs-du-kien-hoan-nhap-600-ty-tu-du-phong-du-an-sao-vang-dai-nguyet-cung-co-trien-vong-loi-nhuan-2026.html/"},
  {factor:"finance", impact:1, date:"2026-06-03", srcDate:"03/06/2026", isNew:false, aff:["PVD","PVS"],
   title:"Thượng nguồn PVS/PVD vẫn tích cực kể cả khi giá dầu hạ nhiệt",
   desc:"Ý nghĩa đầu tư: PVS doanh thu 5T/2026 ~13.500 tỷ (+34% YoY), LNST 2026 +9%; PVD lợi nhuận 2026 dự kiến +~40% nhờ day rate và hiệu suất giàn cao. Backlog là động lực chính, ít phụ thuộc biến động giá dầu ngắn hạn.",
   srcName:"Elibook", url:"https://elibook.vn/2026/06/03/neu-gia-dau-ha-nhiet-trien-vong-nhom-thuong-nguon-nhu-pvs-va-pvd-van-tich-cuc-o-ha-nguon-bsr-van-huong-loi.html/"},
  {factor:"refining", impact:1, date:"2026-06-03", srcDate:"03/06/2026", isNew:false, aff:["BSR"],
   title:"BSR hạ nguồn vẫn hưởng lợi nhờ crack spread cao",
   desc:"Ý nghĩa đầu tư: BSR được kỳ vọng hưởng lợi nhờ crack spread tốt và vận hành vượt công suất Dung Quất; theo dõi kỳ bảo dưỡng và tồn kho sản phẩm.",
   srcName:"Elibook", url:"https://elibook.vn/2026/06/03/neu-gia-dau-ha-nhiet-trien-vong-nhom-thuong-nguon-nhu-pvs-va-pvd-van-tich-cuc-o-ha-nguon-bsr-van-huong-loi.html/"},
  {factor:"legal", impact:1, date:"2026-06-20", srcDate:"20/06/2026", isNew:false, aff:["BSR"],
   title:"Chính phủ yêu cầu bán một phần dầu thô trong nước cho nhà máy lọc dầu nội địa",
   desc:"Ý nghĩa đầu tư: áp dụng Điều 59 khoản 8 Luật Dầu khí 2022 — nhà thầu phải bán một phần dầu thô/condensate (loại phù hợp) cho thị trường trong nước theo công suất lọc dầu nội địa, củng cố an ninh nguyên liệu đầu vào cho BSR (Dung Quất).",
   srcName:"Báo Chính Phủ", url:"https://baomoi.com/chinh-sach-moi-co-hieu-luc-tu-thang-6-2026-c55290298.epi"},
  {factor:"legal", impact:1, date:"2026-06-22", srcDate:"22/06/2026 (truy xuất)", isNew:false, aff:["POW","GAS"],
   title:"Dự thảo nghị định nâng bao tiêu điện LNG lên ≥75%, kéo dài 15 năm",
   desc:"Ý nghĩa đầu tư: MoIT dự thảo nâng sản lượng bao tiêu (Qc) điện LNG từ 65% lên tối thiểu 75% và kéo thời hạn cam kết từ 10 lên 15 năm — cải thiện tính khả thi/bankability dự án điện khí LNG (POW, GAS, NT2). Vẫn là dự thảo, theo dõi bản chính thức.",
   srcName:"Reccessary", url:"https://www.reccessary.com/en/insight/vietnam-dppa-revisions-electricity-market"},
  {factor:"legal", impact:0, date:"2026-06-01", srcDate:"01/06/2026", isNew:false, aff:["PLX","OIL"],
   title:"Bắt buộc xăng E10 toàn quốc từ 01/06/2026 (Thông tư 50/2025/TT-BCT)",
   desc:"Ý nghĩa đầu tư: lộ trình phối trộn E10 áp dụng toàn quốc từ 01/06/2026; E5RON92 vẫn được lưu hành tới 31/12/2030. Tác động vận hành tới phân phối xăng dầu (PLX, OIL) và nhu cầu ethanol; theo dõi chi phí phối trộn và nguồn cung cồn.",
   srcName:"Thanh Niên", url:"https://thanhnien.vn/cac-chinh-sach-moi-co-hieu-luc-tu-thang-62026-185260601131656434.htm"}
],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "oil", "impact": -2, "date": "2026-07-22", "srcDate": "22/07/2026 (truy xuất)", "isNew": true, "aff": ["PVD", "PVS", "BSR", "PLX", "OIL", "GAS"], "title": "Brent crude: 84.76 USD/thùng (-6.9% phiên 22/07)", "desc": "Ý nghĩa đầu tư: Giá dầu giảm gây áp lực sentiment thượng nguồn và tồn kho lọc dầu; PVD/PVS vẫn bám backlog dự án hơn là spot.", "srcName": "Yahoo Finance (BZ=F)", "url": "https://finance.yahoo.com/quote/BZ=F", "src": "py"},
    {"factor": "oil", "impact": 1, "date": "2026-07-22", "srcDate": "22/07/2026 (truy xuất)", "isNew": true, "aff": ["PVD", "PVS", "BSR", "PLX", "OIL"], "title": "WTI crude: 87.49 USD/thùng (+3.0% phiên 22/07)", "desc": "Ý nghĩa đầu tư: WTI tăng xác nhận đà hồi của dầu thô, hỗ trợ sentiment nhóm dầu khí.", "srcName": "Yahoo Finance (CL=F)", "url": "https://finance.yahoo.com/quote/CL=F", "src": "py"},
    {"factor": "gas", "impact": 0, "date": "2026-07-22", "srcDate": "22/07/2026 (truy xuất)", "isNew": false, "aff": ["GAS", "POW", "DPM", "DCM"], "title": "Khí tự nhiên Henry Hub: 2.89 USD/MMBtu (+1.0% phiên 22/07)", "desc": "Ý nghĩa đầu tư: Giá khí đi ngang, ít tác động ngắn hạn.", "srcName": "Yahoo Finance (NG=F)", "url": "https://finance.yahoo.com/quote/NG=F", "src": "py"},
    {"factor": "market", "impact": -1, "date": "2026-07-22", "srcDate": "22/07/2026 (truy xuất)", "isNew": true, "aff": ["PVD", "GAS", "DCM", "PVT", "POW", "DPM"], "title": "Nhóm dầu khí phiên 22/07: 2 mã tăng / 8 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — PVD -5.4%; GAS -5.3%; DCM -3.3%; PVT +3.1%; POW -2.6%; DPM -2.4%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "99ccaf5bc9548c99", "factor": "oil", "impact": 1, "date": "2026-07-23", "srcDate": "23/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Oil Prices Rise 3% as Iran War Stand-off Persists - Energy News, Top Headlines, Commentaries, Features & Events - EnergyNow.com", "desc": "Rule-based: Oil Prices Rise 3% as Iran War Stand-off Persists Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "EnergyNow.com", "url": "https://news.google.com/rss/articles/CBMihgFBVV95cUxOT05ScjQwX2cxMmpKblVhR2g0enp2S2RWWVZ4aXUyMGZJNUR3bkNwX0tCN1hTcXYzSUdTMlA5djVsQ0F6eE4wOTBfbHlnSUc0b0x2bXZ5UXZEOGhrYWhyVnJPcGJVWHZzM2hPSDB4bW1rMFp1NktuTEdjdDNaZngzX2l0aGVsQQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "ec3090488e20d78f", "factor": "oil", "impact": 0, "date": "2026-07-23", "srcDate": "23/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "US Crude Exports Hit Record High in May as Iran War Tightens Global Oil Supplies - EnergyNow.com", "desc": "Rule-based: US Crude Exports Hit Record High in May as Iran War Tightens Global Oil Supplies EnergyNow.com Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "EnergyNow.com", "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxNT1dDWUY4RFhYOXcwV0NSdEtRR0JLR0VMSXBQN3FKaDVTSlNvWE03MHNSNC1Sd2FXRkVGWU1qeHlFczZnbnd5al9ZdHdnOXUwNHhaMUx3ZWxEZTZJSUNpdS13R0lqeUdfV09tR1pJcGVaUHhjZDIxN2hSakJ5a2JkRnZyNGFvY0p0ZFROLS13UjhtSl84N0hvVUhLVnV2ZE9uS21OWXlqTzFxQ1JqX0NmMA?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "6c96af3da2df2095", "factor": "oil", "impact": 0, "date": "2026-07-23", "srcDate": "23/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Oil Price Forecast — Brent ($91.51), WTI ($86) Hit Five-Week Highs on the 11th Night of Iran Strikes — Hormuz Risk vs a $60 Fundamental Anchor - tradingnews.com", "desc": "Rule-based: Oil Price Forecast — Brent ($91.51), WTI ($86) Hit Five-Week Highs on the 11th Night of Iran Strikes — Hormuz Risk vs a $60 Fundamental Anchor tradingnews.com Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "tradingnews.com", "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOeWljVHotdzFBdk94Skp2d0RWTHZHbDliWVdoeXhGc2xwNDdBZXVfc2NlWE50eTdIZGE5MERRdDRXOVdxVldiY2Y3N3RnWFFnTEJWRlQ3MGtUcHJBUDQ3RFlMSUY4akxUQWVUbFBlSXJJY1BRdTBfWHhfcVJsRnRfQmNiX0FCWGR4LUtrcnRn?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "0f0196052e3c3241", "factor": "oil", "impact": 2, "date": "2026-07-22", "srcDate": "22/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Goldman Sachs Warns: If Hormuz Strait Disruption Persists, Brent Crude Could Surge Past $120 in Q4 - finance.biggo.com", "desc": "Rule-based: Goldman Sachs Warns: If Hormuz Strait Disruption Persists, Brent Crude Could Surge Past $120 in Q4 finance.biggo.com Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "finance.biggo.com", "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE8zcm5XQzVHZXIzUV84bGx0V0V1akw3RUFzS0F0eHl3alRadVFpWXNLQjhicDE4M2YzeVhWNk1mMUlmWG1rNnVScHNCalYxWEVHR3JjSDRGcWF6NllnTEZZbjlFcG1pdU92TlIxOHJiV2RrdW1DQ1E?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "96824f52a0bd55eb", "factor": "oil", "impact": 1, "date": "2026-07-22", "srcDate": "22/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Oil Prices Up Over 3% Over Concerns About Prolonged Hormuz Disruption - EnergyNow.com", "desc": "Rule-based: Oil Prices Up Over 3% Over Concerns About Prolonged Hormuz Disruption EnergyNow.com Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "EnergyNow.com", "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxQWU1mb2RuUzdVRV81T2J1UnFkcUNwVlpVT1Y2YzJma2RueGZxbHowQmJJSWg2a2ItWC1IUUpxUEMzNW5xS0RiWlZGMklDVUotczE2RmFrUUZIRE1PMDRuTVI5eHlRRkZNQlY3TFM3cXYzM3FleGk5cW1ZbF9NbHFEbmlfTEt6R0lmOU5hYmlscGpzYW9oUkRIT290MjVidzc1?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "43cc31471b344178", "factor": "market", "impact": -1, "date": "2026-07-22", "srcDate": "22/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Hormuz on a Knife-Edge: Shipping Pays the Price as the Iran-U.S. Ceasefire Unravels - gCaptain", "desc": "Rule-based: Hormuz on a Knife-Edge: Shipping Pays the Price as the Iran-U.S. Ceasefire Unravels gCaptain Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "gCaptain", "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQMXpVNWpqVnBoUkZNMWJEcjZ2MmstOGVYTDViTm1rMmJoaFlmeDFXUjFXZjhkd2VmUkthZ1YzR29QdEFyajhFV3lQb1l4ME5ScTM3bmJCSGhCY2lHRGtLdFZKY3JKTVAtV1gwOUdJX0hCZWxxbUZaczVSeGVaOVFNWWFVdFowTThVUTN4TERGTnhPTDJCdm5NZEdySWRnNUpidTVRb1NB?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "7ed77e5f2e27b42b", "factor": "oil", "impact": 0, "date": "2026-07-22", "srcDate": "22/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "WTI Price Forecast: Middle East tensions lift Oil as bulls test the 100-day SMA - TMGM trading", "desc": "Rule-based: WTI Price Forecast: Middle East tensions lift Oil as bulls test the 100-day SMA TMGM trading Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "TMGM trading", "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxOZEFiRHJ4a0JJSXRrdU1PNjFPYXZ4YVBiY3VzWUQwV3FSYTIwNlJxSlNQYTZBT2ViSVVJSzBOaVI2cWdTUXRTUU40V2k3NFppTUJKWHJQS1I0TmZHZVZ2OVVTZ0VrOGZhT0RtM3dnRnh3WjZqYXRCZmJEcURjRV9ZMUVlMlA4RDFKd1JlcTFuZXY2Y0NMT1VDRlBSTTUteTU4Q0JoRUp6T0hMZDcwUExyRkFET0hVQ2lJSU5Od1pvQU1SZjNDNEREX2JWcmQySVNTNkF0Y3pIWnZqZDNw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "338aa57385c4d535", "factor": "oil", "impact": 0, "date": "2026-07-22", "srcDate": "22/07/2026", "isNew": true, "aff": ["PVD", "PVS", "GAS", "BSR", "PLX"], "title": "Vì sao cổ phiếu dầu khí bị bán tháo khi giá dầu vẫn neo cao? - Báo VietNamNet", "desc": "Rule-based: Vì sao cổ phiếu dầu khí bị bán tháo khi giá dầu vẫn neo cao? Báo VietNamNet Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Báo VietNamNet", "url": "https://news.google.com/rss/articles/CBMimgFBVV95cUxPZXplMTRLbk5mZWRrckxjb3NaNjRSTVBrcHlXZlpvWDBiWWY5YlcycDY3OVJuaTlKTjdYcnE0UVVwX0pIenRjR3V5cVB0YWhqVWJqM1dVSTBUU0ljVFlGc3loY3YyWGlTRC0xMkxmYWtNSHB5bWx6YmNMQXZVMW5VR0xPNmZ6S3RkdVJndE1fWDdDUkZaYTFxS2NB?oc=5", "src": "news", "sourceScope": "local"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
  ["Thăm dò / phát triển mỏ","PSC, FDP, FID, vốn E&P","PVS, PVD, PVC, PVB, PXS","Khung pháp lý rõ; giá dầu đủ cao; dự án được duyệt"],
  ["Khoan giếng","Day rate, hiệu suất giàn, hợp đồng khoan mới","PVD","Giá thuê giàn, hiệu suất sử dụng, hợp đồng mới"],
  ["EPC/EPCIC ngoài khơi","Backlog, tiến độ, biên hợp đồng","PVS, PVB, PVC, PXS","Backlog tăng, thi công đúng tiến độ"],
  ["Thu gom / vận chuyển khí","Đường ống, GPP, LNG terminal","GAS, CNG","Sản lượng khí, giá khí, phí vận chuyển, LNG"],
  ["Vận tải dầu / LPG / sản phẩm","Tàu dầu thô, sản phẩm, LPG","PVT","Giá cước, đội tàu, nhiên liệu, hợp đồng dài hạn"],
  ["Lọc dầu","Sản phẩm xăng/diesel/Jet/LPG","BSR","Crack spread, bảo dưỡng, tồn kho, công suất"],
  ["Phân phối xăng dầu","Bán buôn/lẻ, logistics","PLX, OIL","Điều hành giá, chiết khấu, nhu cầu, tồn kho"],
  ["Tiêu thụ khí","Điện khí, phân bón, LPG/CNG","POW, DPM, DCM, CNG","Giá khí đầu vào, giá điện, sản lượng, giá ure"]
],
  tickers: [
  ["PVD","Day rate; hiệu suất giàn; hợp đồng khoan; tiến độ Lô B","Hợp đồng khoan mới; giá dầu cao; giàn full; Lô B đúng tiến độ","Giàn nhàn rỗi; dự án chậm; chi phí tăng; giá dầu giảm mạnh"],
  ["PVS","Backlog EPC/EPCIC; Lô B; FSO/FPSO; biên hợp đồng","Dự án lớn tăng tốc; thầu mới; backlog tăng; biên cải thiện","Chậm tiến độ; vượt dự toán; biên thấp; tranh chấp"],
  ["GAS","Sản lượng khí khô; LPG/LNG; giá khí; khách điện/đạm","Sản lượng tăng; cơ chế giá/PPA rõ; LNG tiêu thụ ổn","Nguồn khí giảm; ít huy động điện khí; LNG giá cao"],
  ["PVT","Đội tàu; cước tanker/LPG; giá bunker; tỷ giá","Cước tăng; mở rộng đội tàu hiệu quả; hợp đồng dài hạn","Nhiên liệu tăng; tàu già; cước giảm; áp lực vay USD"],
  ["BSR","Crack spread; công suất Dung Quất; tồn kho; bảo dưỡng","Crack tốt; vận hành cao; nâng cấp đúng tiến độ; tồn kho lãi","Crack xấu; bảo dưỡng kéo dài; giá dầu bất lợi; tồn kho lỗ"],
  ["PLX","Sản lượng bán; biên bán lẻ; giá cơ sở; chiết khấu; E10","Nhu cầu tăng; giá sát thị trường; chiết khấu cải thiện","Giá điều hành chậm; lỗ tồn kho; biên bị siết"],
  ["OIL","Sản lượng bán; đấu thầu; kênh bán lẻ; chiết khấu","Nhu cầu tăng; chiết khấu tốt; mở rộng bán lẻ","Biên thấp; tồn kho xấu; cạnh tranh mạnh"],
  ["POW","Sản lượng điện; huy động điện khí; giá khí; PPA","Điện khí huy động cao; PPA rõ; giá khí ổn","Giá khí cao; ít huy động; sự cố; PPA/LNG chậm"],
  ["DPM","Giá ure; sản lượng; giá khí; nhu cầu nông nghiệp","Giá ure tăng; khí ổn; biên tốt","Giá ure giảm; khí tăng; nhu cầu yếu"],
  ["DCM","Giá ure/NPK; khí đầu vào; xuất khẩu; nhu cầu ĐBSCL","Giá ure/NPK tốt; khí ổn; sản lượng tăng","Giá ure giảm; chi phí khí tăng; xuất khẩu yếu"]
],
  sources: [
    ["Petrovietnam (PVN)","https://pvn.vn/","Tin tập đoàn, tiến độ dự án, sản lượng"],
    ["Năng lượng Việt Nam – Dầu khí","https://nangluongvietnam.vn/dau-khi-viet-nam","Phân tích chuyên sâu ngành dầu khí"],
    ["Brent – Trading Economics","https://tradingeconomics.com/commodity/brent-crude-oil","Giá dầu Brent, biến động thời gian thực"],
    ["EIA (Mỹ)","https://www.eia.gov/","Dự báo giá dầu, cân đối cung – cầu"],
    ["PV GAS","https://www.pvgas.com.vn/","Khí khô, LPG, LNG, giá khí"],
    ["BSR (Lọc hóa dầu Bình Sơn)","https://www.bsr.com.vn/","Vận hành Dung Quất, crack spread"],
    ["PVTrans (PVT)","https://pvtrans.com/","Vận tải dầu/LPG, đội tàu, cước"]
  ]
};
