// ====== DỮ LIỆU NGÀNH THỦY SẢN — task "quet-nganh-thuy-san" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.thuysan = {
  id: "thuysan",
  name: "Thủy sản",
  icon: "🐟",
  order: 3,
  scope: "VHC, ANV, FMC, MPC, IDI, CMX",
  subtitle: "Sentiment ngành thủy sản VN theo chuỗi giá trị — xuất khẩu & thị trường, thuế & phòng vệ thương mại, nguyên liệu/nuôi trồng, chi phí đầu vào, tỷ giá, rào cản (IUU), tài chính, dòng tiền. Phạm vi: VHC, ANV, FMC, MPC, IDI, CMX (+ ASM, ABT). Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-09-02T18:00:48+07:00",
  factors: {
  export:"Xuất khẩu & thị trường", tariff:"Thuế & phòng vệ TM", material:"Nguyên liệu & nuôi trồng",
  feed:"Chi phí đầu vào", fx:"Tỷ giá", policy:"Pháp lý & rào cản (IUU)", finance:"Tài chính DN", market:"Thị trường & dòng tiền"
},
  sentiment: {
    score: 0, date: "2026-09-02",
    reason: "Tự động tổng hợp từ 7 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Việt Nam – Hà Lan mở rộng hợp tác nuôi trồng thủy sản bền vững từ công nghệ đến thị trường - VASEP (VASEP, 01/09/2026). Tiêu cực: Khô đậu tương CBOT: 350.6 USD/tấn ngắn (+4.8% phiên 01/09) (Yahoo Finance (ZM=F), 01/09/2026 (truy xuất)). Có 5 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:2, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC"], title:"Vĩnh Hoàn tháng 5: doanh thu thuần 1.737 tỷ (+44%), Mỹ +46%, sản phẩm phụ (C&G) +102%", desc:"Ý nghĩa đầu tư: Thị trường Mỹ (633 tỷ, +46%) và EU (+81%), TQ (+50%) đồng loạt phục hồi; mảng sản phẩm phụ collagen/gelatin bật +102% lên 336 tỷ — củng cố biên lợi nhuận và vị thế dẫn đầu cá tra của VHC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"export", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Ngành bước vào cao điểm đơn hàng tháng 7-8; cá tra 5T XK +12,6% (905 triệu USD), TQ/HK tăng mạnh", desc:"Ý nghĩa đầu tư: Cầu Mỹ-TQ phục hồi, tồn kho thấp và nguồn cung cá thịt trắng tự nhiên thắt chặt giúp DN giữ/đẩy giá bán; cao điểm cuối năm hỗ trợ doanh số — tích cực cho cả cá tra (VHC/ANV/IDI) lẫn tôm (FMC/MPC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"tariff", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","MPC","CMX"], title:"Sao Ta kẹt thuế Mỹ: mỗi container phải đóng cọc 25%, tạm chỉ bán hàng không chịu thuế", desc:"Ý nghĩa đầu tư: Tiền cọc 25%/container gây kẹt vốn tại thị trường Mỹ; FMC dồn sang Nhật (30%)/EU (25%) và tập trung sản phẩm biên cao — rủi ro thuế tôm tiếp tục đè biên nhóm FMC/MPC/CMX.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"finance", impact:1, date:"2026-06-29", srcDate:"29/06/2026", isNew:true, aff:["MPC"], title:"Minh Phú khánh thành nhà máy chế biến Minh Phú Khánh An (Cà Mau), tự động hoá cao", desc:"Ý nghĩa đầu tư: 5T/2026 MPC XK >19.726 tấn tôm, doanh số >211,7 triệu USD, LN ~489,3 tỷ; nhà máy mới ứng dụng robot/tự động hoá giúp tối ưu chi phí, đẩy hàng GTGT — nâng năng lực cạnh tranh MPC.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/minh-phu-mpc-khanh-thanh-nha-may-che-bien-thuy-san-minh-phu-khanh-an-tai-ca-mau-post393104.html"},
    {factor:"finance", impact:1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["ANV","FMC"], title:"Dự báo LNST 2026: ANV ~1.100 tỷ (+10%), FMC ~400 tỷ (+15%) — Chứng khoán NH Việt Nam", desc:"Ý nghĩa đầu tư: Giá cá tra & cá rô phi neo cao cùng cầu các thị trường trọng điểm tích cực hỗ trợ ANV; FMC kỳ vọng phục hồi lợi nhuận nhờ đa dạng thị trường dù vướng thuế Mỹ.", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"material", impact:0, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["VHC","ANV","IDI","FMC","MPC"], title:"Giá cá tra nguyên liệu neo >30.000đ/kg; chi phí nhiên liệu cao do căng thẳng Mỹ-Iran", desc:"Ý nghĩa đầu tư: Nguyên liệu cao phản ánh đơn hàng dồi dào nhưng cũng bào mòn biên nếu không chuyển được sang giá bán; chi phí nhiên liệu (Mỹ-Iran) đẩy chi phí khai thác/nuôi/vận chuyển — theo dõi biên gộp Q2.", srcName:"Tin nhanh chứng khoán (ĐTCK)/VASEP", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"},
    {factor:"market", impact:-1, date:"2026-06-30", srcDate:"30/06/2026", isNew:true, aff:["FMC","ANV","MPC","IDI"], title:"Tuần qua cổ phiếu thủy sản điều chỉnh nhẹ: FMC -0,98%, ANV -0,91%, MPC -0,63%, IDI -3,61%", desc:"Ý nghĩa đầu tư: Nhóm phân hoá và chốt lời ngắn hạn trước mùa cao điểm dù triển vọng tích cực; dòng tiền chọn lọc mã có hiệu suất vận hành tốt (ưu tiên VHC).", srcName:"Tin nhanh chứng khoán (ĐTCK)", url:"https://www.tinnhanhchungkhoan.vn/co-phieu-thuy-san-don-mua-cao-diem-don-hang-post393075.html"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "feed", "impact": -1, "date": "2026-09-01", "srcDate": "01/09/2026 (truy xuất)", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Khô đậu tương CBOT: 350.6 USD/tấn ngắn (+4.8% phiên 01/09)", "desc": "Ý nghĩa đầu tư: Khô đậu tăng làm tăng tham chiếu chi phí thức ăn thủy sản, bất lợi biên nuôi trồng/chế biến.", "srcName": "Yahoo Finance (ZM=F)", "url": "https://finance.yahoo.com/quote/ZM=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-09-01", "srcDate": "01/09/2026 (truy xuất)", "isNew": false, "aff": ["VHC", "ANV", "FMC", "MPC", "IDI", "CMX"], "title": "Tỷ giá USD/VND: 26070.0 đồng (+0.0% phiên 01/09)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": true, "aff": ["IDI", "VHC", "ANV", "CMX", "FMC", "MPC"], "title": "Nhóm thủy sản phiên 28/08: 0 mã tăng / 5 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — IDI -1.4%; VHC -0.4%; ANV -0.3%; CMX -0.2%; FMC -0.1%; MPC +0.0%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "6426c3661e576ddf", "factor": "market", "impact": 0, "date": "2026-09-02", "srcDate": "02/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Tôm khai thác tự nhiên đối mặt nhiều thách thức về bền vững và nguồn cung - VASEP", "desc": "Rule-based: Tôm khai thác tự nhiên đối mặt nhiều thách thức về bền vững và nguồn cung VASEP Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxOa3ZCRVdhcnVyQ1pBYnhRc2FQVTlYLUpNR2dsdzBlLXV4aElCcmhBR3Vxd2xPLUpETUp0X08xVkxXb25JS3BBdkcwcDR0Rnd0OGpVaHJNV0ZiWE90V1FCSXRFUnVXUGxWOFR2TjZKdm40WldmYkZZdnR6RG5JMHY5WmdrOVh0OXk2NUNlcWYwVEZNXzdGNHVwd1QtQ2pSTXZwb3d3cE5aVzVjT2w4YkHSAa4BQVVfeXFMTmt2QkVXYXJ1ckNaQWJ4UXNhUFU5WC1KTUdnbHcwZS11eGhJQnJoQUd1cXdsTy1KRE1KdF9PMVZMV29uSUtwQXZHMHA0dEZ3dDhqVWhyTVdGYlhPdFdRQkl0RVJ1V1BsVjhUdk42SnZuNFpXZmJGWXZ0ekRuSTB2OVpnazlYdDl5NjVDZXFmMFRGTV83RjR1cHdULUNqUk12cG93d3BOWlc1Y09sOGJB?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "d64efcfc8fd3af38", "factor": "market", "impact": 0, "date": "2026-09-02", "srcDate": "02/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Shrimp Meal for Aquaculture Market Outlook to 2035 - IndexBox", "desc": "Rule-based: Shrimp Meal for Aquaculture Market Outlook to 2035 IndexBox Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "IndexBox", "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxNMEk5dUZUNHJSWDdCRTZJc2pjXzJUVXlQLWVNRkt6Z3R1bmlfazA0YmhTSDlKdV9IV1NTM2xqWEE0YTBLQngwNGFqU2ZsNDN2MjhDVXFTenVjbTh5VTdvb2xoTE00N0YtNHItUTdvYUR0UkpDdFlhbWpIbUk3VzZEUVluZ094d0U?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "4f71554d3334e4ff", "factor": "market", "impact": 0, "date": "2026-09-02", "srcDate": "02/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Doanh nghiệp và nhà mua hàng đã tìm thấy gì tại Vietfish 2026? - VASEP", "desc": "Rule-based: Doanh nghiệp và nhà mua hàng đã tìm thấy gì tại Vietfish 2026? VASEP Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNTWF0N0kxQXBraVBqcU5UMnlMNGRjcEJFVFktT2RKQzRGM21sNURUcWV0bWk1XzlyRmJ3TTJzN0JmTV9ERVY2WmdxdHhUZ0xmWHJVWHQ3RGdtYWhHUE50blNNRU1MRUFOVnN3WW1CTUVRc3V5dUtpUEotUGM2SkpDZGhYSmw3VVJwU1VZRTJxaEZocFBMSU9BQWhkMk1vdm9ORDMxN2tR0gGeAUFVX3lxTE9TOU81Z0lTMnA4b2dUX3k4aUhyQ0pfakpXem9iWjRmMmlvVWlDQTZRV3dibEpPdE5fdVhkTkRURlRoekpOVmZ1Z2xEdFZzeGl5cUw4QlZPM0hOQlhsVEVZalFTRzdnalpVX25mdmZrQURta1ZpRlJKMUNEZHMwRkpMRF96MFJMbFF2ZTFzQzNQenNLVm9RVzBybUlINXBB?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "da7e0c197a5e04eb", "factor": "market", "impact": 1, "date": "2026-09-01", "srcDate": "01/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Việt Nam – Hà Lan mở rộng hợp tác nuôi trồng thủy sản bền vững từ công nghệ đến thị trường - VASEP", "desc": "Rule-based: Việt Nam – Hà Lan mở rộng hợp tác nuôi trồng thủy sản bền vững từ công nghệ đến thị trường VASEP Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMi-wFBVV95cUxNTlBYbnNCc1d4dW5DeFpnY1NROThYWFlRdFhLUTl3Qk01clBremh4NDNFbkZoMU5IZFpLampCX2dvc3hKTWRkcjl1N1J2WnVvdXh0VmNRZkg3a1M4ckZWbi1iS3B2aFpJUVVYYzcwckZJZ3F5WUtNcEpkX29PUEZEZlFIV2V6QWdHS0dvSEp2UFliM19nX1BqM3BhbTFvNlBrVVBFWkxBYzN2cE95TXY5QjA1ZmRpRUZOcE1OZGkyTlR5c0lubWdUdzdUdWVjVEYyS29pLWZVR0l2VDF3N1E4cjJpdE4zVXdSelhqdEVMTmNWX3NGMDBsVTlld9IBwgFBVV95cUxNMkhULU1jZ0VuNnU3c0h6U0JVQXpOV1I5Vkc5VGduTkQzUHY2amUyZ1lZMmtEejFsOXNWVmM3Q005MTAwMlhqUUN2aVZUZGNHV29mdlFDTF9nUi1sdDcwOFh1eEJaTjl2enZEX1cwUVpVUV9WbzRPa1dtVXFaMDhYNG1aNHVRVlB6MzdZekR0a0RsbjZObGtuNDVFVGU3T2llRG51LTd3TWJVTjVpdzdoRGVvX3ZCR3hNSXZpUHgxeXRIQQ?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "68f9752260f9d540", "factor": "export", "impact": 0, "date": "2026-09-01", "srcDate": "01/09/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Trung Quốc chi hơn 20 tỷ USD mua tôm, cá: Việt Nam có 2 mặt hàng đứng top đầu - Vietnam.vn", "desc": "Rule-based: Trung Quốc chi hơn 20 tỷ USD mua tôm, cá: Việt Nam có 2 mặt hàng đứng top đầu Vietnam.vn Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Vietnam.vn", "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQWUh6NGNMaWFzcU9VQ0txb2EyY3N6cngyQl9tcmF4dFU2ZjZZTGZSNEd2MGJVX0p2WVFmMTZoa01RVzdRNGl3LUtaZDFhODFHZGZ0dUx2UlVJWFFOWU1sSUZfR1J0ajNXRlNhUF81NlJkYV94WUZWaDI4MUZLbTAxY0ZaQmx3TlpON2RwOEFvY2hrdmU0YVVfY20zd1UwR2M?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "bd0ae90565a2b882", "factor": "market", "impact": -1, "date": "2026-08-30", "srcDate": "30/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Bộ Công Thương phản hồi kiến nghị giảm chi phí logistics cho thủy sản - Báo Nông nghiệp và Môi trường", "desc": "Rule-based: Bộ Công Thương phản hồi kiến nghị giảm chi phí logistics cho thủy sản Báo Nông nghiệp và Môi trường Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Báo Nông nghiệp và Môi trường", "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxQaWJMYlU4VU00SHdnc3hMcGppU2k4b3htb3Z4SWUxWTZPLTVlN09mTTFmUWJvcFNBZ2JHVU5OQlhvTWd5MnNMV01aS2IzZTluYVZyb3B0M3p5SkxKaFZPLW5xcDREYVNieE4yc3VvSUI2N2tKRGdJY3JNRTlVeUlsMTFMT05sOWcxeHhWUzBXc2pkemJOYnhQWWprNGJPaUZTdnlQUGpxWjBkZ1RxbXJaNUFUaw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "090ad2ad3e477be9", "factor": "market", "impact": 0, "date": "2026-08-28", "srcDate": "28/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "VASEP Highlight - T8/2026: Nghêu - VASEP", "desc": "Rule-based: VASEP Highlight Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "VASEP", "url": "https://news.google.com/rss/articles/CBMi_gFBVV95cUxOWlE4OF94dHhoWTNUdUQzVlp2aEROZTFuN0VnWXk2a3JNTWtvZFBZcmozMWNsMjJERm8zMVpGamtiZzFPNzB1VGU1eDFLN0FOMkpocUwtaHpPUjZDdFF2dncyQnhqandWeEZFT19ZNHliTUVJR2FYMU1PNUQ1TmpiZG96ZUpobXJqMzNXNmY3Wmxmbk1PeWZYalZhXzdCSlJpNVhOcWxvM3NpVjZMdEVqWXQtdHR0bU1ITGhxc2ctZ2xKbkVCMXNtRmxBRmk2eE9ScTN1eTR3R205cllhVUhsWTN2Y284MWtjcFZrRlY3OUxxVkFQQTQycDhzc1JOZw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "2ae00e07ad1d8732", "factor": "market", "impact": 0, "date": "2026-08-28", "srcDate": "28/08/2026", "isNew": true, "aff": ["VHC", "ANV", "FMC", "MPC"], "title": "Royal Greenland back to profit in first half of 2026 - WEAREAQUACULTURE", "desc": "Rule-based: Royal Greenland back to profit in first half of 2026 WEAREAQUACULTURE Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "WEAREAQUACULTURE", "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxNQi01MXVzSWV6S0dzX1ptTmRHX1pzc1UyN1JMcml4eFBTOXFFcG1qLXFnd2VxcUpYc2xoc0JfNGpjTXM0eGxDMDZ0OVJpOFZ6dTM4cDd0Sno3SXgya0NWVEFhVV9pV09seEFOWjF2X0Y1NndmUnVxRVhZbWlMLTBmZG9ETTktT3d4aDh2RXh1bVNoVHJSaUhYLXJoVDTSAaoBQVVfeXFMTzg0dGlLTUtkSE03azdxYU9qMk83ZVFRMFhPaWNERUxyckpOSHNJTTBCaFYzdWpXakZTZEhXS1dHMFZQTF8yZmxodFRsMzI2SEI2YlBJVkcyVmVwU2VtM0kzbzdaajIwbHdkQWJxNlNLZE4tbEMwdmJEQ0hyVUpBNkFWM09obnpYa0JKNzkzS3JzOUQtdDNHQUxHb2RSd0FESTh3eG9TMnB2S3c?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
  ["Thức ăn thủy sản","Giá đậu nành/bột cá; tự chủ thức ăn","(đầu vào) ASM, các DN tự chủ","Giá nguyên liệu thức ăn giảm; tự chủ cao"],
  ["Con giống & nuôi trồng","Vùng nuôi tự chủ; giá cá tra/tôm nguyên liệu; dịch bệnh","VHC, ANV, FMC, MPC","Giá nguyên liệu hợp lý; vùng nuôi tự chủ; ít dịch bệnh"],
  ["Chế biến","Công suất; tỷ trọng hàng GTGT; sản phẩm phụ (collagen)","VHC, FMC, MPC, IDI, CMX","Công suất chạy cao; tăng hàng GTGT & C&G"],
  ["Xuất khẩu","Đơn hàng; thị trường Mỹ/TQ/EU/Nhật; giá bán","VHC, ANV, FMC, MPC","Đơn hàng tốt; giá XK tăng; đa dạng thị trường"],
  ["Thị trường tiêu thụ","Thuế CBPG/đối ứng; rào cản IUU/MMPA; cạnh tranh Ecuador/Ấn Độ","VHC, FMC, MPC","Thuế thấp/miễn trừ; rào cản nới; cạnh tranh giảm"]
],
  tickers: [
  ["VHC","Cá tra; thị trường Mỹ/TQ; mảng C&G (collagen); giá cá tra","Giá cá tra & giá XK tăng; thuế Mỹ thấp; C&G tăng","Thuế CBPG Mỹ cao; giá cá tra giảm; cầu Mỹ yếu"],
  ["ANV","Cá tra; mở rộng Trung Quốc; tự chủ vùng nuôi & thức ăn","Thị phần TQ tăng; biên cải thiện; tự chủ chuỗi","Phụ thuộc TQ; giá cá tra giảm; chi phí tăng"],
  ["IDI","Cá tra; thị trường TQ/ASEAN; tồn kho cá","Giá cá tra phục hồi; tồn kho lãi","Giá cá tra yếu; tồn kho lỗ; biên mỏng"],
  ["FMC","Tôm; thị trường Nhật/Mỹ; vùng nuôi; hàng GTGT","Đơn tôm tốt; Nhật ổn định; vùng nuôi mở rộng","Thuế CBPG tôm Mỹ; cạnh tranh Ecuador/Ấn Độ; giá tôm giảm"],
  ["MPC","Tôm (lớn nhất); chuỗi khép kín; thị trường Mỹ","Giá tôm tăng; thị phần Mỹ giữ; chuỗi hiệu quả","Thuế tôm Mỹ 25,76%; giá tôm thấp; dịch bệnh"],
  ["CMX","Tôm; thị trường EU; tôm sinh thái","Cầu EU tốt; giá tôm tăng; chứng nhận sinh thái","Rào cản EU; giá tôm giảm; chi phí cao"]
],
  sources: [
    ["VASEP","https://vasep.com.vn/","Số liệu & dự báo xuất khẩu tôm, cá tra, cá ngừ; thuế Mỹ"],
    ["Tổng cục Hải quan","https://www.customs.gov.vn/","Kim ngạch xuất nhập khẩu theo tháng"],
    ["Thị trường cá tra","https://www.thitruongcatra.com/","Giá cá tra nguyên liệu, thị trường"],
    ["Vĩnh Hoàn (VHC)","https://www.vinhhoan.com/","IR: KQKD, sản lượng, mảng C&G"],
    ["Sao Ta (FMC)","https://fimexvn.com/","IR: doanh số tôm theo tháng, thị trường"],
    ["Nam Việt (ANV)","https://navicorp.com.vn/","IR: cá tra, thị trường Trung Quốc"],
    ["Minh Phú (MPC)","https://minhphu.com/","IR: tôm, thuế CBPG Mỹ"]
  ]
};
