// ====== DỮ LIỆU NGÀNH DỆT MAY — task "quet-nganh-det-may" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.detmay = {
  id: "detmay",
  name: "Dệt may",
  icon: "🧵",
  order: 4,
  scope: "TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG",
  subtitle: "Sentiment ngành dệt may VN theo chuỗi giá trị — đơn hàng & xuất khẩu, thuế & thương mại, nguyên liệu (bông/sợi), tỷ giá, lao động, ESG & xanh hóa, tài chính DN, dòng tiền. Phạm vi: TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-09-05T22:05:12+07:00",
  factors: {
    export: "Đơn hàng & xuất khẩu", tariff: "Thuế & thương mại", input: "Nguyên liệu (bông/sợi)",
    fx: "Tỷ giá", labor: "Lao động & chi phí", esg: "ESG & xanh hóa",
    finance: "Tài chính DN", market: "Thị trường & dòng tiền"
  },
  sentiment: {
    score: -1, date: "2026-09-05",
    reason: "Tự động tổng hợp từ 11 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Hơn 170 doanh nghiệp quốc tế đến Tây Ninh: Muốn có đơn hàng, phải minh bạch chuỗi cung ứng - Một Thế Giới (Một Thế Giới, 05/09/2026); Bangladesh rises to second-largest apparel exporter globally - Textile Today (Textile Today, 05/09/2026). Tiêu cực: India Holds Back on US Trade Pact as New Delhi Seeks Better Tariff Terms - Global Sources (Global Sources, 05/09/2026); | South India cotton yarn turns soft amid falling cotton prices - Fibre2Fashion (Fibre2Fashion, 04/09/2026). Có 4 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["HTG","VGT"], title:"Dệt may Hòa Thọ (HTG): XK nửa đầu năm 2026 ~148,5 triệu USD (+14%), doanh thu hợp nhất 2.893 tỷ (+9%), lãi riêng 224,3 tỷ (đạt 56% KH năm)", desc:"Ý nghĩa đầu tư: HTG (mảng may FOB, thuộc VGT) duy trì đà tăng trưởng 2 con số bất chấp thị trường biến động — green flag cho KQKD 6T; cổ tức tiền mặt cao là điểm cộng. Theo dõi đơn hàng nửa cuối năm và rủi ro thị trường Mỹ.", srcName:"Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"export", impact:-1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"VITAS: XK dệt may 5T2026 ~17,81 tỷ USD (+0,6%) — may mặc 13,72 tỷ GIẢM 1,5%; xơ sợi 1,90 tỷ (+9,6%), vải +6,9%", desc:"Ý nghĩa đầu tư: Phân hóa rõ — mảng MAY mặc (TNG, MSH, GIL, HTG) suy yếu cầu, áp lực cho mục tiêu cả năm 48–49 tỷ USD; mảng SỢI/xơ (STK, ADS, VGT) ngược dòng tăng tốt. Ưu tiên mã có tỷ trọng sợi/đơn giá tốt.", srcName:"VITAS / Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"input", impact:-1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:true, aff:["TCM","STK","ADS","VGT"], title:"Giá bông thế giới (ICE) ~78 US cent/lb, tăng ~18% từ đầu năm trên kỳ vọng nguồn cung toàn cầu thắt chặt", desc:"Ý nghĩa đầu tư: Bông neo cao đẩy chi phí đầu vào mảng may/dệt (TCM) và chi phí bông cho kéo sợi; có thể hỗ trợ giá bán sợi nhưng bóp spread bông–sợi nếu cầu yếu (STK, ADS, VGT). Theo dõi chênh bông–sợi.", srcName:"Trading Economics – Cotton", url:"https://tradingeconomics.com/commodity/cotton"},
    {factor:"fx", impact:1, date:"2026-06-17", srcDate:"17/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"Tỷ giá USD/VND căng: tỷ giá trung tâm 25.165 (16/6), NHTM đồng loạt bán USD kịch trần ~26.433", desc:"Ý nghĩa đầu tư: USD mạnh hỗ trợ doanh thu/biên quy đổi cho nhóm xuất khẩu dệt may (đa số doanh thu USD, chi phí VND) — tích cực cho TNG, MSH, HTG, STK. Lưu ý DN vay USD chịu áp lực chi phí tài chính.", srcName:"Thanh Niên", url:"https://thanhnien.vn/gia-usd-hom-nay-1662026-do-tu-do-bat-tang-18526061608200601.htm"},
    {factor:"finance", impact:1, date:"2026-06-13", srcDate:"13/06/2026", isNew:true, aff:["VGT"], title:"Tập đoàn Dệt May Việt Nam (VGT/Vinatex) ước lãi ~763 tỷ đồng 6T2026 (+14%); đơn sợi đầy đến hết T7, may đến T8–9, song đơn hàng đang chậm lại chờ thuế Mỹ", desc:"Ý nghĩa đầu tư: KQKD hợp nhất 6T tích cực cho VGT, nhưng ban lãnh đạo cảnh báo đơn hàng chững lại — lợi nhuận tốt là quá khứ, biến số là đơn quý IV. Theo dõi lấp đầy chuyền và tín hiệu thuế quan.", srcName:"CafeF", url:"https://cafef.vn/tap-doan-det-may-viet-nam-uoc-lai-763-ty-dong-tang-14-trong-6-thang-dau-nam-don-hang-dang-cham-lai-cho-cau-chuyen-thue-quan-cua-my-188260613013603581.chn"},
    {factor:"tariff", impact:-1, date:"2026-06-12", srcDate:"12/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","VGT"], title:"ALERT — Đơn hàng quý IV khan hiếm: khách nhập khẩu 'nghe ngóng' chờ thuế đối ứng song phương Mỹ (sau 24/7), cộng chi phí vận tải biển +30–40% do xung đột Trung Đông", desc:"Ý nghĩa đầu tư: Rủi ro thiếu đơn cuối năm là tâm điểm — nhạy nhất với MSH (tỷ trọng khách Mỹ lớn); cửa sổ thuế tạm 10% hết hạn 24/7 là mốc quyết định dịch chuyển đơn TQ→VN. Quan sát mức thuế thực tế của VN so Indonesia/Campuchia/Bangladesh.", srcName:"Dân trí / Vietstock", url:"https://dantri.com.vn/kinh-doanh/det-may-viet-nam-doi-mat-ap-luc-kep-tu-thue-quan-va-xung-dot-trung-dong-20260612173236317.htm"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "input", "impact": -1, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": true, "aff": ["TCM", "STK", "ADS", "VGT", "TNG", "MSH"], "title": "Bông ICE: 86.83 cent/lb (+4.2% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Giá bông tăng gây áp lực chi phí đầu vào sợi/dệt/may nếu đơn giá không kịp điều chỉnh.", "srcName": "Yahoo Finance (CT=F)", "url": "https://finance.yahoo.com/quote/CT=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": false, "aff": ["TNG", "MSH", "TCM", "STK", "GIL", "ADS", "VGT", "HTG"], "title": "Tỷ giá USD/VND: 26054.0 đồng (-0.1% phiên 04/09)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 0, "date": "2026-09-04", "srcDate": "04/09/2026 (truy xuất)", "isNew": true, "aff": ["GIL", "VGT", "ADS", "STK", "TNG", "MSH"], "title": "Nhóm dệt may phiên 04/09: 3 mã tăng / 4 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — GIL -1.3%; VGT +0.9%; ADS -0.6%; STK -0.6%; TNG -0.6%; MSH +0.5%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "379d5ab349e20121", "factor": "tariff", "impact": -1, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "India Holds Back on US Trade Pact as New Delhi Seeks Better Tariff Terms - Global Sources", "desc": "Rule-based: India Holds Back on US Trade Pact as New Delhi Seeks Better Tariff Terms Global Sources Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Global Sources", "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxNYkhJZ1ZwSGlrV20yY1BkUHVRRllEYWhnSkVrQ3Rlc0ZPUFRMeVpMT3cxMW5BR09iWDNSRlV5MTFoVnJGdUR5WTJ3bExwSkd5cWhVNThXUkQydzlhWGQ1amF6UVBENHBfOHRKcXgxLTQ5M1VzbHlPZzdnYUI0blU4WTRpa0FjT1BUcGVPazE1QkZlV2RDTEwwRWVTVWgwUTFTOWhEUWl4S0l6XzdGZGVSR3VJRG1CSUxUREZwNlN3?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "fcbadc18041d9def", "factor": "export", "impact": 1, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Hơn 170 doanh nghiệp quốc tế đến Tây Ninh: Muốn có đơn hàng, phải minh bạch chuỗi cung ứng - Một Thế Giới", "desc": "Rule-based: Hơn 170 doanh nghiệp quốc tế đến Tây Ninh: Muốn có đơn hàng, phải minh bạch chuỗi cung ứng Một Thế Giới Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Một Thế Giới", "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNSmIwNjhRdVVqc3BkNDUxMlpDcG5EZmhjNVMyb3FEQUhUamJkVVJPSEdtX21yenBrTUVKRk84VTl6aWYzSHhSVDgzWlcydDBjUEFpZkI2ZldPWkVnMXRGOGZCU3Z2cFJxRTVQQXRDZWx5Q1lsZWtxQkprR1REZG1xRVNQZngxcHBRTS0wMTZHZ3FsNVBrNEVjOFF5bHQyaUYwMmU4MzdVbVVoVVBRSk5xZUFmVXA5aUlhMml5OA?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "2f4bbdb9ade6599f", "factor": "market", "impact": 1, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Bangladesh rises to second-largest apparel exporter globally - Textile Today", "desc": "Rule-based: Bangladesh rises to second-largest apparel exporter globally Textile Today Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Textile Today", "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxOREVYT0xiYUIxRUZfWVpMU3VJU0k4UEZSekFVaEpNdDVwZndWNHB2d0JkS2FwR3hvQ1oxV0ZHaWZDSng4MzdZRXIzazNKeU9VbEs1bHFjM191djd2cVJYdnRpRnlUaGI3Q2FSVjJWNUhtOU1ac0RnTzB3Zm92VTl2ZjRLV3ZWaURWNklTRDNUZ09DOHZ4TWow?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "df858aa801d0a197", "factor": "esg", "impact": 0, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Dệt may, da giày: Vốn xanh quyết định lợi thế - Tạp chí điện tử Thương Trường", "desc": "Rule-based: Dệt may, da giày: Vốn xanh quyết định lợi thế Tạp chí điện tử Thương Trường Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Tạp chí điện tử Thương Trường", "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxQVVd6V2dxS1UxSFFwU1JTdGxzTUJBLU1nQ0xoeDBqU2pFRnk1RjVIc1N0YTlHZEtMcGlkM1o5MFMyWGpxVnVDNDdfckJTQzFWRTNXRkhaOG15clY0SUpjd0pCTE1TUXVnbzZralNpbVZ1S1lZSWZPakNxcFIzWnFsVE5SZXROeVhDQ2pELVBHQmxZZw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "d68c5d9e0cabbce3", "factor": "export", "impact": 0, "date": "2026-09-05", "srcDate": "05/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Bangladesh overtakes China again in apparel exports to US - The Daily Star", "desc": "Rule-based: Bangladesh overtakes China again in apparel exports to US The Daily Star Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "The Daily Star", "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxNQlRfREpXUnRvX1k0bE5pNWU0cmx6UmpqekxyRFd2YUVvNVhCY3pEMm5CY3VsdUtYQzNYazdiTWJIaGFLVUcxOWpJZ2E4Uk1IMW9oRlBLb21WWTN3X2hDNTdKdkRLeXgtNDA3YmZPc1FHdWFBdjd5WlBVb0JpQTFTVW5IYXVHOWlaa2tkc1pkdXNKcUF3WWJxQ3RENnI4TnRLc19iMA?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "204282912625f71e", "factor": "input", "impact": -1, "date": "2026-09-04", "srcDate": "04/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| South India cotton yarn turns soft amid falling cotton prices - Fibre2Fashion", "desc": "Rule-based: | South India cotton yarn turns soft amid falling cotton prices Fibre2Fashion Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxPZzNXaHNlaDBmQWxVbU5fNE9iN0N1dG9yNm1NUEVCQnlXWHpBUVF5X2RIMEJDMXl6dzJQUmlvNnhkMldZV240S0JYRWkydHF0aUVDVTVGUHVIRzF6X3h6cm42MzdDalZNOG9XcmlPT2lvSm1VT1RodjZReGU2dE5ObTRfVkZoYlFfSk1xRXVqTW11QWlwcHp4aVlmcE54UFV4VzFKWWhSaWdWN1J5UkNqdjFUMnllWHppRXJPWmVxdC13WkhTZWtYTXltandJdXZ2MnI4azBKbXE?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "a9dda26c0d4f5957", "factor": "input", "impact": -1, "date": "2026-09-04", "srcDate": "04/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| South India cotton yarn turns soft amid falling cotton prices - Fibre2Fashion", "desc": "Rule-based: | South India cotton yarn turns soft amid falling cotton prices Fibre2Fashion Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxNWlV6TWUtUDd5Nk1OcnJqQlRxS1VmRVlNdkt5SENaVXV3SDZIREdOYlRrMFlsN2Nlb1dDMXh1QmEyU2dFM3pqZDgxb2ZPTTRpTWFnWjhpelRuSXQ3ZXpDeVg1NUMwdGNiOC1QUm1BY2RuT0ZwSTFuMnIyM2JOVTR2d2xWVlpuSS0xUXh4UnB1aElFSHNUSHAzVmNJUnhFTVhtaGQ4TWxQWnBMOFRxYVp5ZFZoWjIxQ1hXaDd3SHVmdTJOdUxwNHhRQWFvaWxsUFQxbHlGZ0JGQThlb3c?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "f7171b4022c5f68f", "factor": "market", "impact": 1, "date": "2026-09-04", "srcDate": "04/09/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| Bangladesh vs Pakistan: What a 36% UK apparel surge really means? - Fibre2Fashion", "desc": "Rule-based: | Bangladesh vs Pakistan: What a 36% UK apparel surge really means? Fibre2Fashion Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxNX2dDUXFrdFJ6Z09rR09rZWxPbHFHYnFHZDNCTWJVR0pNT0ZzY3oxSTBwRFJtMFpHNXpmcU9tdUxUV2RyZFdaU0VaSzNqclA5S3BrZmljUHR3d1lESE9ZQ1hobm9SQVV3MmkwOENkLXFGM0NXR2QxckQzMjZFM0p1YnpRcl9LemZoMllyeWRocHdkTnJXS1BiZ0h5M0pVOEtET3lzT193LS15RDZHUTBXV3MxTUtqVHd1N2NkRVZUSElDd2RDcTI1R3YzNlZCSnhrQ0tqc3ZGWU9BZ0k?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
    ["Nguyên liệu (bông/xơ)", "Giá bông thế giới; nhập khẩu xơ; xơ tái chế", "(đầu vào) STK, ADS", "Giá bông/xơ hợp lý; nguồn cung ổn định"],
    ["Sợi (spinning)", "Giá sợi; chênh bông–sợi; cầu Trung Quốc", "STK, ADS, VGT", "Spread sợi tốt; cầu TQ phục hồi; giá xơ thấp"],
    ["Dệt – nhuộm vải", "Tự chủ vải; quy tắc xuất xứ (CPTPP/EVFTA)", "TCM (chuỗi khép kín); điểm nghẽn của ngành", "Đầu tư dệt nhuộm; đáp ứng xuất xứ 'từ sợi/vải trở đi'"],
    ["May (CMT/FOB/ODM)", "Đơn hàng; đơn giá; tỷ trọng FOB/ODM", "TNG, MSH, TCM, GIL, HTG, VGT", "Đơn hàng đầy; dịch lên FOB/ODM; năng suất cao"],
    ["Thương hiệu & phân phối", "OBM; thị trường nội địa; giá trị gia tăng", "Số ít DN có thương hiệu", "Phát triển OBM; biên cao; ít phụ thuộc gia công"],
    ["Thị trường xuất khẩu", "Mỹ/EU/Nhật/Hàn; thuế; dịch chuyển đơn", "TNG, MSH, TCM, HTG", "Thuế thấp/ổn định; đơn dịch từ TQ/Bangladesh về VN"]
  ],
  tickers: [
    ["TNG", "Đơn hàng (Decathlon, Columbia…); công suất chuyền; đơn giá", "Đơn hàng đầy; mở rộng chuyền; thị trường EU tốt", "Cầu Mỹ/EU yếu; đơn giá giảm; tồn kho cao"],
    ["MSH", "FOB/ODM; khách Mỹ (tỷ trọng lớn); nhà máy mới (SH10)", "Đơn FOB tăng; khách Mỹ ổn; nhà máy mới chạy đủ", "Thuế đối ứng Mỹ; mất khách lớn; giá bông tăng"],
    ["TCM", "Chuỗi khép kín sợi–dệt–may; khách Hàn (E-Land); ODM", "Tự chủ chuỗi; đơn ODM biên cao; Hàn/Nhật ổn", "Đơn hàng yếu; lỗ mảng sợi; cạnh tranh khu vực"],
    ["STK", "Sợi tái chế (recycled); giá xơ; cầu TQ; dự án Unitex", "Giá sợi tốt; premium recycled; Unitex vận hành", "Cầu sợi yếu; cạnh tranh sợi TQ; giá dầu (xơ) cao"],
    ["GIL", "May + KCN (Gilimex Phú Bài); hậu vụ kiện Amazon", "KCN cho thuê tốt; đơn hàng may hồi phục", "Mất đơn khách lớn; KCN chậm lấp đầy"],
    ["ADS", "Sợi + khăn (Damsan); giá sợi; BĐS KCN", "Giá sợi tốt; mảng khăn ổn; KCN đóng góp", "Cầu sợi yếu; chi phí đầu vào; đòn bẩy"],
    ["VGT", "Tổng công ty (sợi + may); chu kỳ ngành; hợp nhất", "Ngành hồi phục; mảng sợi có lãi trở lại", "Sợi lỗ; cầu yếu; bộ máy lớn kém linh hoạt"],
    ["HTG", "May FOB (Hòa Thọ); khách ổn định; cổ tức cao", "Đơn hàng đầy; biên ổn định; cổ tức tiền mặt", "Cầu yếu; chi phí lao động tăng; tỷ giá"]
  ],
  sources: [
    ["Hiệp hội Dệt May VN (VITAS)", "https://vietnamtextile.org.vn/", "Kim ngạch, đơn hàng, triển vọng ngành"],
    ["Tổng cục Hải quan", "https://www.customs.gov.vn/", "Kim ngạch xuất khẩu dệt may theo tháng"],
    ["Vinatex", "https://vinatex.com.vn/", "Tin ngành, sản xuất, giá sợi"],
    ["Giá bông – Trading Economics", "https://tradingeconomics.com/commodity/cotton", "Giá bông thế giới (đầu vào sợi)"],
    ["OTEXA (Mỹ)", "https://otexa.trade.gov/", "Số liệu nhập khẩu dệt may vào Mỹ theo nước"],
    ["Bộ Công Thương", "https://moit.gov.vn/", "Chính sách thương mại, FTA, phòng vệ thương mại"],
    ["TNG IR", "https://tng.vn/", "Doanh thu theo tháng, đơn hàng, công suất"],
    ["Dệt may Thành Công (TCM)", "https://www.thanhcongtextile.com/", "IR: KQKD tháng, cơ cấu đơn hàng"]
  ]
};
