// ====== DỮ LIỆU NGÀNH DỆT MAY — task "quet-nganh-det-may" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.detmay = {
  id: "detmay",
  name: "Dệt may",
  icon: "🧵",
  order: 4,
  scope: "TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG",
  subtitle: "Sentiment ngành dệt may VN theo chuỗi giá trị — đơn hàng & xuất khẩu, thuế & thương mại, nguyên liệu (bông/sợi), tỷ giá, lao động, ESG & xanh hóa, tài chính DN, dòng tiền. Phạm vi: TNG, MSH, TCM, STK, GIL, ADS, VGT, HTG. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-08-10T09:12:45+07:00",
  factors: {
    export: "Đơn hàng & xuất khẩu", tariff: "Thuế & thương mại", input: "Nguyên liệu (bông/sợi)",
    fx: "Tỷ giá", labor: "Lao động & chi phí", esg: "ESG & xanh hóa",
    finance: "Tài chính DN", market: "Thị trường & dòng tiền"
  },
  sentiment: {
    score: 0, date: "2026-08-10",
    reason: "Tự động tổng hợp từ 8 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Dệt may vượt 27 tỷ USD sau 7 tháng, động lực tăng trưởng đang dịch chuyển - thuonghieucongluan.com.vn (thuonghieucongluan.com.vn, 10/08/2026); Xuất khẩu dệt may 7 tháng đạt trên 27 tỷ USD, duy trì đà tăng trưởng - Vietnam+ (VietnamPlus) (Vietnam+ (VietnamPlus), 09/08/2026). Tiêu cực: US tariffs raise concern across Türkiye’s textile and apparel sector - Textile Today (Textile Today, 09/08/2026); US has refunded about $100bn in Trump tariffs - The Daily Star (The Daily Star, 08/08/2026). Có 4 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    {factor:"finance", impact:1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["HTG","VGT"], title:"Dệt may Hòa Thọ (HTG): XK nửa đầu năm 2026 ~148,5 triệu USD (+14%), doanh thu hợp nhất 2.893 tỷ (+9%), lãi riêng 224,3 tỷ (đạt 56% KH năm)", desc:"Ý nghĩa đầu tư: HTG (mảng may FOB, thuộc VGT) duy trì đà tăng trưởng 2 con số bất chấp thị trường biến động — green flag cho KQKD 6T; cổ tức tiền mặt cao là điểm cộng. Theo dõi đơn hàng nửa cuối năm và rủi ro thị trường Mỹ.", srcName:"Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"export", impact:-1, date:"2026-06-28", srcDate:"28/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"VITAS: XK dệt may 5T2026 ~17,81 tỷ USD (+0,6%) — may mặc 13,72 tỷ GIẢM 1,5%; xơ sợi 1,90 tỷ (+9,6%), vải +6,9%", desc:"Ý nghĩa đầu tư: Phân hóa rõ — mảng MAY mặc (TNG, MSH, GIL, HTG) suy yếu cầu, áp lực cho mục tiêu cả năm 48–49 tỷ USD; mảng SỢI/xơ (STK, ADS, VGT) ngược dòng tăng tốt. Ưu tiên mã có tỷ trọng sợi/đơn giá tốt.", srcName:"VITAS / Báo Đầu tư", url:"https://baodautu.vn/det-may-hoa-tho-xuat-khau-nua-dau-nam-2026-xap-xi-149-trieu-usd-d629575.html"},
    {factor:"input", impact:-1, date:"2026-06-26", srcDate:"26/06/2026 (truy xuất)", isNew:true, aff:["TCM","STK","ADS","VGT"], title:"Giá bông thế giới (ICE) ~78 US cent/lb, tăng ~18% từ đầu năm trên kỳ vọng nguồn cung toàn cầu thắt chặt", desc:"Ý nghĩa đầu tư: Bông neo cao đẩy chi phí đầu vào mảng may/dệt (TCM) và chi phí bông cho kéo sợi; có thể hỗ trợ giá bán sợi nhưng bóp spread bông–sợi nếu cầu yếu (STK, ADS, VGT). Theo dõi chênh bông–sợi.", srcName:"Trading Economics – Cotton", url:"https://tradingeconomics.com/commodity/cotton"},
    {factor:"fx", impact:1, date:"2026-06-17", srcDate:"17/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","STK","ADS","VGT"], title:"Tỷ giá USD/VND căng: tỷ giá trung tâm 25.165 (16/6), NHTM đồng loạt bán USD kịch trần ~26.433", desc:"Ý nghĩa đầu tư: USD mạnh hỗ trợ doanh thu/biên quy đổi cho nhóm xuất khẩu dệt may (đa số doanh thu USD, chi phí VND) — tích cực cho TNG, MSH, HTG, STK. Lưu ý DN vay USD chịu áp lực chi phí tài chính.", srcName:"Thanh Niên", url:"https://thanhnien.vn/gia-usd-hom-nay-1662026-do-tu-do-bat-tang-18526061608200601.htm"},
    {factor:"finance", impact:1, date:"2026-06-13", srcDate:"13/06/2026", isNew:true, aff:["VGT"], title:"Tập đoàn Dệt May Việt Nam (VGT/Vinatex) ước lãi ~763 tỷ đồng 6T2026 (+14%); đơn sợi đầy đến hết T7, may đến T8–9, song đơn hàng đang chậm lại chờ thuế Mỹ", desc:"Ý nghĩa đầu tư: KQKD hợp nhất 6T tích cực cho VGT, nhưng ban lãnh đạo cảnh báo đơn hàng chững lại — lợi nhuận tốt là quá khứ, biến số là đơn quý IV. Theo dõi lấp đầy chuyền và tín hiệu thuế quan.", srcName:"CafeF", url:"https://cafef.vn/tap-doan-det-may-viet-nam-uoc-lai-763-ty-dong-tang-14-trong-6-thang-dau-nam-don-hang-dang-cham-lai-cho-cau-chuyen-thue-quan-cua-my-188260613013603581.chn"},
    {factor:"tariff", impact:-1, date:"2026-06-12", srcDate:"12/06/2026", isNew:true, aff:["TNG","MSH","TCM","HTG","GIL","VGT"], title:"ALERT — Đơn hàng quý IV khan hiếm: khách nhập khẩu 'nghe ngóng' chờ thuế đối ứng song phương Mỹ (sau 24/7), cộng chi phí vận tải biển +30–40% do xung đột Trung Đông", desc:"Ý nghĩa đầu tư: Rủi ro thiếu đơn cuối năm là tâm điểm — nhạy nhất với MSH (tỷ trọng khách Mỹ lớn); cửa sổ thuế tạm 10% hết hạn 24/7 là mốc quyết định dịch chuyển đơn TQ→VN. Quan sát mức thuế thực tế của VN so Indonesia/Campuchia/Bangladesh.", srcName:"Dân trí / Vietstock", url:"https://dantri.com.vn/kinh-doanh/det-may-viet-nam-doi-mat-ap-luc-kep-tu-thue-quan-va-xung-dot-trung-dong-20260612173236317.htm"}
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "input", "impact": 0, "date": "2026-08-07", "srcDate": "07/08/2026 (truy xuất)", "isNew": false, "aff": ["TCM", "STK", "ADS", "VGT", "TNG", "MSH"], "title": "Bông ICE: 82.61 cent/lb (+0.8% phiên 07/08)", "desc": "Ý nghĩa đầu tư: Giá bông đi ngang, tác động chi phí ngắn hạn thấp.", "srcName": "Yahoo Finance (CT=F)", "url": "https://finance.yahoo.com/quote/CT=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-08-07", "srcDate": "07/08/2026 (truy xuất)", "isNew": false, "aff": ["TNG", "MSH", "TCM", "STK", "GIL", "ADS", "VGT", "HTG"], "title": "Tỷ giá USD/VND: 26234.0 đồng (-0.1% phiên 07/08)", "desc": "Ý nghĩa đầu tư: Tỷ giá ổn định, ít tạo tín hiệu mới.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 1, "date": "2026-08-07", "srcDate": "07/08/2026 (truy xuất)", "isNew": true, "aff": ["VGT", "GIL", "STK", "ADS", "HTG", "TNG"], "title": "Nhóm dệt may phiên 07/08: 4 mã tăng / 1 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — VGT +3.6%; GIL -2.5%; STK +1.2%; ADS +0.7%; HTG +0.3%; TNG +0.0%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "4060b17b04c2290d", "factor": "export", "impact": 1, "date": "2026-08-10", "srcDate": "10/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Dệt may vượt 27 tỷ USD sau 7 tháng, động lực tăng trưởng đang dịch chuyển - thuonghieucongluan.com.vn", "desc": "Rule-based: Dệt may vượt 27 tỷ USD sau 7 tháng, động lực tăng trưởng đang dịch chuyển thuonghieucongluan.com.vn Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "thuonghieucongluan.com.vn", "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxNMVJHeHdmMlhQVjR4VW9FelBiUTRUS1l4YVZsc1IxOXJvTS1aSjI4OG53NEhSVEFlUkRkOHRMMGVUUXQyYjJYWTRfdXg0UEdOV1Eya1FZTUFzVVJnd2dtV0ZjaWd2Y19tUm1FWmc5LVVPMFRwOTZSSFBPZkhDNnVyaFlHUmhhX3pjVGJPamlMWkU4anBoeHMwTkxQZm8wZ3pSOFFvdFZyUnVIMzFYVTVCbEhzekpOdENLeVdZ?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "67c7b89cc369ecbf", "factor": "export", "impact": 1, "date": "2026-08-09", "srcDate": "09/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Xuất khẩu dệt may 7 tháng đạt trên 27 tỷ USD, duy trì đà tăng trưởng - Vietnam+ (VietnamPlus)", "desc": "Rule-based: Xuất khẩu dệt may 7 tháng đạt trên 27 tỷ USD, duy trì đà tăng trưởng Vietnam+ (VietnamPlus) Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Vietnam+ (VietnamPlus)", "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNTWgySzBtM0liNE56RzUwN1FBQU1ydnRQdjJPWERFZGVuVEY3emotNHFVV1JfQXcxamJrbjZ3MmQyblRFQWRaa3FBZWpVMVhCZDE3STBwTElWVlBlVUZPb3Z1dG84ZjdRcFo5RFZ5NEl4RTdqRl9DTXZhM00xcmoxNEpuYk1RZDJDQmdtWVBEM29tN21ESUdfc3V1OFF3Z0l3R2VRb0pIejFNaElQOWdz?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "11655ce5ec9689c2", "factor": "tariff", "impact": -1, "date": "2026-08-09", "srcDate": "09/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "US tariffs raise concern across Türkiye’s textile and apparel sector - Textile Today", "desc": "Rule-based: US tariffs raise concern across Türkiye’s textile and apparel sector Textile Today Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Textile Today", "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxORW14OEJGcEdCZ2xNWEROdkJJT0lZWEFkbnN6N25SandIbUhUSy1OUV95MWRhX0wxYktoRm1DMWFrczAzNjhKU0IwUXZld2dLb25HSE91b0R6M0RXTmYzeC1OU1FJSVJJM1l1T1ZydTlKc3ZoOS1jN3ZKWUN1YjY2TjB3eWxQNGpNUWl5WW9mRmI3Yk1jeUFOSlNCVld1NnFE?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "a44b0f6f8308389b", "factor": "export", "impact": 0, "date": "2026-08-09", "srcDate": "09/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "US tariff threat rises as India's apparel industry gains ground in UK, EU - Business Standard", "desc": "Rule-based: US tariff threat rises as India's apparel industry gains ground in UK, EU Business Standard Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Business Standard", "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQanFoM0xoeDhtQW9OdE9RRERfb0JXTVlLY1g5cTRwX0M3VzhEZ0RHZEFkcEFnM2JmbHdycWtCMWJ1cjZfVlZHUFpNX3RmS2ZidFZDakE0V1lHeURwVU1hcTVLTTVXMlNEcTRjVmNWcXBTbndacTkzX0xKSENERGhNaXI3cjk1MFVxT3hPNmtXYndmQXhEdGx2YlhGczdJSlI3UU53UVhnYnlNekx0R21qYdIBtgFBVV95cUxPTkRwbGRCS19WWTF0NDEySTlGeFQyYmNTSENNVUU5dWhIenFJRC1tR21FZHU5VDhhTGFkUlFzdi1pQk5Fcjdub2otZDctVGdGWkhaNm9mT1h6N0lfX3M0WGd3RFlnelZFeElLTGpTSDVTR0EwLVQyT0RYWWlkZkxHdDVkbFFKZU9SSzlaUzY1SlVIU3NzODNZNUJqR3ZtRzQ2Nl9WakRpRzRFNFBWR3hEY3BrQ2VDQQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "fea745fcadb7aa45", "factor": "market", "impact": 0, "date": "2026-08-09", "srcDate": "09/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Công nhân ngành Dệt May đua tài, làm chủ kỹ năng nghề - Laodong.vn", "desc": "Rule-based: Công nhân ngành Dệt May đua tài, làm chủ kỹ năng nghề Laodong.vn Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Laodong.vn", "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNOUxMZ3hTNGYwV3FxcXdkVFV6ZmJMWDh5QUg5T0d1N1BXdnh4dU1DR01BQlgyYU1xeUZGYjNEaHdtNmVYSVgxLVZaNHBzWjh6Q2xIcHQ0QmdfYzRPY0luZkN5UlR3MzZMeG1QNW5XVGxwMld0Y3NsWDdOWHJ6Z0RJUzBvSFl4NWhQYXBnVXcxdHVQMWo4WWVhcw?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "ee9600fe157cc322", "factor": "export", "impact": 0, "date": "2026-08-09", "srcDate": "09/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "Bangladeshi apparel gains advantage as China, India exports to US drop - Dhaka Tribune", "desc": "Rule-based: Bangladeshi apparel gains advantage as China, India exports to US drop Dhaka Tribune Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Dhaka Tribune", "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQQTlPTFA0Wk9Vdmc3Z0NaREJ1alF5aEtzcUdQYTJYdldLSm5HaGZhU3NfTkVFVzE4TGt1cFZhcEgxZkhYYUFsQzFRY0tQdDd4Q3BCdXlmQ3h1UGV2OXdWNUs3M1UxNGRiNHA5dVduazBIVTd4OXdZeGlnRGtFRGFKTjJ2MUpKQjBac184NExGZVJiM0ZVeWFlQ9IBmAFBVV95cUxQQTlPTFA0Wk9Vdmc3Z0NaREJ1alF5aEtzcUdQYTJYdldLSm5HaGZhU3NfTkVFVzE4TGt1cFZhcEgxZkhYYUFsQzFRY0tQdDd4Q3BCdXlmQ3h1UGV2OXdWNUs3M1UxNGRiNHA5dVduazBIVTd4OXdZeGlnRGtFRGFKTjJ2MUpKQjBac184NExGZVJiM0ZVeWFlQw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "6fbde4eee9698f13", "factor": "tariff", "impact": -1, "date": "2026-08-08", "srcDate": "08/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "US has refunded about $100bn in Trump tariffs - The Daily Star", "desc": "Rule-based: US has refunded about $100bn in Trump tariffs The Daily Star Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "The Daily Star", "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxON0pLeUg2cnRuMmVtOU9sSXpRbkt3UE9OcjRpX0FXNHZ0RHBrbEZ6eDl5YUpCUUtNN1JUVzQ2eWo3YVBPZG5vVGQ5TjFBTHJDOTN0NWtTanZjbkdNbE1XaXpab0NvM0Foc2lTakxFU3ptVnFjRkxKeGlOdXlDNVJqeVlyMy1NNDlHUVNPdGNwcllEdkJ4Rnc4?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "59113111036aafe0", "factor": "input", "impact": 0, "date": "2026-08-08", "srcDate": "08/08/2026", "isNew": true, "aff": ["TNG", "MSH", "TCM", "STK"], "title": "| South India's cotton yarn stable, faces higher cost but slower demand - Fibre2Fashion", "desc": "Rule-based: | South India's cotton yarn stable, faces higher cost but slower demand Fibre2Fashion Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Fibre2Fashion", "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxOS2FjUUYxSF8yNWRYR1JPb2ltcXdyWFRFYWp4U29FbU5oOGU1VGlUUGItTjdKaFktUm1hT2thQW5SVDJLU2ZkbnlWcXAyQndEeU1lTW5UcmgyX0dHNzlrU01GVVhqZEIwQnBjUGliN01wV2JteFpJeExVWWF5THdwNUxLcmM3WXFvQzhXMFZiLVdVY3dsNHVzdXNJXzZsUXhOcERNWW90aEdlZVVwcks3T08tanl5Q3k2eG41WDJQRmpZcEpqN0pBNmRZWUwwdHlObG81UE9B?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
    ["Nguyên liệu (bông/xơ)", "Giá bông thế giới; nhập khẩu xơ; xơ tái chế", "(đầu vào) STK, ADS", "Giá bông/xơ hợp lý; nguồn cung ổn định"],
    ["Sợi (spinning)", "Giá sợi; chênh bông–sợi; cầu Trung Quốc", "STK, ADS, VGT", "Spread sợi tốt; cầu TQ phục hồi; giá xơ thấp"],
    ["Dệt – nhuộm vải", "Tự chủ vải; quy tắc xuất xứ (CPTPP/EVFTA)", "TCM (chuỗi khép kín); điểm nghẽn của ngành", "Đầu tư dệt nhuộm; đáp ứng xuất xứ 'từ sợi/vải trở đi'"],
    ["May (CMT/FOB/ODM)", "Đơn hàng; đơn giá; tỷ trọng FOB/ODM", "TNG, MSH, TCM, GIL, HTG, VGT", "Đơn hàng đầy; dịch lên FOB/ODM; năng suất cao"],
    ["Thương hiệu & phân phối", "OBM; thị trường nội địa; giá trị gia tăng", "Số ít DN có thương hiệu", "Phát triển OBM; biên cao; ít phụ thuộc gia công"],
    ["Thị trường xuất khẩu", "Mỹ/EU/Nhật/Hàn; thuế; dịch chuyển đơn", "TNG, MSH, TCM, HTG", "Thuế thấp/ổn định; đơn dịch từ TQ/Bangladesh về VN"]
  ],
  tickers: [
    ["TNG", "Đơn hàng (Decathlon, Columbia…); công suất chuyền; đơn giá", "Đơn hàng đầy; mở rộng chuyền; thị trường EU tốt", "Cầu Mỹ/EU yếu; đơn giá giảm; tồn kho cao"],
    ["MSH", "FOB/ODM; khách Mỹ (tỷ trọng lớn); nhà máy mới (SH10)", "Đơn FOB tăng; khách Mỹ ổn; nhà máy mới chạy đủ", "Thuế đối ứng Mỹ; mất khách lớn; giá bông tăng"],
    ["TCM", "Chuỗi khép kín sợi–dệt–may; khách Hàn (E-Land); ODM", "Tự chủ chuỗi; đơn ODM biên cao; Hàn/Nhật ổn", "Đơn hàng yếu; lỗ mảng sợi; cạnh tranh khu vực"],
    ["STK", "Sợi tái chế (recycled); giá xơ; cầu TQ; dự án Unitex", "Giá sợi tốt; premium recycled; Unitex vận hành", "Cầu sợi yếu; cạnh tranh sợi TQ; giá dầu (xơ) cao"],
    ["GIL", "May + KCN (Gilimex Phú Bài); hậu vụ kiện Amazon", "KCN cho thuê tốt; đơn hàng may hồi phục", "Mất đơn khách lớn; KCN chậm lấp đầy"],
    ["ADS", "Sợi + khăn (Damsan); giá sợi; BĐS KCN", "Giá sợi tốt; mảng khăn ổn; KCN đóng góp", "Cầu sợi yếu; chi phí đầu vào; đòn bẩy"],
    ["VGT", "Tổng công ty (sợi + may); chu kỳ ngành; hợp nhất", "Ngành hồi phục; mảng sợi có lãi trở lại", "Sợi lỗ; cầu yếu; bộ máy lớn kém linh hoạt"],
    ["HTG", "May FOB (Hòa Thọ); khách ổn định; cổ tức cao", "Đơn hàng đầy; biên ổn định; cổ tức tiền mặt", "Cầu yếu; chi phí lao động tăng; tỷ giá"]
  ],
  sources: [
    ["Hiệp hội Dệt May VN (VITAS)", "https://vietnamtextile.org.vn/", "Kim ngạch, đơn hàng, triển vọng ngành"],
    ["Tổng cục Hải quan", "https://www.customs.gov.vn/", "Kim ngạch xuất khẩu dệt may theo tháng"],
    ["Vinatex", "https://vinatex.com.vn/", "Tin ngành, sản xuất, giá sợi"],
    ["Giá bông – Trading Economics", "https://tradingeconomics.com/commodity/cotton", "Giá bông thế giới (đầu vào sợi)"],
    ["OTEXA (Mỹ)", "https://otexa.trade.gov/", "Số liệu nhập khẩu dệt may vào Mỹ theo nước"],
    ["Bộ Công Thương", "https://moit.gov.vn/", "Chính sách thương mại, FTA, phòng vệ thương mại"],
    ["TNG IR", "https://tng.vn/", "Doanh thu theo tháng, đơn hàng, công suất"],
    ["Dệt may Thành Công (TCM)", "https://www.thanhcongtextile.com/", "IR: KQKD tháng, cơ cấu đơn hàng"]
  ]
};
