// ====== DỮ LIỆU NGÀNH HÀNG HÓA (đường, sữa, sắn, ngô) — task "quet-nganh-hang-hoa" cập nhật file này mỗi sáng ======
// Chỉ sửa: lastUpdated, sentiment, items. GIỮ NGUYÊN: factors, valuechain, tickers, sources, meta.
window.SECTORS = window.SECTORS || {};
window.SECTORS.hanghoa = {
  id: "hanghoa",
  name: "Hàng hóa",
  icon: "🌾",
  order: 5,
  scope: "SBT, SLS, LSS, QNS, VNM, IDP, MCM, DBC, BAF, HAG",
  subtitle: "Sentiment nhóm hàng hóa nông nghiệp VN (đường, sữa, sắn, ngô/TĂCN) theo giá hàng hóa & chuỗi giá trị — giá đường, giá sữa bột, ngô & thức ăn chăn nuôi, sắn, chi phí đầu vào, tỷ giá, chính sách & phòng vệ TM, tài chính DN. Phạm vi: SBT, SLS, LSS, QNS, VNM, IDP, MCM, DBC, BAF, HAG. Chỉ tin có nguồn cập nhật ≤ 30 ngày.",
  lastUpdated: "2026-08-31T11:55:26+07:00",
  factors: {
    sugar: "Đường", milk: "Sữa", corn: "Ngô & TĂCN", cassava: "Sắn",
    input: "Chi phí đầu vào & logistics", fx: "Tỷ giá & nhập khẩu",
    policy: "Chính sách & phòng vệ TM", finance: "Tài chính DN", market: "Thị trường & dòng tiền"
  },
  sentiment: {
    score: 1, date: "2026-08-31",
    reason: "Tự động tổng hợp từ 5 tín hiệu mới nhất trong 3 ngày gần nhất. Tích cực: Statsguru: Sugar tastes bitter as retail prices surge amid tighter supply - Business Standard (Business Standard, 31/08/2026); Global Sugar Prices Hit One-Year High: What’s Driving the Rise? - Caspian Post (Caspian Post, 29/08/2026). Có 3 tín hiệu trung tính/chờ kiểm chứng. Đây là chấm điểm rule-based từ tin/số liệu tự động; mở nguồn để kiểm chứng trước khi ra quyết định."
  },
  items: [
    { factor: "corn", impact: -1, date: "2026-06-29", srcDate: "29/06/2026 (truy xuất)", isNew: true, aff: ["DBC","BAF","HAG"], title: "Giá heo hơi tiếp tục giảm: miền Bắc 67–68k, miền Trung 62–67k, miền Nam 61–63k đ/kg", desc: "Ý nghĩa đầu tư: Heo hơi hạ nhiệt và giảm tuần thứ hai liên tiếp ép biên đầu ra của DBC/BAF/HAG; vùng giá 60–68k vẫn có lãi nhưng xu hướng giảm là tín hiệu thận trọng cho lợi nhuận quý 2–3.", srcName: "Thanh Niên", url: "https://thanhnien.vn/gia-heo-hoi-hom-nay-2962026-lai-tiep-tuc-giam-185260629081524846.htm" },
    { factor: "corn", impact: -1, date: "2026-06-25", srcDate: "25/06/2026", isNew: true, aff: ["DBC","BAF","HAG"], title: "ALERT: Bùng phát dịch tả heo châu Phi (ASF) ở Đồng Nai, tiêu hủy đàn ~1.942 con; báo động đỏ miền Bắc", desc: "Ý nghĩa đầu tư: Ổ dịch ASF mới + khuyến cáo tạm dừng tái đàn là rủi ro hai mặt cho DBC/BAF: tăng rủi ro thiệt hại đàn ngắn hạn, nhưng nếu lan rộng sẽ giảm cung và đỡ giá heo cuối năm. Theo dõi sát mức độ lan và tiến độ tái đàn.", srcName: "Một Thế Giới", url: "https://motthegioi.vn/gia-heo-hoi-mien-bac-asf/" },
    { factor: "corn", impact: 0, date: "2026-06-24", srcDate: "24/06/2026 (truy xuất)", isNew: true, aff: ["DBC","BAF","HAG"], title: "Giá ngô nhập ~248,8 USD/tấn (−3,6%); khô đậu tương ~475,9 USD/tấn (+5,2%)", desc: "Ý nghĩa đầu tư: Ngô rẻ hơn hỗ trợ giá thành thức ăn chăn nuôi nhưng khô đậu tăng bù trừ; nguồn cung khô đậu về nhiều tháng 6–7 có thể hạ nhiệt giá → trung tính với biên TĂCN của DBC/BAF.", srcName: "Nhà Bè Agri", url: "https://nhabeagri.com/gia-nong-san/gia-ngo-moi-nhat/" },
    { factor: "fx", impact: -1, date: "2026-06-17", srcDate: "17/06/2026", isNew: true, aff: ["VNM","IDP","MCM","DBC","BAF"], title: "USD/VND căng: tỷ giá trung tâm 25.165, NHTM bán USD kịch trần 26.433 đồng", desc: "Ý nghĩa đầu tư: USD mạnh, giá bán kịch trần làm tăng chi phí nhập bột sữa, ngô và khô đậu (tính bằng USD) → bất lợi biên cho nhóm nhập nguyên liệu VNM/IDP/MCM/DBC/BAF, bù trừ một phần lợi ích giá hàng hóa thế giới giảm.", srcName: "Thanh Niên", url: "https://thanhnien.vn/gia-usd-hom-nay-1662026-do-tu-do-bat-tang-18526061608200601.htm" },
    { factor: "sugar", impact: -1, date: "2026-06-12", srcDate: "12/06/2026", isNew: true, aff: ["SBT","SLS","LSS","QNS"], title: "Đường lậu, không rõ nguồn gốc vẫn tràn lan; VSSA dự báo dư cung kéo dài", desc: "Ý nghĩa đầu tư: Đường nhập lậu Campuchia/Lào (~16.300 đ/kg) cạnh tranh trực tiếp, dư cung tiếp diễn → rủi ro tồn kho và giá bán thấp cho doanh nghiệp đường, tiêu cực ngắn hạn cho SBT/LSS/SLS/QNS.", srcName: "Vietstock", url: "https://vietstock.vn/2026/06/duong-lau-khong-ro-nguon-goc-van-tran-lan-118-1453545.htm" },
    { factor: "cassava", impact: 0, date: "2026-06-12", srcDate: "12/06/2026", isNew: true, aff: ["HAG"], title: "Giá tinh bột sắn xuất khẩu neo cao (~515–540 USD/tấn) nhưng Trung Quốc giảm mua", desc: "Ý nghĩa đầu tư: Giá tinh bột sắn neo cao gần gấp đôi cùng kỳ hỗ trợ doanh nghiệp sắn, song cầu Trung Quốc giảm do bớt dùng cho ethanol là rủi ro đầu ra; tác động gián tiếp, nhẹ tới HAG và DN tinh bột.", srcName: "Vietnam.vn", url: "https://www.vietnam.vn/en/trung-quoc-cham-mua-hang-gia-mot-loai-tinh-bot-cua-viet-nam-giam-sau/" },
    { factor: "sugar", impact: -1, date: "2026-06-05", srcDate: "05/06/2026", isNew: true, aff: ["SBT","SLS","LSS","QNS"], title: "Giá đường nội địa chạm đáy 3 năm dù giá đường thế giới gần đỉnh 5 tháng", desc: "Ý nghĩa đầu tư: Đường kính trắng nội địa chỉ 15.800–16.600 đ/kg do dư cung + đường lậu, ép biên mảng đường của SBT/SLS/LSS/QNS bất chấp giá #11 thế giới cao; chưa thấy catalyst tăng giá nội địa rõ ràng.", srcName: "Dân trí", url: "https://dantri.com.vn/kinh-doanh/duong-lau-bua-vay-nganh-mia-duong-lao-dao-vi-gia-cham-day-20260605091744497.htm" },
    { factor: "milk", impact: 1, date: "2026-06-02", srcDate: "02/06/2026 (truy xuất)", isNew: true, aff: ["VNM","IDP","MCM"], title: "Đấu giá GDT: WMP −3,1% về 3.589 USD/tấn, SMP −3,6%, chỉ số chung −2,8%", desc: "Ý nghĩa đầu tư: Giá bột sữa nhập (WMP/SMP) giảm do dư cung toàn cầu = hạ giá vốn đầu vào, hỗ trợ biên gộp cho VNM/IDP/MCM; tuy nhiên cần bù trừ với tỷ giá USD/VND cao và sức mua trong nước còn yếu (Q1 giảm ~3,7%).", srcName: "GlobalDairyTrade / eDairyNews", url: "https://en.edairynews.com/supply-glut-slashes-global-dairy-auction-prices/" }
  ],
  // <PY-ITEMS> khối này do quant_update.py tự ghi mỗi sáng — ĐỪNG sửa tay
  itemsPY: [
    {"factor": "sugar", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": true, "aff": ["SBT", "SLS", "LSS", "QNS"], "title": "Đường thô ICE #11: 17.56 cent/lb (-3.5% phiên 28/08)", "desc": "Ý nghĩa đầu tư: Giá đường thế giới giảm tạo áp lực tham chiếu lên giá bán và tồn kho của SBT/SLS/LSS/QNS.", "srcName": "Yahoo Finance (SB=F)", "url": "https://finance.yahoo.com/quote/SB=F", "src": "py"},
    {"factor": "corn", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": true, "aff": ["DBC", "BAF", "HAG"], "title": "Ngô CBOT: 536.2 cent/bushel (+5.1% phiên 28/08)", "desc": "Ý nghĩa đầu tư: Giá ngô tăng đẩy chi phí thức ăn chăn nuôi, bất lợi biên cho DBC/BAF/HAG.", "srcName": "Yahoo Finance (ZC=F)", "url": "https://finance.yahoo.com/quote/ZC=F", "src": "py"},
    {"factor": "corn", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": true, "aff": ["DBC", "BAF"], "title": "Khô đậu tương CBOT: 348.8 USD/tấn ngắn (+5.6% phiên 28/08)", "desc": "Ý nghĩa đầu tư: Khô đậu tăng đẩy chi phí đạm trong thức ăn chăn nuôi, bất lợi biên DBC/BAF.", "srcName": "Yahoo Finance (ZM=F)", "url": "https://finance.yahoo.com/quote/ZM=F", "src": "py"},
    {"factor": "fx", "impact": 0, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": false, "aff": ["VNM", "IDP", "MCM", "DBC", "BAF"], "title": "Tỷ giá USD/VND: 26070.0 đồng (-0.1% phiên 28/08)", "desc": "Ý nghĩa đầu tư: Tỷ giá USD/VND ổn định, ít tác động chi phí nhập khẩu.", "srcName": "Yahoo Finance (VND=X)", "url": "https://finance.yahoo.com/quote/VND=X", "src": "py"},
    {"factor": "market", "impact": 1, "date": "2026-08-28", "srcDate": "28/08/2026 (truy xuất)", "isNew": true, "aff": ["SLS", "IDP", "QNS", "LSS", "BAF", "SBT"], "title": "Nhóm hàng hóa phiên 28/08: 6 mã tăng / 1 mã giảm", "desc": "Ý nghĩa đầu tư: Diễn biến giá nhóm — SLS +4.5%; IDP +3.5%; QNS +1.1%; LSS +1.0%; BAF +0.9%; SBT +0.4%. Dùng để soi dòng tiền và xác nhận/tương phản với luận điểm cơ bản.", "srcName": "vnstock (VCI)", "url": "https://www.hsx.vn/", "src": "py"}
  ],
  // </PY-ITEMS>
  // <NEWS-ITEMS> khối này do news_update.py tự ghi — ĐỪNG sửa tay
  itemsNews: [
    {"id": "4e0925fd2ba77fa8", "factor": "sugar", "impact": 1, "date": "2026-08-31", "srcDate": "31/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Statsguru: Sugar tastes bitter as retail prices surge amid tighter supply - Business Standard", "desc": "Rule-based: Statsguru: Sugar tastes bitter as retail prices surge amid tighter supply Business Standard Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Business Standard", "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxPeUVKcWl6WmFFUTJLSjI5aGNwOEtrR1pQMHhZLWp4VEhOTnlkcWY2cWJfazdCZFQxREV6SnZ2TGhORkEyRFNQXzF6clAwcG9QaWZnYlFWUTNjRkg5X2RZdVA1U2FqRkJpdjAxLXZVUTdBN05OdVEtbmRXd2J1dVZCSzdKZUdPcmhpTjhZUGdQSWtGZ3RlS0xjc0JvUmZMQWNQeXp3eUh2RE9sbWxvOWRwZlM3bFo0eW1udG5Yc21Xd0VkUFdOY3FlXzRPdFM3MWREVWx3b2ktU0V1RFFN0gHcAUFVX3lxTE95RUpxaXpaYUVRMktKMjloY3A4S2tHWlAweFktanhUSE5OeWRxZjZxYl9rN0JkVDFERXpKdnZMaE5GQTJEU1BfMXpyUDBwb1BpZmdiUVZRM2NGSDlfZFl1UDVTYWpGQml2MDEtdlVRN0E3Tk51US1uZFd3YnV1VkJLN0plR09yaGlOOFlQZ1BJa0ZndGVLTGNzQm9SZkxBY1B5end5SHZET2xtbG85ZHBmUzdsWjR5bW50blhzbVd3RWRQV05jcWVfNE90UzcxZERVbHdvaS1TRXVEUU0?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "2307aa057ad81d92", "factor": "sugar", "impact": 0, "date": "2026-08-30", "srcDate": "30/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Vietnam's export triumph: How a small nation beat China and India to become America's top trade partner - inkl", "desc": "Rule-based: Vietnam's export triumph: How a small nation beat China and India to become America's top trade partner inkl Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "inkl", "url": "https://news.google.com/rss/articles/CBMixAFBVV95cUxNeF95UFlMZWdzbjdoOXZScVdXd2FtUzR3bXV1dlZPcU16dzNJazlFOWdyQ3lBZnM1UTVpamRPTVBWbEFzbHlrakROaU9nLUF1VnlwaThvMDh5UUJfdkpyaG9LMml0NGJqRnkyVm41NU1wZDNMLUR3ZndHSVhmNDgtenU2UmhGaGw3MGhrNHF0di1iZ2NHenRrbDlSNnJSMkVnRTBlWkdScHJaZzV2c3JkZGtYUnJNSkp0LXZNRVZjenZOZmgw?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "d7add4e8eaea0dfe", "factor": "sugar", "impact": 1, "date": "2026-08-29", "srcDate": "29/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Global Sugar Prices Hit One-Year High: What’s Driving the Rise? - Caspian Post", "desc": "Rule-based: Global Sugar Prices Hit One-Year High: What’s Driving the Rise? Caspian Post Tác động sơ bộ: tích cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Caspian Post", "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNSzNwdXE4Um4zb01Ia1lOcUhvMnJEamFKSDh6UEozcVZWemswNzNweWRZa1VRRnI3VXhkTHZtc2tEWkJMQnFMd1NTNlZjOENJSzRnLTEtdVRlQmhiZGRtMmt0cGtMZFV0a2JvM0RqOHVtNk1RYmh5SkhlQmp2OVVKUGRMSms0NjJfNkJGczBldEZpUWZqZmZhcklxNA?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "61a53389c7994af8", "factor": "corn", "impact": 0, "date": "2026-08-29", "srcDate": "29/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Wheat Leads Grain Complex And Corn Matches the Pace - Iowa PBS", "desc": "Rule-based: Wheat Leads Grain Complex And Corn Matches the Pace Iowa PBS Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Iowa PBS", "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQeF9DYmkwYjVtdVdBenVhSzEyeWNkV1ptRERPQjFWejl0aUZraEZsTGMxVTMtTlhRdi15bUlwWGtmXzJUZHoxb3liaDV1Nk93M2NUNkN0QU56U2xkN1NZZHNYVHhsZHY3U095RXZ0X3NteUJVUk9zWFpzQUM4YUs0dW52N1ItWVkwOUxiUllHckZCS04zWW9QNVJtT285NU5XRVpYZFhreEIydzNrdS00?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "9a76391c67b2ecce", "factor": "sugar", "impact": 0, "date": "2026-08-29", "srcDate": "29/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Sugar Prices Retreat on Long Liquidation Pressures - Barchart.com", "desc": "Rule-based: Sugar Prices Retreat on Long Liquidation Pressures Barchart.com Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Barchart.com", "url": "https://news.google.com/rss/articles/CBMimgFBVV95cUxPdTZsN19jMzhxNW9iTlZuTV9Zc0VHLVhiSzVPc18yZmJLMWRLS205b19Oanhpeks0T2Q1U1NhZzNUTU1XWmpmcWJGWVJyRHItVlhSUlF4MUpKYWNtUE9jM2xrS1JTTlhSSFBwcDBCTVJjQ2V0SjdTZWpoRDNYcE9uQzBEaXR1enpPbUxpUmZMeEdQbnBReW9xdGlR?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "1ed5c1e481f36a97", "factor": "sugar", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Sugar Prices Fall As Low Indian Rates Cut Import Demand - Business Viewpoint Magazine", "desc": "Rule-based: Sugar Prices Fall As Low Indian Rates Cut Import Demand Business Viewpoint Magazine Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Business Viewpoint Magazine", "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTFBTMlNzSjJMd1p2Y2hITU1lZTRMd19RZ2lsOThSeTBHNExYdVRVZHVYVGR0b21YalpQU2Zwa1hLVW1OWUMtdDlpa0FqNXVZVlhSVGpTcmsxOS1pNHhtQkxwMERDUTczSDBzMEFCX0YxU3hnQzRlMXpMLQ?oc=5", "src": "news", "sourceScope": "intl"},
    {"id": "a208f23ce7f6a807", "factor": "corn", "impact": -1, "date": "2026-08-28", "srcDate": "28/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "Giá heo giảm, lợi nhuận của các 'ông lớn' ngành chăn nuôi ra sao? - Vietnam.vn", "desc": "Rule-based: Giá heo giảm, lợi nhuận của các 'ông lớn' ngành chăn nuôi ra sao? Vietnam.vn Tác động sơ bộ: tiêu cực theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Vietnam.vn", "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxPZzRxWUtQeG8wQ1VuN3dZYTZRZ2xURVBJcHo3WTdqeEZpMWtoVTRfWk0tMEFGRjVtM29aYUp5R2Q1NUlocmhyNmdmMl9KYm50Sm41LVdBRXRmdER1TExtOWpNYWFzOEhFdm9FR1h1U1R3VVcxNEpqSGJTeGxqZXI4anpEX0JfMG9VSHBnMA?oc=5", "src": "news", "sourceScope": "local"},
    {"id": "ea850146d0f3d580", "factor": "milk", "impact": 0, "date": "2026-08-28", "srcDate": "28/08/2026", "isNew": true, "aff": ["SBT", "QNS", "VNM", "DBC", "BAF"], "title": "USA dairy industry accelerates push to boost milk protein levels - Dairy Business Middle East & Africa", "desc": "Rule-based: USA dairy industry accelerates push to boost milk protein levels Dairy Business Middle East & Africa Tác động sơ bộ: trung tính/chờ kiểm chứng theo keyword; mở nguồn để kiểm chứng trước khi ra quyết định.", "srcName": "Dairy Business Middle East & Africa", "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOUUJMNjZFYzJyX2UyR2NRM2txYnM3QnRjOGwxVWJHQm1oMC1hVTI1RV9VSXplNVg2YU1obGNLc0RFZU1sWjR1TmUydEc3eU5VNGdmV0lkNXBKUE5HNUV2eTlWV1NmSzNyaThjd21GQ2Z3UjdKTWJVb3RUX0FsLWhRM002THZyMHNkQjVRZUNUTmQxdTd0emxpeUNadzF5QmluX1Y4TGsyTVQ?oc=5", "src": "news", "sourceScope": "intl"}
  ],
  // </NEWS-ITEMS>
  valuechain: [
    ["Đường", "Vùng mía; giá đường thế giới (#11) & nội; nhập lậu; CBPG đường Thái", "SBT, SLS, LSS, QNS", "Giá đường cao; phòng vệ TM hiệu quả; vùng nguyên liệu ổn"],
    ["Sữa", "Giá bột sữa nhập (WMP/SMP); sức mua; đàn bò; thị phần", "VNM, IDP, MCM, QNS (sữa đậu nành)", "Giá bột nhập rẻ; sức mua hồi phục; giữ/tăng thị phần"],
    ["Ngô & thức ăn chăn nuôi", "Giá ngô/khô đậu nhập; giá heo; dịch bệnh; tái đàn", "DBC, BAF, HAG", "Giá heo cao + nguyên liệu rẻ = biên tốt; tái đàn thuận lợi"],
    ["Sắn", "Giá sắn lát/tinh bột; cầu Trung Quốc; ethanol", "HAG (nông nghiệp) + DN tinh bột", "Cầu TQ tốt; giá tinh bột cao; xuất khẩu thuận lợi"],
    ["Chi phí & logistics", "Cước vận tải; năng lượng; phân bón; tỷ giá nhập nguyên liệu", "Toàn nhóm", "Cước & năng lượng giảm; tỷ giá ổn định"]
  ],
  tickers: [
    ["SBT", "Đường (lớn nhất); vùng mía; xuất khẩu; giá đường", "Giá đường cao; vùng nguyên liệu mở rộng; xuất khẩu tốt", "Giá đường giảm; đường nhập lậu; tồn kho; đòn bẩy cao"],
    ["SLS", "Đường; vùng mía Sơn La; biên cao; cổ tức tiền mặt", "Giá đường cao; năng suất mía tốt; cổ tức lớn", "Giá đường giảm; thời tiết bất lợi; diện tích mía"],
    ["LSS", "Đường + sau đường (điện, cồn); đa dạng hóa", "Giá đường tốt; mảng sau đường đóng góp", "Giá đường yếu; cạnh tranh; chi phí"],
    ["QNS", "Sữa đậu nành Vinasoy + đường; giá đậu nành; thị phần", "Vinasoy giữ thị phần; đường có lãi; giá đậu nành rẻ", "Cạnh tranh sữa đậu; giá đường giảm; sức mua"],
    ["VNM", "Sữa (đầu ngành); giá bột nhập; thị phần; xuất khẩu", "Giá WMP/SMP rẻ; giữ/tăng thị phần; xuất khẩu Trung Đông", "Sức mua yếu; mất thị phần; giá bột nhập tăng"],
    ["IDP", "Sữa (nhãn Kun); tăng trưởng; biên; marketing", "Tăng trưởng nhãn Kun; biên cao; phân phối mở rộng", "Cạnh tranh gay gắt; chi phí marketing; sức mua"],
    ["MCM", "Sữa (Mộc Châu); đàn bò; vùng nguyên liệu; hợp lực VNM", "Sản lượng sữa tươi tăng; hợp lực Vinamilk; thương hiệu", "Giá nguyên liệu; cạnh tranh; sức mua yếu"],
    ["DBC", "3F (feed–farm–food); giá heo; giá ngô/khô đậu; tái đàn", "Giá heo cao + nguyên liệu rẻ; tái đàn; vắc-xin ASF", "Giá heo thấp; dịch ASF; giá ngô cao; đòn bẩy"],
    ["BAF", "Chăn nuôi heo; giá heo; mở rộng đàn; chuỗi khép kín", "Giá heo cao; mở trại mới; chuỗi khép kín hiệu quả", "Giá heo thấp; dịch bệnh; đòn bẩy; pha loãng"],
    ["HAG", "Chuối + heo (+ sầu riêng); giá heo/chuối; cơ cấu nợ", "Giá heo/chuối tốt; giảm nợ; dòng tiền cải thiện", "Giá nông sản yếu; đòn bẩy cao; pha loãng"]
  ],
  sources: [
    ["Giá đường – Trading Economics", "https://tradingeconomics.com/commodity/sugar", "Giá đường thế giới (#11), tham chiếu giá nội địa"],
    ["Giá ngô – Trading Economics", "https://tradingeconomics.com/commodity/corn", "Giá ngô thế giới (đầu vào thức ăn chăn nuôi)"],
    ["Global Dairy Trade", "https://www.globaldairytrade.info/", "Giá đấu giá sữa bột WMP/SMP toàn cầu"],
    ["Tổng cục Hải quan", "https://www.customs.gov.vn/", "Xuất khẩu sắn/tinh bột sắn, nhập khẩu ngô/đậu/sữa"],
    ["AgroMonitor", "https://agromonitor.vn/", "Dữ liệu & giá nông sản (đường, TĂCN, sắn) trong nước"],
    ["Bộ Nông nghiệp & Môi trường", "https://www.mard.gov.vn/", "Chính sách nông nghiệp, dịch bệnh chăn nuôi"],
    ["Chăn nuôi Việt Nam", "https://channuoivietnam.com/", "Giá heo hơi 3 miền, giá nguyên liệu TĂCN"],
    ["Vinamilk IR", "https://www.vinamilk.com.vn/", "IR: KQKD, thị phần, sản lượng sữa"]
  ]
};
